### PR TITLE
Revert "framework/st_things : optimize stack size"

### PR DESCRIPTION
**Pull request by JeongJunSik**
This reverts commit 6d8cc9b64c7bde8aee1a0233fa00bd4fa1bdb940.

Reducing StackSize causes an assert error.
The stack size actually used is sufficient, but there seems to be a conflict issue.
After thorough review, I will upload it again.

### CODE REVIEW

**Comment by sunghan-chang** [comment]
@JeongJunSik Do you use stack monitor to optimize stack size?

**Comment by seinfra** [comment]
Target : [01d5ad89c7a325a05c66658011d10a4733186931] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [01d5ad89c7a325a05c66658011d10a4733186931] - Code Rule Check OK.

**Comment by JeongJunSik** [comment]
@sunghan-chang Yes, I am using a stack monitor, and I get a problem even when I'm bigger than the peak value.

**Pull request merged**
