### PR TITLE
To add Cypress 4390x board example application

### PR DESCRIPTION
**Pull request by CypressHJ**
This code is for Cypress 4390x board example. and test the merge process. 

BR, HJ Lee.

### CODE REVIEW

**Comment by seinfra** [comment]
Code Rule Check Result:
apps/examples/cy4390x_demo/cy4390x_demo_main.c:59: ERROR: [SPC_M_SEP] space prohibited after that open parenthesis '('
apps/examples/cy4390x_demo/cy4390x_demo_main.c:59: ERROR: [SPC_M_SEP] space prohibited before that close parenthesis ')'
apps/examples/cy4390x_demo/cy4390x_demo_main.c:62: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/cy4390x_demo/cy4390x_demo_main.c:63: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/cy4390x_demo/cy4390x_demo_main.c:66: ERROR: [SPC_M_SEP] space prohibited after that open parenthesis '('
apps/examples/cy4390x_demo/cy4390x_demo_main.c:66: ERROR: [SPC_M_SEP] space prohibited before that close parenthesis ')'
apps/examples/cy4390x_demo/cy4390x_demo_main.c:67: ERROR: [SPC_M_SEP] space prohibited after that open parenthesis '('
apps/examples/cy4390x_demo/cy4390x_demo_main.c:67: ERROR: [SPC_M_SEP] space prohibited before that close parenthesis ')'
apps/examples/cy4390x_demo/cy4390x_demo_main.c:76: ERROR: [SPC_M_SEP] space prohibited after that open parenthesis '('
apps/examples/cy4390x_demo/cy4390x_demo_main.c:76: ERROR: [SPC_M_SEP] space prohibited before that close parenthesis ')'
apps/examples/cy4390x_demo/cy4390x_demo_main.c:78: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/cy4390x_demo/cy4390x_demo_main.c:79: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/cy4390x_demo/cy4390x_demo_main.c:81: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/cy4390x_demo/cy4390x_demo_main.c:81: ERROR: [SPC_M_OPR] space required after that ',' (ctx:VxV)
apps/examples/cy4390x_demo/cy4390x_demo_main.c:81: ERROR: [SPC_M_SEP] space prohibited before that close parenthesis ')'
apps/examples/cy4390x_demo/cy4390x_demo_main.c:82: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/cy4390x_demo/cy4390x_demo_main.c:82: ERROR: [BRC_M_SMT] that open brace { should be on the previous line
apps/examples/cy4390x_demo/cy4390x_demo_main.c:82: ERROR: [SPC_M_SEP] space prohibited after that open parenthesis '('
apps/examples/cy4390x_demo/cy4390x_demo_main.c:82: ERROR: [SPC_M_SEP] space prohibited before that close parenthesis ')'
apps/examples/cy4390x_demo/cy4390x_demo_main.c:83: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/cy4390x_demo/cy4390x_demo_main.c:84: ERROR: [IDT_M_TAB] code indent should use tabs where possible
apps/examples/cy4390x_demo/cy4390x_demo_main.c:84: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/cy4390x_demo/cy4390x_demo_main.c:85: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/cy4390x_demo/cy4390x_demo_main.c:87: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/cy4390x_demo/cy4390x_demo_main.c:87: ERROR: [BRC_M_SMT] that open brace { should be on the previous line
apps/examples/cy4390x_demo/cy4390x_demo_main.c:87: ERROR: [SPC_M_SEP] space prohibited after that open parenthesis '('
apps/examples/cy4390x_demo/cy4390x_demo_main.c:87: ERROR: [SPC_M_SEP] space prohibited before that close parenthesis ')'
apps/examples/cy4390x_demo/cy4390x_demo_main.c:88: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/cy4390x_demo/cy4390x_demo_main.c:89: ERROR: [IDT_M_TAB] code indent should use tabs where possible
apps/examples/cy4390x_demo/cy4390x_demo_main.c:89: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/cy4390x_demo/cy4390x_demo_main.c:90: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/cy4390x_demo/cy4390x_demo_main.c:92: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/cy4390x_demo/cy4390x_demo_main.c:92: ERROR: [SPC_M_SEP] space prohibited after that open parenthesis '('
apps/examples/cy4390x_demo/cy4390x_demo_main.c:92: ERROR: [SPC_M_SEP] space prohibited before that close parenthesis ')'
apps/examples/cy4390x_demo/cy4390x_demo_main.c:94: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/cy4390x_demo/cy4390x_demo_main.c:103: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/cy4390x_demo/cy4390x_demo_main.c:104: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/cy4390x_demo/cy4390x_demo_main.c:106: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/cy4390x_demo/cy4390x_demo_main.c:107: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/cy4390x_demo/cy4390x_demo_main.c:109: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/cy4390x_demo/cy4390x_demo_main.c:109: ERROR: [BRC_M_SMT] that open brace { should be on the previous line
apps/examples/cy4390x_demo/cy4390x_demo_main.c:109: ERROR: [SPC_M_SEP] space prohibited after that open parenthesis '('
apps/examples/cy4390x_demo/cy4390x_demo_main.c:109: ERROR: [SPC_M_SEP] space prohibited before that close parenthesis ')'
apps/examples/cy4390x_demo/cy4390x_demo_main.c:110: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/cy4390x_demo/cy4390x_demo_main.c:111: ERROR: [IDT_M_TAB] code indent should use tabs where possible
apps/examples/cy4390x_demo/cy4390x_demo_main.c:111: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/cy4390x_demo/cy4390x_demo_main.c:112: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/cy4390x_demo/cy4390x_demo_main.c:113: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/cy4390x_demo/cy4390x_demo_main.c:113: ERROR: [BRC_M_SMT] that open brace { should be on the previous line
apps/examples/cy4390x_demo/cy4390x_demo_main.c:113: ERROR: [BRC_M_SMT] else should follow close brace '}'
apps/examples/cy4390x_demo/cy4390x_demo_main.c:114: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/cy4390x_demo/cy4390x_demo_main.c:115: ERROR: [IDT_M_TAB] code indent should use tabs where possible
apps/examples/cy4390x_demo/cy4390x_demo_main.c:115: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/cy4390x_demo/cy4390x_demo_main.c:116: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/cy4390x_demo/cy4390x_demo_main.c:125: ERROR: [SPC_M_OPR] spaces required around that '=' (ctx:VxV)
apps/examples/cy4390x_demo/cy4390x_demo_main.c:127: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/cy4390x_demo/cy4390x_demo_main.c:130: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/cy4390x_demo/cy4390x_demo_main.c:139: ERROR: [SPC_M_KWD] space required before the open parenthesis '('

**Comment by CypressHJ** [comment]
I updated c file for Code Rule Error.

**Comment by seinfra** [comment]
Code Rule Check Result:
apps/examples/cy4390x_demo/cy4390x_demo_main.c:81: ERROR: [SPC_M_OPR] space required after that ',' (ctx:VxV)
apps/examples/cy4390x_demo/cy4390x_demo_main.c:81: ERROR: [SPC_M_SEP] space prohibited before that close parenthesis ')'
apps/examples/cy4390x_demo/cy4390x_demo_main.c:82: ERROR: [BRC_M_SMT] that open brace { should be on the previous line
apps/examples/cy4390x_demo/cy4390x_demo_main.c:87: ERROR: [BRC_M_SMT] that open brace { should be on the previous line
apps/examples/cy4390x_demo/cy4390x_demo_main.c:109: ERROR: [BRC_M_SMT] that open brace { should be on the previous line
apps/examples/cy4390x_demo/cy4390x_demo_main.c:113: ERROR: [BRC_M_SMT] that open brace { should be on the previous line
apps/examples/cy4390x_demo/cy4390x_demo_main.c:113: ERROR: [BRC_M_SMT] else should follow close brace '}'

**Comment by seinfra** [comment]
Code Rule Check Result:
apps/examples/cy4390x_demo/cy4390x_demo_main.c:81: ERROR: [SPC_M_OPR] space required after that ',' (ctx:VxV)
apps/examples/cy4390x_demo/cy4390x_demo_main.c:81: ERROR: [SPC_M_SEP] space prohibited before that close parenthesis ')'
apps/examples/cy4390x_demo/cy4390x_demo_main.c:82: ERROR: [BRC_M_SMT] that open brace { should be on the previous line
apps/examples/cy4390x_demo/cy4390x_demo_main.c:87: ERROR: [BRC_M_SMT] that open brace { should be on the previous line
apps/examples/cy4390x_demo/cy4390x_demo_main.c:109: ERROR: [BRC_M_SMT] that open brace { should be on the previous line
apps/examples/cy4390x_demo/cy4390x_demo_main.c:113: ERROR: [BRC_M_SMT] that open brace { should be on the previous line
apps/examples/cy4390x_demo/cy4390x_demo_main.c:113: ERROR: [BRC_M_SMT] else should follow close brace '}'

**Comment by seinfra** [comment]
Code Rule Check Result:
apps/examples/cy4390x_demo/cy4390x_demo_main.c:81: ERROR: [SPC_M_SEP] space prohibited between function name and open parenthesis '('
apps/examples/cy4390x_demo/cy4390x_demo_main.c:81: ERROR: [SPC_M_OPR] space required after that ',' (ctx:VxV)

**Comment by CypressHJ** [comment]
commits will be changed.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Pull request closed without merging**
