### PR TITLE
apps/examples: Modify FUNCNAME on Makefile

### PR DESCRIPTION
**Pull request by YiHyunJin**
add FUNCNAME to APPNAME for user's convenience.

### CODE REVIEW

**Comment by sunghan-chang** [comment]
@YiHyunJin I don't understand what you want to say.
```
add FUNCNAME to APPNAME for user's convenience.
```

**Comment by YiHyunJin** [comment]
@sunghan-chang I wans to say what add APPNAME to FUNCNAME. if APPNAME is 'hello' and FUNCNAME is 'hello_main', I wanted to let the user fix APPNAME only

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Pull request merged**
