### PR TITLE
example/protobuf_enc_itc : add ITC for proto buf

### PR DESCRIPTION
**Pull request by manoj11588612**
New Testcase's:
1.ITCNegTestUint32f -> this as a negative testcase in which we are giving float input for comparing with 32 bit unsigned integer value
2.ITCNegTestBool -> this as a negative testcase in which we are giving float input for comparing with bool value
3.ITCNegTestInt32 -> this as a negative testcase in which we are giving float input for comparing with 32 bit  integer value
4.ITCNegTestInt64 -> this as a negative testcase in which we are giving float input for comparing with 64 bit integer value
5.ITCNegTestUint32 -> this as a negative testcase in which we are giving signed input for comparing with 32 bit unsigned integer value

Signed-off-by: manoj.g2 <manoj.g2@samsung.com>

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [feb9972a6e8a166783e00eecf7ca28d8aae14302] - Code Rule Check (C++) OK.

**Comment by manoj11588612** [comment]
@pillip8282 please review

**Comment by pillip8282** [comment]
@manoj11588612  This ITC is not different to prototest_main. So I think the ITC just duplicate the test cases.

**Comment by manoj11588612** [comment]
@pillip8282 
we developed 5 testcase  with negative scenario
These are not similar to ITC
1.ITCNegTestUint32f -> this as a negative testcase in which we are giving float input for comparing with 32 bit unsigned integer value
 2.ITCNegTestBool -> this as a negative testcase in which we are giving float input for comparing with bool value
 3.ITCNegTestInt32 -> this as a negative testcase in which we are giving float input for comparing with 32 bit integer value
 4.ITCNegTestInt64 -> this as a negative testcase in which we are giving float input for comparing with 64 bit integer value
 5.ITCNegTestUint32 -> this as a negative testcase in which we are giving signed input for comparing with 32 bit unsigned integer value

**Comment by pillip8282** [comment]
@manoj11588612 
I think those negative cases are similar. I think they're negative UTCs. I think that template of ITC and UTC should be different

**Pull request closed without merging**
