### PR TITLE
external/stress_tool: Add ST_EXPECT_EQ2 and ST_EXPECT_NEQ

### PR DESCRIPTION
**Pull request by SeonghoByeon**
- Modify ST_EXPECT to ST_EXPECT_EQ
- Add ST_EXPECT_EQ2 for handling two types of return values
- Modify corresponding applications using stress test tool

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [49b92964298e7b80d746343b26f327d2d3fd7c8e] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [49b92964298e7b80d746343b26f327d2d3fd7c8e] - Code Rule Check OK.

**Comment by jsdosa** [comment]
I think,
it would be nice to have a description of what to expect in the function name.
This is not a fix, but for example. ST_EXPECT to ST_EXPECT_EQ (NEQ looks good.)

**Comment by SeonghoByeon** [comment]
@jsdosa Thanks for the comment. Applied.

**Comment by seinfra** [comment]
Target : [2266f9cbc10649c5b3dff9c8631c1c38cd5ed8aa] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [2266f9cbc10649c5b3dff9c8631c1c38cd5ed8aa] - Code Rule Check (C++) OK.

**Pull request merged**
