### PR TITLE
IMXRT1020-EVK:

### PR DESCRIPTION
**Pull request by btheosam**
Download script changes to fix long boot delay

imxrt1020-evk_download.sh: Read the configured partitions and input passed on to
download script and perform action ONLY on the input partition.

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [bed088e36d8ef921d514bc0fe2debe893a28bffa] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [bed088e36d8ef921d514bc0fe2debe893a28bffa] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [2c565b0d6f03f577bb91b8c94063ca36af5886b5] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [2c565b0d6f03f577bb91b8c94063ca36af5886b5] - Code Rule Check OK.

**Comment by sunghan-chang** [comment]
@btheosam Could you write the title with what you modify simply? It is written in our commit rules.

**Comment by seinfra** [comment]
Target : [5686ec247fecdc1d3932ecf0ee233996a9300459] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [5686ec247fecdc1d3932ecf0ee233996a9300459] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [6b89eb656ed71ca9af99feb349b548b3ef775716] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [6b89eb656ed71ca9af99feb349b548b3ef775716] - Code Rule Check (C++) OK.

**Pull request merged**
