### PR TITLE
Media: Add BufferInputDataSource

### PR DESCRIPTION
**Pull request by junmin-kim**
Data comes through the buffer.
Callback should be used.

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [5ab5c00720e3432643d2df94da441106814e94e6] - Code Rule Check Result:
framework/include/media/BufferInputDataSource.h:45: ERROR: [SPC_M_OPR] spaces prohibited around that ':' (ctx:WxW)
framework/include/media/BufferInputDataSource.h:67: ERROR: [SPC_M_OPR] need consistent spacing around '&' (ctx:VxW)
framework/include/media/BufferInputDataSource.h:73: ERROR: [SPC_M_OPR] need consistent spacing around '&' (ctx:VxW)
framework/include/media/BufferInputDataSource.h:73: ERROR: [SPC_M_OPR] spaces required around that '=' (ctx:VxV)
framework/include/media/BufferInputDataSource.h:73: ERROR: [SPC_M_OPR] need consistent spacing around '&' (ctx:VxW)

**Comment by seinfra** [comment]
Target : [5ab5c00720e3432643d2df94da441106814e94e6] - Code Rule Check (C++) OK.

**Comment by jsdosa** [comment]
@junmin-kim, need check the #1960

**Comment by junmin-kim** [comment]
I'll fix after #1960 is merged

**Pull request closed without merging**
