### PR TITLE
artik053/audio: fix configurations that use wifi manager

### PR DESCRIPTION
**Pull request by pillip8282**
As wifi manager setting is changed, all configurations that use wifi manager
should be changed.

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [1a86abc5ad18b86b447eb7f3a6b5c55195da85e6] - Code Rule Check (C++) OK.

**Comment by pillip8282** [comment]
@davidfather 
Actually I was going to modify all configurations that use wifi manager. But only audio configuration was left. so title is confusing.

**Comment by seinfra** [comment]
Target : [3af3ab4c576de2c88921b90ad65acd9e03fcbca3] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [3af3ab4c576de2c88921b90ad65acd9e03fcbca3] - Code Rule Check OK.

**Pull request merged**
