### PR TITLE
media: Add nullptr check at FileDataSource.close

### PR DESCRIPTION
**Pull request by junmin-kim**
flcose(nullptr) could occur an error.

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [8c6f8193bdaf4b800046c5788e73fff0e1c36c5a] - Code Rule Check (C++) OK.

**Comment by jsdosa** [comment]
@junmin-kim 
open function also required conditions.

**Comment by seinfra** [comment]
Target : [8c6f8193bdaf4b800046c5788e73fff0e1c36c5a] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [472b6355593a578cd943ed2a8d75bd5aaaf549b5] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [472b6355593a578cd943ed2a8d75bd5aaaf549b5] - Code Rule Check OK.

**Pull request merged**
