### PR TITLE
[SYNC] from Samsung/TizenRT (sync/protection/20190321-1340)

### PR DESCRIPTION
**Pull request by whatwant**
Sync

Merge between 5fc8b94(protection) and ecd51d4(sync/protection/20190321-1340)

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [ecd51d4432ae3be5fe137d24d1d2e459ff30d032] - Code Rule Check Result:
os/include/tinyara/mm/mm.h:789: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/include/tinyara/mm/mm.h:789: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/include/tinyara/mm/mm.h:790: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/include/tinyara/mm/mm.h:790: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/include/tinyara/mm/mm.h:791: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/include/tinyara/mm/mm.h:791: ERROR: [IDT_M_TAB] please, no spaces at the start of a line

**Comment by seinfra** [comment]
Target : [ecd51d4432ae3be5fe137d24d1d2e459ff30d032] - Code Rule Check (C++) OK.

**Comment by sunghan-chang** [comment]
@kishore-sn RAM Partition commit causes violations of coding rules as shown above. Our detection tool is not perfectly working. Please consider it when you make a PR. Thank you.

**Comment by kishore-sn** [comment]
OK. I will fix it in my next PR.

**Pull request closed without merging**
