### PR TITLE
net/local: Add uds_checksd

### PR DESCRIPTION
**Pull request by junmin-kim**
Add uds_checksd function and connect with netmgr

### CODE REVIEW

**Comment by junmin-kim** [comment]
@pillip8282 I raised a draft. How about this approach?

**Comment by seinfra** [comment]
Target : [8344aff3d7b703f2e7da20c9b89aaa125fb0ff15] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [8344aff3d7b703f2e7da20c9b89aaa125fb0ff15] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [b367dc71e9c2afdc62b78388674dd122709216b8] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [b367dc71e9c2afdc62b78388674dd122709216b8] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [c3fef2acf9fe992826f452557f478053ede5f5c6] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [c3fef2acf9fe992826f452557f478053ede5f5c6] - Code Rule Check OK.

**Pull request merged**
