### PR TITLE
Add a copyright in curl_config.h

### PR DESCRIPTION
**Pull request by HONGCHAEHEE**
This file needs a copyright.

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [a3e8b69f9874430e0f56006010d45abef1923de7] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [a3e8b69f9874430e0f56006010d45abef1923de7] - Code Rule Check OK.

**Comment by sunghan-chang** [comment]
@HONGCHAEHEE Original Curl makes this file automatically when it is built using cmake. But we don't support cmake so that we use fixed file. Let's leave comments to say that difference on file.

**Comment by HONGCHAEHEE** [comment]
@sunghan-chang Thank you. I left your comments on file.

**Comment by seinfra** [comment]
Target : [539bd52ab23754578b59f440f7b7a70bbf00a8d4] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [539bd52ab23754578b59f440f7b7a70bbf00a8d4] - Code Rule Check OK.

**Pull request merged**
