### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by chaewon6**
apps/examples/nettest/nettest.c
line 190, 192 : continousely -> continuously

apps/examples/wakaama_client/wakaama_client.c
line 165 trying connect -> trying connection

apps/examples/tls_client/tls_client_main.c
line 393 sucesseding -> succeeding

apps/examples/telnetd/telnetd.c
line 298 tart -> start

apps/examples/speech_detector_test/speech_detector_test_main.cpp
line 45, 47 create -> creation
line 75, 77 prepare -> preparation

apps/examples/smart_test/smart_test.c
line 220,273 Conducts an append test on the file. -> Conducts a test on the appended file.
line 238,252,260 append -> appended file

apps/examples/smart/smart_main.c
line 506 info -> into
line 529 try -> try to
line 578 Succesffully -> Successfully

apps/examples/slsiwifi/slsiwifi_main.c
line 59 worst -> the worst
line 170 sanity -> sane
line 345 highest -> the highest

apps/examples/mtdpart/mtdpart_main.c
line 414,504 Verfy -> Verify
line 458 Try reading -> Try to reading

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [dabdc331c96c787fdabf812640df2fb5a1214c5c] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [dabdc331c96c787fdabf812640df2fb5a1214c5c] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [e45198ddcac10ceb6d70f409f92fc277ab7fb0ee] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [e45198ddcac10ceb6d70f409f92fc277ab7fb0ee] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [1266dfcf6a581152928dd8f146d3be53cef309c5] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [1266dfcf6a581152928dd8f146d3be53cef309c5] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [1bd748ced94408749036870349450bdfe03526cf] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [3c0dcfffae17ab3a09fa260068cb80443096dd93] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [3c0dcfffae17ab3a09fa260068cb80443096dd93] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [6334cb8162aea5997b5879b496bee2fdfc462ca5] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [6334cb8162aea5997b5879b496bee2fdfc462ca5] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [1c78ba8393f75e2123166e2142041065b74ce073] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [5e8483e95c46fce9bde6ae9e2e774869cc8a5f27] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [5e8483e95c46fce9bde6ae9e2e774869cc8a5f27] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [27eba1ea2879266b01768412cbe05d10f2904308] - Code Rule Check OK.

**Comment by sunghan-chang** [comment]
@chaewon6 Thank you for contribution. But it is difficult to merge all of commits. Some change is correct on grammar but it is not good at meaning.
for example `append test` is testing `append` functionality. It is not a test for appended file.
And we can't merge some commits like `there are something wrong `.

So, let's close this. Thank you again.

**Pull request closed without merging**
