### PR TITLE
errno: Add key error number

### PR DESCRIPTION
**Pull request by junmin-kim**
ENOKEY, EKEYEXPIRED, EKEYREVOKED, EKEYREJECTED are added

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [44544d419789054fed1b080d79ded330b39b52cc] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [44544d419789054fed1b080d79ded330b39b52cc] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [2a6c155cf17492f8d93149616d738e9dc3daaaf9] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [2a6c155cf17492f8d93149616d738e9dc3daaaf9] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [9d8013430fc71a1d033bea3c6ebea4a378a49ab8] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [9d8013430fc71a1d033bea3c6ebea4a378a49ab8] - Code Rule Check (C++) OK.

**Comment by junmin-kim** [comment]
Do not merge. Now on discuss

**Comment by seinfra** [comment]
Target : [74ea097567f5776c7b4fc4bde611f80ba1629a5f] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [74ea097567f5776c7b4fc4bde611f80ba1629a5f] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [c8f5bca9df7bbe590de8c53dd29cb283e30f70e4] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [c8f5bca9df7bbe590de8c53dd29cb283e30f70e4] - Code Rule Check OK.

**Pull request merged**
