### PR TITLE
framework/st_things: making the code align.

### PR DESCRIPTION
**Pull request by Hyunjun85**
1. Fixes indentation with spaces.
2. The tab cannot be placed middle of lines.

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [23196248891bb43aaeef7c4a0a9fa68a48e7c1af] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [23196248891bb43aaeef7c4a0a9fa68a48e7c1af] - Code Rule Check (C++) OK.

**Comment by sunghan-chang** [comment]
@Hyunjun85 I am sorry for not to give comments at once. But this is not an applying coding rule. There is no coding rule for this. Let's say `make it beautifuler` or `make it align` or something else.

**Comment by Hyunjun85** [comment]
@sunghan-chang I have changed the title.
Thanks for your help.

**Comment by seinfra** [comment]
Target : [ea0a579234cfecdb970f016e3e40fc3969c5bb9b] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [ea0a579234cfecdb970f016e3e40fc3969c5bb9b] - Code Rule Check OK.

**Pull request merged**
