### PR TITLE
apps/examples/testcase/filesystem: Fix fs mops fail TC

### PR DESCRIPTION
**Pull request by KimDongEon**
Fix failed test cases

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [990293947ad5df2c38f062d3231b66a8c25ab819] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [990293947ad5df2c38f062d3231b66a8c25ab819] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [da141063142412852471046213423935c9c8ff00] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [da141063142412852471046213423935c9c8ff00] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [d112f4eacc8d6a0ed3af380c0e634deab2b68d77] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [d112f4eacc8d6a0ed3af380c0e634deab2b68d77] - Code Rule Check OK.

**Comment by KimDongEon** [comment]
@chanijjani 
have complemented the failure.

**Pull request merged**
