### PR TITLE
imxrt1050-evk/userspace: Add config dependency (CONFIG_SYSTEM_PREAPP_INIT)

### PR DESCRIPTION
**Pull request by NilabhShant**
This patch adds config check for system pre-application init.

Signed-off-by: Nilabh <n.shant@partner.samsung.com>

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [7fe510fba2730be45b68829820723cca1f2ad578] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [7fe510fba2730be45b68829820723cca1f2ad578] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [a54df430938faff751f4769c834b6e03dae35352] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [a54df430938faff751f4769c834b6e03dae35352] - Code Rule Check OK.

**Comment by NilabhShant** [comment]
> userspace.h also needs to modify like here.

Yes, I fix it.

**Pull request merged**
