### PR TITLE
travis: modify .travis.yml to maintain latest docker image

### PR DESCRIPTION
**Pull request by an4967**
- TizenRT docker image is updated (ver. 1.5.0)
- new toolchain, xtensa-esp32-elf is added.

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [b7ad9f3abe2ead19db4c01b5bdc43e85d0fb4345] - Code Rule Check (C++) OK.

**Comment by sunghan-chang** [comment]
@an4967 Let's say `esp32 toolchain support` at commit title. `travis` looks incorrect.
There is no relationship between travis and docker.
```
docker: support esp32 toolchain with version xxx
```

**Comment by sunghan-chang** [comment]
PR title is not important. Please change a commit title.

**Comment by seinfra** [comment]
Target : [ac45d2a7330df98f8b42a5cdbd3eff9c19d1fe10] - Code Rule Check OK.

**Pull request merged**
