### PR TITLE
apps/testcase/audio : give the frame count in pcm_readi

### PR DESCRIPTION
**Pull request by vir2u3**
itc_audio_pcm_readi_p
1.give the proper frame count in pcm_readi

Signed-off-by: sri <sri@s.sa.corp.samsungelectronics.net>

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [6e8c213c519951166217312ee15fffc10c092263] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [6e8c213c519951166217312ee15fffc10c092263] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [6e8c213c519951166217312ee15fffc10c092263] -

**Comment by vir2u3** [comment]
@sunghan-chang @sangwon03 please review

**Pull request merged**
