### PR TITLE
configs/rtl8721csm/scripts: Modify linker script to move app data to psram

### PR DESCRIPTION
**Pull request by jeongchanKim**

### CODE REVIEW

**Comment by sunghan-chang** [comment]
@keerthanalex Could you review this PR? This PR reverts yours and applies another way due to booting failure on loadable with yours.

**Comment by keerthanalex** [comment]
> @keerthanalex Could you review this PR? This PR reverts yours and applies another way due to booting failure on loadable with yours.

Ok @sunghan-chang , I'll check the performance tomorrow in office and update you on the same.

**Comment by sunghan-chang** [comment]
@keerthanalex Any update?

**Comment by keerthanalex** [comment]
> @keerthanalex Any update?

@sunghan-chang , Please find the test result as below



hello   config | default TizenRT   master[f99f12c] | default TizenRT   master[f99f12c] + PR #4970
-- | -- | --
TX throughput | ~30 Mbps | ~30 Mbps
RX throughput | ~30 Mbps | ~30 Mbps
SRAM heap consumed | 100572a0 | 10057a20   (1920 bytes more)

The performance result is almost same as compared to PR #4920  but SRAM heap consumption seems to be more.

With ble code on ble_combo_tester_main config,



ble_combo_tester_main   config | default TizenRT   master[f99f12c] | default TizenRT   master[f99f12c] + PR #4970
-- | -- | --
SRAM heap consumed | 100585c0 | 10059700   (4416 bytes more)

Do you know the reason for loadable apps config boot fail with PR #4920 ?
To avoid unexpected SRAM heap consumption in future(which in turn might affect performance), It looks necessary to keep only required files on SRAM.

**Comment by jeongchanKim** [comment]
> > @keerthanalex Any update?
> 
> @sunghan-chang , Please find the test result as below
> 
> hello config	default TizenRT master[[f99f12c](https://github.com/Samsung/TizenRT/commit/f99f12c688d0bfcf6169c357049222d17b7faa5f)]	default TizenRT master[[f99f12c](https://github.com/Samsung/TizenRT/commit/f99f12c688d0bfcf6169c357049222d17b7faa5f)] + PR #4970
> TX throughput	~30 Mbps	~30 Mbps
> RX throughput	~30 Mbps	~30 Mbps
> SRAM heap consumed	100572a0	10057a20 (1920 bytes more)
> The performance result is almost same as compared to PR #4920 but SRAM heap consumption seems to be more.
> 
> With ble code on ble_combo_tester_main config,
> 
> ble_combo_tester_main config	default TizenRT master[[f99f12c](https://github.com/Samsung/TizenRT/commit/f99f12c688d0bfcf6169c357049222d17b7faa5f)]	default TizenRT master[[f99f12c](https://github.com/Samsung/TizenRT/commit/f99f12c688d0bfcf6169c357049222d17b7faa5f)] + PR #4970
> SRAM heap consumed	100585c0	10059700 (4416 bytes more)
> Do you know the reason for loadable apps config boot fail with PR #4920 ?
> To avoid unexpected SRAM heap consumption in future(which in turn might affect performance), It looks necessary to keep only required files on SRAM.

We don't know why loadable fails with PR#4920. We should check what is different between with #4920 or without.
I have a question. You said that heap consumption is around 4K higher. Is this from real heap consumption(dynamic allocation)? or from global variable?

**Comment by keerthanalex** [comment]
> > > @keerthanalex Any update?
> > 
> > 
> > @sunghan-chang , Please find the test result as below
> > hello config	default TizenRT master[[f99f12c](https://github.com/Samsung/TizenRT/commit/f99f12c688d0bfcf6169c357049222d17b7faa5f)]	default TizenRT master[[f99f12c](https://github.com/Samsung/TizenRT/commit/f99f12c688d0bfcf6169c357049222d17b7faa5f)] + PR #4970
> > TX throughput	~30 Mbps	~30 Mbps
> > RX throughput	~30 Mbps	~30 Mbps
> > SRAM heap consumed	100572a0	10057a20 (1920 bytes more)
> > The performance result is almost same as compared to PR #4920 but SRAM heap consumption seems to be more.
> > With ble code on ble_combo_tester_main config,
> > ble_combo_tester_main config	default TizenRT master[[f99f12c](https://github.com/Samsung/TizenRT/commit/f99f12c688d0bfcf6169c357049222d17b7faa5f)]	default TizenRT master[[f99f12c](https://github.com/Samsung/TizenRT/commit/f99f12c688d0bfcf6169c357049222d17b7faa5f)] + PR #4970
> > SRAM heap consumed	100585c0	10059700 (4416 bytes more)
> > Do you know the reason for loadable apps config boot fail with PR #4920 ?
> > To avoid unexpected SRAM heap consumption in future(which in turn might affect performance), It looks necessary to keep only required files on SRAM.
> 
> We don't know why loadable fails with PR#4920 yet. We should check what is different between with #4920 or without.
> I have a question. You said that heap consumption is around 4K higher. Is this from real heap consumption(dynamic allocation)? or from global variable?

The heap consumption is 4K higher for ble_combo_tester_main config with ble code but the coex performance is not affected.
It is the static heap consumption value from "target_img2.map" of build config.

**Comment by sunghan-chang** [comment]
Because
1. This is working on flat build as well as loadable build.
2. There is no SRAM overflow on real usages with this.
3. We have no plan to debug @keerthanalex 's change on loadable.
I am going to merge this.
@keerthanalex Could you let me know if you have another opinion?

**Comment by keerthanalex** [comment]
> Because
> 
> 1. This is working on flat build as well as loadable build.
> 2. There is no SRAM overflow on real usages with this.
> 3. We have no plan to debug @keerthanalex 's change on loadable.
> 
> I am going to merge this.
> @keerthanalex Could you let me know if you have another opinion?

@sunghan-chang, I haven't found the reason for boot fail yet. So you can go ahead with the merge, I'll let you know if there is any update on this.

**Comment by sunghan-chang** [comment]
@keerthanalex Ok, thank you for update.

**Review by sunghan-chang — APPROVED** [review]

**Pull request merged**
