### PR TITLE
config: Enable SCSC driver instead of none

### PR DESCRIPTION
**Pull request by rzr**
Observed issue:

    wireless/scsc/max_buf.h:24:24:
    fatal error: utils_misc.h: No such file or directory

Also other changes are generated by using "make menuconfig",
some features were enabled by default
but to make this change minimal,
they were disabled again to align current base

Change-Id: I647c0689e6764b1b18c4eca96b041a108dcab69e
Signed-off-by: Philippe Coval <p.coval@samsung.com>

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [a0ce2f0759b3a6f68817b36978822e77797947e4] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [a0ce2f0759b3a6f68817b36978822e77797947e4] - Code Rule Check OK.

**Comment by sunghan-chang** [comment]
@rzr Thank you for contribution. Could you write exact location where you modify at commit title?
```
configs/artik055s/nettest: Enable SCSC driver instead of none

Observed issue:

    wireless/scsc/max_buf.h:24:24:
    fatal error: utils_misc.h: No such file or directory

Also other changes are generated by using "make menuconfig",
some features were enabled by default
but to make this change minimal,
they were disabled again to align current base

Change-Id: I647c0689e6764b1b18c4eca96b041a108dcab69e
Signed-off-by: Philippe Coval <p.coval@samsung.com>
```

**Comment by seinfra** [comment]
Target : [a561fac7dc7e548cd24a75b2987fdd2cd6c78432] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [a561fac7dc7e548cd24a75b2987fdd2cd6c78432] - Code Rule Check OK.

**Comment by sunghan-chang** [comment]
@rzr I am sorry but we don't need to know your private path, ```sandbox/rzr/review/artik/master```. I meant file path on TizenRT as I left an example.
```
configs/artik055s/nettest: Enable SCSC driver instead of none
```

**Comment by rzr** [comment]
Sorry I was distracted ;)

**Comment by seinfra** [comment]
Target : [c1321fd0846ab62ac7063b7f3e49ab5582c58ab7] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [c1321fd0846ab62ac7063b7f3e49ab5582c58ab7] - Code Rule Check OK.

**Comment by sunghan-chang** [comment]
@rzr Thank you for changing. I merged.

**Comment by rzr** [comment]
Thank you for your patience
I will share an other patch about configs soon

**Pull request merged**
