### PR TITLE
le_tc/kernel : add ITCs for libc_stdlib

### PR DESCRIPTION
**Pull request by arvinmittal**
Scenarios ITCs perform below tests:
convert string to integer with diff combination
string to long integer conversion with diff combination
convert string to long long integer with diff combination
convert string to double with diff combination
compute quotient and remainder for negative number
compute quotient and remainder for zero number

Signed-off-by: Arvin Mittal <arvin.mittal@samsung.com>

### CODE REVIEW

**Comment by arvinmittal** [comment]
@samegautam 
Please review.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by samegautam** [comment]
Looking good to me
@sunghan-chang  : please review the changes and merge.

**Comment by sunghan-chang** [comment]
@arvinmittal @samegautam Hello.
This change looks like utc, not itc. Same function but different inputs.

**Comment by arvinmittal** [comment]
@sunghan-chang 
earlier in UTCs, inputs used were only positive number type, but in ITCs API is verified on different input types of positive, negative and zero integer type

**Comment by sunghan-chang** [comment]
@arvinmittal So, yours supplements UTC. That is not a kind of ITC.

**Pull request closed without merging**
