### PR TITLE
1020 dl prot

### PR DESCRIPTION
**Pull request by btheosam**

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [9d7c7405a503dce00650415d7f9b0b0a53e837ac] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [9d7c7405a503dce00650415d7f9b0b0a53e837ac] - Code Rule Check OK.

**Comment by btheosam** [comment]
> Please modify the Make.defs of wifi_loadable as well.

Done.

**Comment by seinfra** [comment]
Target : [6662f72b6608e4785ad10333db284d096f337e0c] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [6662f72b6608e4785ad10333db284d096f337e0c] - Code Rule Check (C++) OK.

**Pull request merged**
