### PR TITLE
os/board/rtl8730e: Support scanning of multiple specified APs

### PR DESCRIPTION
**Pull request by jwei5**
* Add API wifi_netmgr_utils_scan_multi_ap() to scan up to 6 specified APs
* If the channel of any of the APs to scan is set to 0, scan will be done on all valid channels
* Add scan option RTW_SCAN_ALL to support including results of other APs when scanning for specified APs

### CODE REVIEW

**Comment by Jw00** [comment]
Thank you for your working, I will check this and then share the test result with you.

**Comment by jwei5** [comment]
Due to a conflict when PR #6199 is merged, please do not merge this PR yet.
I will rebase this PR after PR #6199 is merged.

**Comment by sunghan-chang** [comment]
@jwei5 I merged the PR #6199 . Could you rebase this?

**Comment by jwei5** [comment]
Hi @sunghan-chang , @Jw00 , I have rebased this PR

**Comment by Jw00** [comment]
> Hi @sunghan-chang , @Jw00 , I have rebased this PR, could you help to check it again? Thanks.

I will check the latest version.

**Comment by edwakuwaku** [comment]
Hi @sunghan-chang  @Jw00 , sorry for interrupting. But as you know, recently there are quite many changes in our km4_km0 binary in different PR, and due to pending verification in Tizen Lite, it cause extra effort for us to maintain the commit ordering in our internal branch (ie. rebase/recommit).
Thus, since this feature is necessary, and it has been quite a while, could you share the test result and merge it asap?
Thank you for your understanding.

**Review by Jw00 — APPROVED** [review]
I've checked this PR works well.
Thank you for your works.

**Review by sunghan-chang — APPROVED** [review]

**Pull request merged**
