### PR TITLE
framework/st_things : Clean up things logger

### PR DESCRIPTION
**Pull request by JeongJunSik**
- Removed unnecessary logger api and changed to output waring, error, debug, info only

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [3beda716966993dd82da4c74c831411fd7d20dda] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [3beda716966993dd82da4c74c831411fd7d20dda] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [797cd29458a4ce7c39220bffa206da5b6a0ddf25] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [797cd29458a4ce7c39220bffa206da5b6a0ddf25] - Code Rule Check (C++) OK.

**Comment by juitem** [comment]
Would you please fix conflicts?

**Comment by seinfra** [comment]
Target : [f3ce26b202f0ddeaa6e70751d9bfbc5a8c0a26a4] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [f3ce26b202f0ddeaa6e70751d9bfbc5a8c0a26a4] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [dde361db42e94eedb2c049673fe1a6594b0a750e] -

**Comment by seinfra** [comment]
Target : [388b883c8585b5cf4f5cc1e3b62fa22ea67644fa] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [388b883c8585b5cf4f5cc1e3b62fa22ea67644fa] - Code Rule Check OK.

**Pull request merged**
