### PR TITLE
framework/binary_manager, messaging : Modify TizenRT API version from…

### PR DESCRIPTION
**Pull request by jeongchanKim**
… v3.0 PRE to v3.0

TizenRT releases the version 3.0 at Dec 29th 2019.
But binary manager and messaging APIs' version were not changed yet, so fixed them.

### CODE REVIEW

**Review by pillip8282 — APPROVED** [review]
lgtm

**Review by davidfather — APPROVED** [review]
Looks good to me.

**Review by jsdosa — APPROVED** [review]
looks nice to me.

**Review by jeongarmy — APPROVED** [review]
It looks good

**Review by sunghan-chang — APPROVED** [review]

**Pull request merged**
