### PR TITLE
build/configs: Add meta files to support esp32 boards on RT IDE

### PR DESCRIPTION
**Pull request by zhouxinhe**
To support build and flash project with Tizen Studio RT IDE on esp32 boards.
(co-work with PR #4023)

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [9343847c2257e3e454845e9514bf3512cd5c9f07] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [9343847c2257e3e454845e9514bf3512cd5c9f07] - Code Rule Check (C++) OK.

**Comment by sunghan-chang** [comment]
@zhouxinhe Regardless of this PR, is there any way to debug like gdb in ARM?

**Comment by zhouxinhe** [comment]
> @zhouxinhe Regardless of this PR, is there any way to debug like gdb in ARM?

We can use gdb-debugging on esp32 boards, so it is possible.
Actually, I tried to do that, but it's difficult to use debug funtion of RT IDE for me now, so I can not verify it. I plan to enable it in future.

**Pull request merged**
