### PR TITLE
apps/example/testcase/media : Fix build issue of multiple definition

### PR DESCRIPTION
**Pull request by manoj11588612**
remove the multiple definition code from media itc code

Signed-off-by: manoj <manoj.g2@samsung.com>

### CODE REVIEW

**Comment by manoj11588612** [comment]
@Taejun-Kwon @samegautam 
please approve

**Comment by seinfra** [comment]
Target : [85df4cd5b01f3c76c9a13c6161d1ca94208408d3] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [85df4cd5b01f3c76c9a13c6161d1ca94208408d3] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [85df4cd5b01f3c76c9a13c6161d1ca94208408d3] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [85df4cd5b01f3c76c9a13c6161d1ca94208408d3] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [85df4cd5b01f3c76c9a13c6161d1ca94208408d3] - Code Rule Check (C++) OK.

**Pull request closed without merging**
