### PR TITLE
Added code for checking if fd open is success

### PR DESCRIPTION
**Pull request by krishshanmukh**
1. Added code for checking if fd open is success
2. fd is not closed while returning(if error). Closed fd before returning

### CODE REVIEW

**Comment by sunghan-chang** [comment]
This includes below pull reqeust. What do you want to merge?

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by krishshanmukh** [comment]
Hi @sunghan-chang ,
The other 2 pull requests are based out of another file. So I've raised a different pull request. 
I'm new to contributing to open source. May I know if I can make all the related changes in a single pull request or if I have to raise different ones, as I have done now?

**Comment by sunghan-chang** [comment]
If they have a dependancy or same kind of changes, then you can raise them at a pull reqeust.

**Comment by sunghan-chang** [comment]
Are you a SRIB engineer?

**Comment by krishshanmukh** [comment]
@sunghan-chang .. Yes.. I'm SRIB engineer

**Pull request closed without merging**
