### PR TITLE
WIP: Rebase IoT.js on current upstream

### PR DESCRIPTION
**Pull request by rzr**
I tried to split changes to make tracking easier

Using HEAD was suggested by IoT.js's @zherczeg as latest release (1.0) is a bit old now

Note, this patch is pretty big and all changes have already been reviewed either upstream or downstream, so don't panic you can skip reviewing if agrea on strategy and commit messages.

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [2101d7b9f4a9b7404b02c8d5a4e1b78eca37fd61] -

**Comment by seinfra** [comment]
Target : [f34b7e05de7dda5e1db0e32c1a736817857b17a1] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [f34b7e05de7dda5e1db0e32c1a736817857b17a1] - Code Rule Check OK.

**Comment by sunghan-chang** [comment]
@rzr Is this discussed with IoTjs maintainers, @haesik and @hs0225 ?

**Comment by sunghan-chang** [comment]
@rzr Additionally Is ```external/iotjs/config/tizenrt/Kconfig.runtime``` alive in this PR?

**Comment by sunghan-chang** [comment]
@rzr I've asked @hs0225 about this PR. He said, he can't confirm it is ok or not (Previous one was fully tested on a board). I am not a maintainer of iotjs so that I can't merge that without confirmation of iotjs maintainer. Could you talk this at iotjs community?

**Comment by rzr** [comment]
Thanks for feedback, I knew that this patch will not go through without discussions first.

First let me comment about your questions

1/

Yes I have previously upstreamed TizenRT's Kconfig.runtime to IoT.js 

tizenrt: Import Kconfig.runtime from TizenRT sources #1452 
https://github.com/Samsung/iotjs/pull/1452

And prepared the transition in TizenRT:

WISH: iotjs: Sync iotjs upstream in Tizen:RT #1277 
https://github.com/Samsung/TizenRT/pull/1277


2/

About upstream coordination, I have announced in freenode my intention to update iotjs in TizenRT

```
<RzR> akiss, hi my patch went in, now I am trying to propose upgrade
<RzR> I noticed that some downstream patches werent forwarded to you
<RzR> I'll try to upstream thoses too
<RzR> zherczeg, hi I am talking about iotjs in Tizen:RT
<zherczeg> ok
<RzR> zherczeg, I'll keep you updated, let me know if you plan to tag a version soon, I'll double check that nothing is missing and make sure it will be easy to sync
<akiss> RzR: nice, looking forward
<akiss> thanks for the update
<RzR> you're welcome, I hope it will help cooperation and then we'll can consider to switch to git modules
<RzR> meanwhile I tried to split the changes in https://github.com/Samsung/TizenRT/pull/2018
<zherczeg> wow that is a huge patch
<RzR> it's a raw import
<RzR> don't panic
<RzR> code has been already reviewed
```

Should this be discussed elsewhere ?

Let me notify more IoT.js's upstream developers

https://github.com/Samsung/iotjs/graphs/contributors

cc: @ILyoan @hs0225 @yichoi @LaszloLango @galpeter @daeyeon @bzsolt @glistening @DanielBallaSZTE @haesik @rtakacs @#12knightburton @seanshpark @robertsipka @chokobole @chunseoklee @nova0821 @zherczeg @19kolipka @akosthekiss

Do you see any objections to update IoT.js in Tizen:RT ?

3/

Regarding tests, I know that Tizen:RT is also tested upstream, ie:
https://travis-ci.org/Samsung/iotjs/jobs/411754512

Myself I've been using it on ARTIK055s for a couple of months (using http, adc, gpio modules)
and will give more details if curious.

**Comment by sunghan-chang** [comment]
@rzr Thank you very much for your effort. But I discussed this with IoTjs dev team who is in HQ. He rejected this PR and he wants to raise an issue on IoTjs community (issue tab?). We should do public release ours and at that time we should get a test result from software engineering team. Because of that, it is difficult to update iotjs without confirmation from iotjs dev team.

**Comment by akosthekiss** [comment]
As I've been CC'd, I took a look at the commits. Except for the topmost SVACE fix, the rest seem to be TizenRT internal affairs (the update of IoT.js within TizenRT is the jurisdiction of TizenRT maintainers IMO). Moreover, the SVACE fix has landed in libtuv some hours ago, and the libtuv submodule of IoT.js has also been updated. With no downstream patches left, it seems there isn't anything left I could contribute to this PPR now.

**Comment by rzr** [comment]
thanks for feedback please hold this issue open a couple of weeks more because some of us are on vacation .

if needed i can open a ticket in iot.js tracker too and crosslink

**Comment by sunghan-chang** [comment]
@rzr I will. Thank you.

**Comment by robertsipka** [comment]
I think the topmost  `SVACE fix` commit is incorrect and not necessary. That check should be after the allocation, where it is.

**Comment by rzr** [comment]
It was merged upstream, if libtuv could be improved let me suggest to commit there then the change will land is next IoT.js import sync.

ps: I plan to update this PR on a monthly basis until merged.

**Comment by seinfra** [comment]
Target : [fc8ccc369b92a29140055444fe0716c28bc2992a] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [fc8ccc369b92a29140055444fe0716c28bc2992a] - Code Rule Check OK.

**Comment by LaszloLango** [comment]
@rzr, why is the `iotjs/deps` directory copied into the TizenRT repository? Why aren't they submodules as they are in the original repository?

**Comment by LaszloLango** [comment]
Furthermore, `deps/mbedtls` is not needed for TizenRT, because IoT.js build uses the built-in version of mbedtls. This would be an unnecessary duplication in the repository.

**Comment by rzr** [comment]
> @rzr, why is the `iotjs/deps` directory copied into the TizenRT repository? Why aren't they submodules as they are in the original repository?

I also think submodules are better in long term of software integration, but they may be a bit more difficult to patch for downstream, but this is not impossible. I think it was discussed earlier, and I aligned to existing method, but I'll be happy to replace this import patch with submodules.

Thx for the tip about deps/mbedtls, In perfect world both should use same version too.

**Comment by seinfra** [comment]
Target : [f38fe4ada673a95cda000ed4ad45803a0fb889ce] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [b343eb870c22e3cf4fb74a0fad654496f3ad339b] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [b343eb870c22e3cf4fb74a0fad654496f3ad339b] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [cf34f6cf682af5e7fb0364b383beb36b0a8dc32d] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [cf34f6cf682af5e7fb0364b383beb36b0a8dc32d] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [cf34f6cf682af5e7fb0364b383beb36b0a8dc32d] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [cf34f6cf682af5e7fb0364b383beb36b0a8dc32d] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [cf34f6cf682af5e7fb0364b383beb36b0a8dc32d] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [cf34f6cf682af5e7fb0364b383beb36b0a8dc32d] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [cf34f6cf682af5e7fb0364b383beb36b0a8dc32d] - Code Rule Check (C++) OK.

**Comment by rzr** [comment]
Is a new release of IoT.js planned anytime soon ?

**Comment by sunghan-chang** [comment]
@rzr Oh sorry for late reply. I found this now. As far as I know, no plan.

**Comment by rzr** [comment]
OK thanks for feedback, ping me if there are any interest to use updated iotjs on tizenrt, 
Or I can try to upstream this for nuttx, I've been using this for webthings-iotjs

Relate-to: https://github.com/rzr/webthing-iotjs/wiki/IotJs

**Pull request closed without merging**
