### PR TITLE
configs/imxrt1020-evk, imxrt1050-evk: Add C++ support in flat build

### PR DESCRIPTION
**Pull request by sangam-swami**
Support for C++ was not there in imxrt project.
Added configs and scripts to support helloxx

Signed-off-by: Sangamanatha <sangam.swami@samsung.com>

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [703006f4ada1f9bbccf109e57a33a4096d5aade9] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [703006f4ada1f9bbccf109e57a33a4096d5aade9] - Code Rule Check OK.

**Comment by sunghan-chang** [comment]
1. Please keep the file permissions with 644.
2. Please check the file path.
3. i.MXRT boards have no audio device. Do we need to enable C++ for them?

**Comment by seinfra** [comment]
Target : [bd223737d9102c7553fa87cff756e03449c839b6] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [bd223737d9102c7553fa87cff756e03449c839b6] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [86097ca08144a5700d822b0e18cee24640945bd9] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [86097ca08144a5700d822b0e18cee24640945bd9] - Code Rule Check OK.

**Comment by sangam-swami** [comment]
> 1. Please keep the file permissions with 644.
> 2. Please check the file path.
> 3. i.MXRT boards have no audio device. Do we need to enable C++ for them?
Hi, Please find the below updates.
1. Updated the file permissions to 644.
2. set file path properly in the comments section
3. C++ will be enabled for reference, imxrt board have capability for audio interface if needed.

**Pull request merged**
