### PR TITLE
apps/example/artik_demo/artik_demo.c 오타수정

### PR DESCRIPTION
**Pull request by leegiyun**
apps/example/artik_demo/artik_demo.c

At the end of line 242; is missing

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [688402b09af2f44f2e27bcc796ebe01ea700a631] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [688402b09af2f44f2e27bcc796ebe01ea700a631] - Code Rule Check (C++) OK.

**Comment by sunghan-chang** [comment]
@leegiyun Thank you for contribution. But we don't allow this kind of title. Could you check our commit rules through link below?
https://github.com/Samsung/TizenRT/wiki/Documentations#commit-rules

**Comment by sunghan-chang** [comment]
@leegiyun Thank you for renaming PR title. But commit title is more important than PR's. Could you modify  it as shown below?
```
git commit --amend
<modify title> + exit using ctrl + x
git push -f
```

**Pull request closed without merging**
