### PR TITLE
os/board/rtl8721csm: fix pmk cache incorrect issue when switching mode between sta/softap

### PR DESCRIPTION
**Pull request by lu04-wang**

### CODE REVIEW

**Comment by sunghan-chang** [comment]
@lu04-wang Could you let us know this PR includes another PR which is not merged?

**Comment by lu04-wang** [comment]
> @lu04-wang Could you let us know this PR includes another PR which is not merged?

@sunghan-chang No, there is only one PR is included.

**Review by j11591 — APPROVED** [review]
LGTM

**Review by jsdosa — APPROVED** [review]
looks nice to me.

**Review by jeongchanKim — APPROVED** [review]
LGTM

**Pull request merged**
