### PR TITLE
os/board/rtl8721csm: print log for wlan EAPOL process

### PR DESCRIPTION
**Pull request by gexuyan**
EAPOL process will print following logs:
For STA mode:
- RX message 1 of 4-Way Handshake from xx:xx:xx:xx:xx:xx
- Sending EAPOL-Key 2/4
- RX message 3 of 4-Way Handshake from xx:xx:xx:xx:xx:xx
- Sending EAPOL-Key 4/4
- (if EAPOL timeout) timeout - didn't receive EAPOL message 7000ms

For SoftAP mode:
- STA xx:xx:xx:xx:xx:xx - sending 1/4 msg of 4-Way Handshake
- STA xx:xx:xx:xx:xx:xx - received EAPOL-Key frame (2/4 Pairwise)
- STA xx:xx:xx:xx:xx:xx - sending 3/4 msg of 4-Way Handshake
- STA xx:xx:xx:xx:xx:xx - received EAPOL-Key frame (4/4 Pairwise)
- (if EAPOL timeout) timeout - didn't receive EAPOL message 7000ms

### CODE REVIEW

**Comment by gexuyan** [comment]
> Is the print log inbuilt in the binary files ?

Yes it it

**Review by pillip8282 — COMMENTED** [review]
How about to add commit description? for example what information, how frequently, log examples.

**Comment by gexuyan** [comment]
> How about to add commit description? for example what information, how frequently, log examples.

Sure no problem, log examples have been added in the commit description.

**Comment by j11591** [comment]
Looks good to me.

**Review by pillip8282 — APPROVED** [review]
lgtm

**Comment by pillip8282** [comment]
Can you re submit the PR to run CI server. I can't merge it because it didn't run in CI server. you can simply run CI server by changing commit title and push it.

**Comment by sunghan-chang** [comment]
@gexuyan You should not use `git pull` to rebase.  Please follow steps as below
```sh
$ git reset --hard HEAD^
$ git fetch upstream
$ git rebase upstream/master
(if no error)
$ git push -f
```

**Comment by gexuyan** [comment]
Dear all, since this branch already been very messy. I will open a new pull request for this issue. Thank you.

**Pull request closed without merging**
