### PR TITLE
[UnderVerification] os/board/rtl8730e: Modify I2S Pin

### PR DESCRIPTION
**Pull request by ZhenBei-Sin**
build/configs/rtl8730e: Enable CONFIG_GPIO by default

os/board/rtl8730e: Modify I2S Pin
Change Notes:
- Configure the I2S BCLK pin for both normal and sleep modes with Pull Down initialization.
- Configure the I2S BCLK pin to operate as a GPIO input pin when enter sleep mode.
- Configure the PA23 pin for normal mode with Pull Down initialization.

### CODE REVIEW

**Comment by sunghan-chang** [comment]
@abhishek-samsung Is this verified?

**Comment by ZhenBei-Sin** [comment]
> @abhishek-samsung Is this verified?

Hi @abhishek-samsung
Could you please clarify if the requirement for using I2S for the audio feature is still necessary?
Have you completed any verification on your end?
If the changes have been verified and confirmed, I will proceed with rebasing and resolving any conflicts.

Thank You.

**Comment by abhishek-samsung** [comment]
> > @abhishek-samsung Is this verified?
> 
> Hi @abhishek-samsung Could you please clarify if the requirement for using I2S for the audio feature is still necessary? Have you completed any verification on your end? If the changes have been verified and confirmed, I will proceed with rebasing and resolving any conflicts.
> 
> Thank You.

Hello @ZhenBei-Sin , thanks for the PR. Sorry for the delayed reply. We have taken the changes from the PR and applied it internally. Its working well. We are plannig to change the placement of the code that puts BCLK to tristate mode (this is because NDP needs to control the BCLK pin itself for smoother transition into sleep). So, this PR can be closed. We will make the changes on our end based on this PR.

**Comment by ZhenBei-Sin** [comment]
> > > @abhishek-samsung Is this verified?
> > 
> > 
> > Hi @abhishek-samsung Could you please clarify if the requirement for using I2S for the audio feature is still necessary? Have you completed any verification on your end? If the changes have been verified and confirmed, I will proceed with rebasing and resolving any conflicts.
> > Thank You.
> 
> Hello @ZhenBei-Sin , thanks for the PR. Sorry for the delayed reply. We have taken the changes from the PR and applied it internally. Its working well. We are plannig to change the placement of the code that puts BCLK to tristate mode (this is because NDP needs to control the BCLK pin itself for smoother transition into sleep). So, this PR can be closed. We will make the changes on our end based on this PR.

Thank you for informing me. I'll proceed with closing this PR.

**Pull request closed without merging**
