### PR TITLE
configs/artik055s/audio : disable manual testcase and enable Audio ITC

### PR DESCRIPTION
**Pull request by samegautam**
change flags:
CONFIG_DISABLE_MANUAL_TESTCASE : to disable manual testcase
CONFIG_EXAMPLES_TESTCASE_AUDIO_ITC : enabled audio testcase execution

Signed-off-by: Sameer Gautam <sameer.g1@samsung.com>

### CODE REVIEW

**Comment by samegautam** [comment]
@Taejun-Kwon @sunghan-chang : please review

**Comment by seinfra** [comment]
Target : [d6a3344453d32a0010df2abb576e7063f2a2a5a7] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [d6a3344453d32a0010df2abb576e7063f2a2a5a7] - Code Rule Check OK.

**Comment by samegautam** [comment]
@yc207-lee : please review

**Pull request merged**
