### PR TITLE
Revert "testcase/filesystem: Fix fs readdir() tc failure"

### PR DESCRIPTION
**Pull request by lokeshbv**
This reverts commit 025cd752928a44adb72ad093ce0c65a7e1bfd6e2.

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [f87f9ca01c13c2367c94f70750b51b8217eb1ac0] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [f87f9ca01c13c2367c94f70750b51b8217eb1ac0] - Code Rule Check OK.

**Comment by sunghan-chang** [comment]
@lokeshbv Could you write the reason of this PR? Why do you revert it?

**Comment by seinfra** [comment]
Target : [7a9af3b66372a2b26cc5dd86b4fb74ed9485c985] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [7a9af3b66372a2b26cc5dd86b4fb74ed9485c985] - Code Rule Check (C++) OK.

**Pull request merged**
