### PR TITLE
apps/slsiwifi: Use sleep() instead of up_mdelay() 

### PR DESCRIPTION
**Pull request by SeonghoByeon**
- Remove kernel API, up_mdelay() call in slsiwifi example application
- Modify up_mdelay(3000) to sleep(3)

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [9c55073cd7508cdf0291c19aeef7a18e4bb0c85e] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [9c55073cd7508cdf0291c19aeef7a18e4bb0c85e] - Code Rule Check OK.

**Comment by SeonghoByeon** [comment]
@sunghan-chang That is a good proposal. Thanks for the comment!

**Comment by seinfra** [comment]
Target : [e927ba7598af709339505d4eafc6e516f53232c1] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [e927ba7598af709339505d4eafc6e516f53232c1] - Code Rule Check (C++) OK.

**Pull request merged**
