### PR TITLE
Fix memory leak and Resource Usage Optimization

### PR DESCRIPTION
**Pull request by samirsahu1947**
Fix memory leak for External IoTjs echo_server

### CODE REVIEW

**Comment by sunghan-chang** [comment]
@samirsahu1947 IoT.js is managed by another github project. For code maintain, you had better make a issue on there as they do.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by samirsahu1947** [comment]
@haesik Can you please review the change ?

**Comment by haesik** [comment]
Echo_server is just a test code for libtuv, not platform code.. and the part you are talking about is an error situation.  I think It does not seem to have to be patched..

**Pull request closed without merging**
