### PR TITLE
framework/st_things: Arrange st_things's folder structure

### PR DESCRIPTION
**Pull request by heejin-kim**
Arrange and rename the framework/st_things files.
Also to avoid errors that can occur while building, arranged CFLAGS in Make.defs.

### CODE REVIEW

**Comment by heejin-kim** [comment]
Because of VM ware error, I can not amend the original commit (PR 1164). 
So I commit again as a new PR, please understand that.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Pull request merged**
