### PR TITLE
Doxygen: move description files

### PR DESCRIPTION
**Pull request by KimDongEon**
The file for the description does not need to be separate from the actual header file. Therefore, correction is made.

### CODE REVIEW

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by sunghan-chang** [comment]
@KimDongEon Don't use full path on commit title.
external/mbedtls and external/iotjs are enough.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by KimDongEon** [comment]
Fix the commit title.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Pull request merged**
