### PR TITLE
os/board/rtl8721csm: fix a typo, UDPATE, in MTU update callback structure name

### PR DESCRIPTION
**Pull request by yeetee179**

### CODE REVIEW

**Comment by sunghan-chang** [comment]
@yeetee179 This is a fix of UPDATE typo. But there are many other typos,
1. lenth -> length
```
os/board/rtl8721csm/src/component/common/api/wifi/wifi_conf.h
os/board/rtl8721csm/src/component/soc/realtek/amebad/app/monitor/ram/monitor_hp.c
os/board/rtl8721csm/src/component/soc/realtek/amebad/app/monitor/ram/monitor_lp.c
os/board/rtl8721csm/src/component/soc/realtek/amebad/app/monitor/rom/monitor_rom.c
os/drivers/wireless/realtek/wifi_util_interface/wifi_conf.h
```
2. successed -> succeeded
```
os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/inc/os_mem.h
```
3. ouput -> output
```
os/board/rtl8721csm/src/component/soc/realtek/amebad/fwlib/include/rtl8721d_tim.h
```

**Comment by yeetee179** [comment]
> @yeetee179 This is a fix of UPDATE typo. But there are many other typos,
> 
> 1. lenth -> length
> 
> ```
> os/board/rtl8721csm/src/component/common/api/wifi/wifi_conf.h
> os/board/rtl8721csm/src/component/soc/realtek/amebad/app/monitor/ram/monitor_hp.c
> os/board/rtl8721csm/src/component/soc/realtek/amebad/app/monitor/ram/monitor_lp.c
> os/board/rtl8721csm/src/component/soc/realtek/amebad/app/monitor/rom/monitor_rom.c
> os/drivers/wireless/realtek/wifi_util_interface/wifi_conf.h
> ```
> 
> 2. successed -> succeeded
> 
> ```
> os/board/rtl8721csm/src/component/common/bluetooth/realtek/sdk/inc/os_mem.h
> ```
> 
> 3. ouput -> output
> 
> ```
> os/board/rtl8721csm/src/component/soc/realtek/amebad/fwlib/include/rtl8721d_tim.h
> ```

maybe we can merge this commit first, for the changes above we will fix them in the next commit

**Comment by sunghan-chang** [comment]
> maybe we can merge this commit first, for the changes above we will fix them in the next commit

Yes, I agree.

**Review by sunghan-chang — APPROVED** [review]

**Review by ydlee-sec — APPROVED** [review]
LGTM~

**Pull request merged**
