### PR TITLE
build/tools/amebad/bootloader/ : Add Version information print

### PR DESCRIPTION
**Pull request by fengyunlai**
Add git version info print in km0 boot, km0 image2, km4 boot, to sync with Realtek Git.

### CODE REVIEW

**Review by thapav — APPROVED** [review]
LGTM

**Comment by sunghan-chang** [comment]
Could you add logs you added in the commit description?

**Comment by fengyunlai** [comment]
> Could you add logs you added in the commit description?

Hi Mr Chang, I have reupload bins and add description in commit message. Thanks

**Review by abhishek-samsung — COMMENTED** [review]
Please change "compule time" -> "compile time" in the commit message.

**Comment by fengyunlai** [comment]
> Please change "compule time" -> "compile time" in the commit message.

Thanks for reminder, the typo has been corrected.

**Review by jeongchanKim — APPROVED** [review]
LGTM

**Comment by sunghan-chang** [comment]
@fengyunlai I sent a mail to Eric. The sentence "bootloader_version" should be fixed. Could you talk with Eric?

**Comment by fengyunlai** [comment]
> @fengyunlai I sent a mail to Eric. The sentence "bootloader_version" should be fixed. Could you talk with Eric?

Noted Mr Chang, and I just fixed it accordingly. Thanks~

**Comment by sunghan-chang** [comment]
@fengyunlai `e.g."bootloader_version km0_bootloader_ver_425efc0ccec91b05a3b6c0189020296beb3931fd_2021/08/17-10:36:29"` looks toooo long. It will take more time to print and will affect booting time longer. How about reducing logs like below?
```
bootloader_version km0_425efc0_20210817
```
First 7 chars are enough to distinguish the commit.

**Comment by fengyunlai** [comment]
> @fengyunlai `e.g."bootloader_version km0_bootloader_ver_425efc0ccec91b05a3b6c0189020296beb3931fd_2021/08/17-10:36:29"` looks toooo long. It will take more time to print and will affect booting time longer. How about reducing logs like below?
> 
> ```
> bootloader_version km0_425efc0_20210817
> ```
> 
> First 7 chars are enough to distinguish the commit.

Hi Mr Chang. I understand your consideration. But may I suggest we keep the message format? Because actually the message is synchronized with our Git server and other projects' format also. That's why it took me some time for this feature. One advantage is that, in future bootloader update,  we can avoid persons forget to update the message. The booting time affect I  think is very very minor.

**Comment by sunghan-chang** [comment]
@fengyunlai Could you check elapsed time with / without the logs?

**Comment by fengyunlai** [comment]
> @fengyunlai Could you check elapsed time with / without the logs?

Mr Chang, with logs  (3 messages together) added, the time taken is 0.03 s more.

**Review by jeongchanKim — APPROVED** [review]
LGTM

**Review by sunghan-chang — APPROVED** [review]

**Comment by sunghan-chang** [comment]
@fengyunlai Could you send me another bootloader which is increased kernel partition?

**Pull request merged**
