### PR TITLE
os/board/rtl8721csm/src/libs: adding wlan library 

### PR DESCRIPTION
**Pull request by prashantrar**
Adding the wlan library for RTL8721CSM to support wifi operations.

 os/board/rtl8721csm/src/libs/lib_wlan.a

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [7e4130c69fd125af167d2e86f6e0bbd0f86d3894] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [7e4130c69fd125af167d2e86f6e0bbd0f86d3894] - Code Rule Check OK.

**Comment by sunghan-chang** [comment]
@prashantrar It is difficult to know for what because we support other boards. Could you write that it is for realtek board like `board/rtl8721csm: add wlan library`?

**Comment by sunghan-chang** [comment]
@prashantrar Because this is the open source, we think that history is important.

**Comment by prashantrar** [comment]
> 
> 
> @prashantrar Because this is the open source, we think that history is important.

@sunghan-chang I have changed the title accordingly.

**Comment by sunghan-chang** [comment]
@prashantrar PR title is not used for history. Could you change the commit title? And there are three boards name in the PR title. Could you do that once because PR title is too long for commit title?

**Comment by sunghan-chang** [comment]
1. [Realtek][RTL8721CSM] add wlan library
2. add wlan library for Realtek AmebaD board RTL8721CSM
3. board/rtl8721csm: add wlan library

**Comment by seinfra** [comment]
Target : [682d0f53e559689311cf5bdf8306cbf2cd0962bf] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [682d0f53e559689311cf5bdf8306cbf2cd0962bf] - Code Rule Check OK.

**Comment by prashantrar** [comment]
@sunghan-chang I have updated the PR title,. I have also amended the commit title and force pushed again. The name of the board is mentioned only once

**Pull request merged**
