### PR TITLE
tools: Add .clang-format at TizenRT dir

### PR DESCRIPTION
**Pull request by junmin-kim**
This is TizenRT style custom clang-format file
User can format cpp files using .clang-format
USAGE : clang-format -style=file -i "filename"

### CODE REVIEW

**Comment by junmin-kim** [comment]
@sunghan-chang Please review this PR

**Comment by seinfra** [comment]
Target : [40c9c27c9e150829959b84e50c8086a52e0abe25] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [40c9c27c9e150829959b84e50c8086a52e0abe25] - Code Rule Check (C++) OK.

**Comment by junmin-kim** [comment]
@sunghan-chang It needs clang-format

**Comment by sunghan-chang** [comment]
@junmin-kim Could you move this to os/tools? Because formater for C is there.

**Pull request merged**
