### PR TITLE
configs/imxrt1050-evk,imxrt1020-evk: enable CONFIG_OPTIMIZE_APP_RELOAD_TIME by default

### PR DESCRIPTION
**Pull request by sangam-swami**
There are differnces in flags of defconfig and .config
Update defconfig with .config changes after make menuconfig.

Signed-off-by: Sangamanatha <sangam.swami@samsung.com>

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [b099044ec44a951517ab0bc34af5e4a160bff962] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [b099044ec44a951517ab0bc34af5e4a160bff962] - Code Rule Check OK.

**Comment by sunghan-chang** [comment]
@sangam-swami Is this necessary?

**Comment by sangam-swami** [comment]
> @sangam-swami Is this necessary?
If we don't change defconfig, then few of the flags(CONFIG_OPTIMIZE_APP_RELOAD_TIME etc)  are not set by default, need to do run make menuconfig.

**Comment by sunghan-chang** [comment]
@sangam-swami So, main purpose of this PR is enabling CONFIG_OPTIMIZE_APP_RELOAD_TIME. Except this, nothing is valid. Then,
1. Could you update another defconfigs like 1020-evk/loadable?
2. Please rewrite the commit title with exact purpose. To know what it is, I should open the commit. I can't know what modification is with title.
e.g
```
configs/imxrt1050-evk: enable CONFIG_OPTIMIZE_APP_RELOAD_TIME by default
```

**Comment by sangam-swami** [comment]
> @sangam-swami So, main purpose of this PR is enabling CONFIG_OPTIMIZE_APP_RELOAD_TIME. Except this, nothing is valid. Then,
> 
> 1. Could you update another defconfigs like 1020-evk/loadable?
> 2. Please rewrite the commit title with exact purpose. To know what it is, I should open the commit. I can't know what modification is with title.
>    e.g
> 
> ```
> configs/imxrt1050-evk: enable CONFIG_OPTIMIZE_APP_RELOAD_TIME by default
> ```

There were 3 flags which are changed after running make menuconfig command.
CONFIG_ARCH_HAVE_TICKLESS,CONFIG_EXAMPLES_BINARY_UPDATE, CONFIG_OPTIMIZE_APP_RELOAD_TIME
CONFIG_ARCH_HAVE_TICKLESS -> all imxrt defconfig have same settings, so I won't be modiying
CONFIG_EXAMPLES_BINARY_UPDATE -> not used anywhere so removed from related defconfig
CONFIG_OPTIMIZE_APP_RELOAD_TIME -> updated in related defconfigs

> 1. Could you update another defconfigs like 1020-evk/loadable? 
Yes updated SAM defconfig
> 2. Please rewrite the commit title with exact purpose
changed the commit message

**Pull request merged**
