### PR TITLE
Refactor MPU API for app separation

### PR DESCRIPTION
**Pull request by kishore-sn**
Change the mpu_user_intsram_context() to mpu_user_extsram_context().
Add new Config to determine the MPU region SHAREABLE settings for app regions.

Signed-off-by: Kishore SN <kishore.sn@samsung.com>

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [3250db743297f7a1e7be64267c3a7d7d530eacb1] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [3250db743297f7a1e7be64267c3a7d7d530eacb1] - Code Rule Check OK.

**Comment by sunghan-chang** [comment]
@kishore-sn refractor -> refactor

**Comment by seinfra** [comment]
Target : [9781c7ff669eb4861d7b16127be2f659a7c03c6f] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [9781c7ff669eb4861d7b16127be2f659a7c03c6f] - Code Rule Check OK.

**Pull request merged**
