### PR TITLE
testcase/filesystem: Add functions description and Fix functions name

### PR DESCRIPTION
**Pull request by KimDongEon**
1. Add some functions description
2. Some functions have been rename to their correct meanings

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [8fae858a5dca915727db994a1ace33075741eea5] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [8fae858a5dca915727db994a1ace33075741eea5] - Code Rule Check (C++) OK.

**Comment by sunghan-chang** [comment]
@KimDongEon Please find my comments.
1. Let's say `testcase/filesystem: add function description` 
2. Please split the different topics. 
    1. add function description
    2. fix or modify or change the function name to do something

**Comment by seinfra** [comment]
Target : [349f3522d74bccaddbefb7fff540e5a0cc3bea21] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [349f3522d74bccaddbefb7fff540e5a0cc3bea21] - Code Rule Check OK.

**Comment by KimDongEon** [comment]
@sunghan-chang 
I reflected your opinion.

**Comment by seinfra** [comment]
Target : [0feaa1d4f21c1745acfd66239cd476c9925738e6] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [0feaa1d4f21c1745acfd66239cd476c9925738e6] - Code Rule Check OK.

**Pull request merged**
