### PR TITLE
Protection

### PR DESCRIPTION
**Pull request by btheosam**

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [a8745f2c8df1d0f0a6bef75132c433f84ff48cd0] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [a8745f2c8df1d0f0a6bef75132c433f84ff48cd0] - Code Rule Check (C++) OK.

**Comment by sunghan-chang** [comment]
@btheosam Please follow our commit rules.
It is in our wiki.

**Comment by sunghan-chang** [comment]
https://github.com/Samsung/TizenRT/wiki/Documentations#commit-rules

**Comment by btheosam** [comment]
> @btheosam Please follow our commit rules.
> It is in our wiki.
Fixed.

**Comment by btheosam** [comment]
@sunghan-chang Fixed.

**Comment by seinfra** [comment]
Target : [a0cd87084912c18d96ec58b461edee54c5356d06] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [a0cd87084912c18d96ec58b461edee54c5356d06] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [a0cd87084912c18d96ec58b461edee54c5356d06] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [a0cd87084912c18d96ec58b461edee54c5356d06] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [a0cd87084912c18d96ec58b461edee54c5356d06] - Code Rule Check (C++) OK.

**Comment by btheosam** [comment]
Parallel commit with app loadable-elf voids this.

**Pull request closed without merging**
