### PR TITLE
board/rtl8720e/wifi : Add assoc and disassoc handler when starting SoftAP

### PR DESCRIPTION
**Pull request by jwei5**
Add association and disassociation handler event for SoftAP

### CODE REVIEW

**Comment by sunghan-chang** [comment]
@jwei5 Could you rewrite the commit title like below?
```
board/rtl8720e/wifi : Add assoc and disassoc handler when starting SoftAP

Some description for what it is and why this is necessary
```

**Comment by sunghan-chang** [comment]
@jwei5 Could you do it with the commit? not the pr.

**Comment by sunghan-chang** [comment]
@jwei5 You modified the pr only. But it's necessary on the commit for the history.

**Comment by jwei5** [comment]
@sunghan-chang Understood, I will correct this

**Comment by sunghan-chang** [comment]
@jwei5 You can do it like below
```sh
$ git commit --amend
modify the commit and exit
$ git push -f
```

**Review by sunghan-chang — APPROVED** [review]

**Comment by sunghan-chang** [comment]
@j11591 Could you review and merge this?

**Comment by j11591** [comment]
> @j11591 Could you review and merge this?

I will merge it after testing

**Pull request merged**
