### PR TITLE
fs/tmpfs: Fix tmpfs_ioctl() logic

### PR DESCRIPTION
**Pull request by lokeshbv**
Fixes the logic in tmpfs_ioctl() that extracts the priv state structure from the file system structures.
It was not getting the right value and causing mmap() to fail.

This patch is back-ported from Nuttx.

Signed-off-by: Lokesh B V <lokesh.bv@partner.samsung.com>

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [ec64bf7001071f91569a75d6f171046c28970b82] - Code Rule Check Result:
os/fs/tmpfs/fs_tmpfs.c:91: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:91: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:93: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:93: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:95: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:95: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:97: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:97: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:111: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:111: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:113: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:113: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:117: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:117: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:119: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:119: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:121: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:121: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:124: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:124: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:127: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:127: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:129: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:129: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:130: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:130: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:132: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:132: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:133: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:133: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:134: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:134: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:136: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:136: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:137: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:137: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:138: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:138: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:140: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:140: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:142: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:142: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:144: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:144: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:149: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:149: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:152: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:152: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:154: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:154: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:161: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:161: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:163: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:163: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:165: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:165: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:167: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:167: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:169: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:169: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:174: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:174: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:177: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:177: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:179: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:179: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:181: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:181: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:319: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:319: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:376: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:376: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:483: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:483: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:504: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:504: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:553: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:553: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:554: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:554: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:635: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:635: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:636: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:636: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:780: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:780: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:781: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:781: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:836: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:889: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:889: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:890: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:890: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:891: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:891: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:1014: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:1014: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:1015: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:1015: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:1016: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:1016: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:1058: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:1058: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:1059: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:1059: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:1060: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:1060: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:1099: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:1099: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:1128: ERROR: [BRC_M_SMT] else should follow close brace '}'
os/fs/tmpfs/fs_tmpfs.c:1153: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:1153: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:1219: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:1219: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:1285: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:1285: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:1469: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:1469: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:1497: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:1515: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:1515: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:1590: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:1595: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:1729: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:1729: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:1777: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:1777: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:1802: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:1802: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:1869: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:1869: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:1885: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:1885: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:2127: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:2127: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:2245: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:2245: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:2314: ERROR: [SPC_M_SEP] space prohibited before that close parenthesis ')'
os/fs/tmpfs/fs_tmpfs.c:2373: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:2373: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:2418: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:2418: ERROR: [IDT_M_TAB] please, no spaces at the start of a line

**Comment by seinfra** [comment]
Target : [ec64bf7001071f91569a75d6f171046c28970b82] - Code Rule Check (C++) OK.

**Comment by sunghan-chang** [comment]
Thank you for this change. Regardless of this commit, could you apply coding rules to this file?

**Comment by seinfra** [comment]
Target : [3bcdd4ddd4987b2d0f99891cf73bedc12b5c5906] - Code Rule Check Result:
os/fs/tmpfs/fs_tmpfs.c:91: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:91: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:93: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:93: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:95: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:95: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/fs/tmpfs/fs_tmpfs.c:97: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/fs/tmpfs/fs_tmpfs.c:97: ERROR: [IDT_M_TAB] please, no spaces at the start of a line

**Comment by seinfra** [comment]
Target : [3bcdd4ddd4987b2d0f99891cf73bedc12b5c5906] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [dfddfb33303f97679b8ceccdf399674b4edbf03d] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [dfddfb33303f97679b8ceccdf399674b4edbf03d] - Code Rule Check Result:
os/fs/tmpfs/fs_tmpfs.c:2313: ERROR: [SPC_M_SEP] space prohibited before that close parenthesis ')'

**Comment by seinfra** [comment]
Target : [61698aae537be3f2ffe0052a349f4a6df1f5840f] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [61698aae537be3f2ffe0052a349f4a6df1f5840f] - Code Rule Check OK.

**Pull request merged**
