### PR TITLE
framework/media: modify the folder name of codecs

### PR DESCRIPTION
**Pull request by jiawei-xiang**
1. change folder name: "streaming" to "codec"
2. change folder name: "codecs" to "codec/opus_api"

@Taejun-Kwon @junmin-kim

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [a52c658028d8d0e34fc2b9d539ca9eaa60357786] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [a52c658028d8d0e34fc2b9d539ca9eaa60357786] - Code Rule Check Result:
framework/src/media/Decoder.h:39: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:VxO)
framework/src/media/Decoder.h:39: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:OxV)
framework/src/media/Decoder.h:39: ERROR: [SPC_M_OPR] spaces required around that '<' (ctx:VxV)
framework/src/media/Decoder.h:39: ERROR: [SPC_M_OPR] spaces required around that '>' (ctx:VxW)
framework/src/media/codec_wrapper/opus_api/opus_decoder_api.c:69: ERROR: [IDT_M_TAB] code indent should use tabs where possible
framework/src/media/codec_wrapper/opus_api/opus_decoder_api.c:69: ERROR: [IDT_M_TAB] please, no space before tabs
framework/src/media/codec_wrapper/opus_api/opus_decoder_api.c:69: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
framework/src/media/codec_wrapper/opus_api/opus_decoder_api.c:70: ERROR: [IDT_M_TAB] code indent should use tabs where possible
framework/src/media/codec_wrapper/opus_api/opus_decoder_api.c:70: ERROR: [IDT_M_TAB] please, no space before tabs
framework/src/media/codec_wrapper/opus_api/opus_decoder_api.c:70: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
framework/src/media/codec_wrapper/opus_api/opus_decoder_api.c:71: ERROR: [IDT_M_TAB] code indent should use tabs where possible
framework/src/media/codec_wrapper/opus_api/opus_decoder_api.c:71: ERROR: [IDT_M_TAB] please, no space before tabs
framework/src/media/codec_wrapper/opus_api/opus_decoder_api.c:71: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
framework/src/media/codec_wrapper/opus_api/opus_decoder_api.c:72: ERROR: [IDT_M_TAB] code indent should use tabs where possible
framework/src/media/codec_wrapper/opus_api/opus_decoder_api.c:72: ERROR: [IDT_M_TAB] please, no space before tabs
framework/src/media/codec_wrapper/opus_api/opus_decoder_api.c:72: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
framework/src/media/codec_wrapper/opus_api/opus_decoder_api.c:73: ERROR: [IDT_M_TAB] code indent should use tabs where possible
framework/src/media/codec_wrapper/opus_api/opus_decoder_api.c:73: ERROR: [IDT_M_TAB] please, no space before tabs
framework/src/media/codec_wrapper/opus_api/opus_decoder_api.c:73: ERROR: [IDT_M_TAB] please, no spaces at the start of a line

**Comment by seinfra** [comment]
Target : [1a96d8a08f42769af13263c767c6511cd0cf2c0f] -

**Comment by jiawei-xiang** [comment]
@Taejun-Kwon Thanks for your suggestion,  I fixed it.

**Comment by seinfra** [comment]
Target : [c0aced44740d595b54da03c5b96295c4654a05c2] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [c0aced44740d595b54da03c5b96295c4654a05c2] - Code Rule Check Result:
framework/src/media/Decoder.h:39: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:VxO)
framework/src/media/Decoder.h:39: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:OxV)
framework/src/media/Decoder.h:39: ERROR: [SPC_M_OPR] spaces required around that '<' (ctx:VxV)
framework/src/media/Decoder.h:39: ERROR: [SPC_M_OPR] spaces required around that '>' (ctx:VxW)
framework/src/media/codec/opus_api/opus_decoder_api.c:69: ERROR: [IDT_M_TAB] code indent should use tabs where possible
framework/src/media/codec/opus_api/opus_decoder_api.c:69: ERROR: [IDT_M_TAB] please, no space before tabs
framework/src/media/codec/opus_api/opus_decoder_api.c:69: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
framework/src/media/codec/opus_api/opus_decoder_api.c:70: ERROR: [IDT_M_TAB] code indent should use tabs where possible
framework/src/media/codec/opus_api/opus_decoder_api.c:70: ERROR: [IDT_M_TAB] please, no space before tabs
framework/src/media/codec/opus_api/opus_decoder_api.c:70: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
framework/src/media/codec/opus_api/opus_decoder_api.c:71: ERROR: [IDT_M_TAB] code indent should use tabs where possible
framework/src/media/codec/opus_api/opus_decoder_api.c:71: ERROR: [IDT_M_TAB] please, no space before tabs
framework/src/media/codec/opus_api/opus_decoder_api.c:71: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
framework/src/media/codec/opus_api/opus_decoder_api.c:72: ERROR: [IDT_M_TAB] code indent should use tabs where possible
framework/src/media/codec/opus_api/opus_decoder_api.c:72: ERROR: [IDT_M_TAB] please, no space before tabs
framework/src/media/codec/opus_api/opus_decoder_api.c:72: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
framework/src/media/codec/opus_api/opus_decoder_api.c:73: ERROR: [IDT_M_TAB] code indent should use tabs where possible
framework/src/media/codec/opus_api/opus_decoder_api.c:73: ERROR: [IDT_M_TAB] please, no space before tabs
framework/src/media/codec/opus_api/opus_decoder_api.c:73: ERROR: [IDT_M_TAB] please, no spaces at the start of a line

**Comment by Taejun-Kwon** [comment]
could you please resolve conflicts?

**Comment by zhouxinhe** [comment]
> @zhouxinhe Please provide a new PR.

I made a new PR #2880   
@jiawei-xiang Please close this one, thanks.

**Pull request closed without merging**
