### PR TITLE
os/board/rtl8721csm: Tune BT Coex Case for AP + BT Scan

### PR DESCRIPTION
**Pull request by ziyik**
Change time slot for BT Coex Case "AP + BT Scan" to 37,13,37,13 slot time

### CODE REVIEW

**Comment by an4967** [comment]
@ziyik 
Please check the build results.

**Comment by ziyik** [comment]
> @ziyik Please check the build results.

This PR is depend on [PR5325](https://github.com/Samsung/TizenRT/pull/5325).
If it is merge build error will be resolve.

**Comment by an4967** [comment]
@ziyik 
Please check the conflicts. After PR5325 merged, I think this happened

**Comment by ziyik** [comment]
> @ziyik Please check the conflicts. After PR5325 merged, I think this happened. And can you print the log of coex case for debugging?

Rebase of this PR is done.
The debug message should no be commit into master.
It is a internal use debug message.

**Pull request closed without merging**
