### PR TITLE
framework/media: Add isRecording API to check recording status

### PR DESCRIPTION
**Pull request by jsdosa**
Add API to check if it is currently recording.

Signed-off-by: jsdosa <jsdosa@gmail.com>

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [9b178bed23d0cdca80899a026c8473f01777e8ba] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [9b178bed23d0cdca80899a026c8473f01777e8ba] - Code Rule Check Result:
framework/include/media/MediaRecorder.h:189: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:VxO)
framework/include/media/MediaRecorder.h:189: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:OxV)
framework/include/media/MediaRecorder.h:189: ERROR: [SPC_M_OPR] spaces required around that '<' (ctx:VxV)
framework/include/media/MediaRecorder.h:189: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:VxO)
framework/include/media/MediaRecorder.h:189: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:OxV)
framework/include/media/MediaRecorder.h:189: ERROR: [SPC_M_OPR] spaces required around that '>' (ctx:VxW)
framework/include/media/MediaRecorder.h:200: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:VxO)
framework/include/media/MediaRecorder.h:200: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:OxV)
framework/include/media/MediaRecorder.h:200: ERROR: [SPC_M_OPR] spaces required around that '<' (ctx:VxV)
framework/include/media/MediaRecorder.h:200: ERROR: [SPC_M_OPR] spaces required around that '>' (ctx:VxW)
framework/include/media/MediaRecorder.h:208: ERROR: [IDT_M_TAB] code indent should use tabs where possible
framework/include/media/MediaRecorder.h:208: ERROR: [IDT_M_TAB] please, no space before tabs
framework/include/media/MediaRecorder.h:234: ERROR: [SPC_M_OPR] spaces required around that '==' (ctx:VxV)
framework/include/media/MediaRecorder.h:234: ERROR: [SPC_M_OPR] need consistent spacing around '&' (ctx:VxW)
framework/include/media/MediaRecorder.h:246: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:OxV)
framework/include/media/MediaRecorder.h:246: ERROR: [SPC_M_OPR] spaces required around that '<' (ctx:VxV)
framework/include/media/MediaRecorder.h:246: ERROR: [SPC_M_OPR] spaces required around that '>' (ctx:VxW)
framework/src/media/MediaRecorderImpl.h:81: ERROR: [SPC_M_OPR] spaces prohibited around that ':' (ctx:WxW)
framework/src/media/MediaRecorderImpl.h:81: ERROR: [SPC_M_OPR] spaces required around that '<' (ctx:VxV)
framework/src/media/MediaRecorderImpl.h:81: ERROR: [SPC_M_OPR] spaces required around that '>' (ctx:VxE)
framework/src/media/MediaRecorderImpl.h:84: ERROR: [SPC_M_OPR] need consistent spacing around '&' (ctx:VxW)
framework/src/media/MediaRecorderImpl.h:99: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:VxO)
framework/src/media/MediaRecorderImpl.h:99: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:OxV)
framework/src/media/MediaRecorderImpl.h:99: ERROR: [SPC_M_OPR] spaces required around that '<' (ctx:VxV)
framework/src/media/MediaRecorderImpl.h:99: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:VxO)
framework/src/media/MediaRecorderImpl.h:99: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:OxV)
framework/src/media/MediaRecorderImpl.h:99: ERROR: [SPC_M_OPR] spaces required around that '>' (ctx:VxW)
framework/src/media/MediaRecorderImpl.h:101: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:VxO)
framework/src/media/MediaRecorderImpl.h:101: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:OxV)
framework/src/media/MediaRecorderImpl.h:101: ERROR: [SPC_M_OPR] spaces required around that '<' (ctx:VxV)
framework/src/media/MediaRecorderImpl.h:101: ERROR: [SPC_M_OPR] spaces required around that '>' (ctx:VxW)
framework/src/media/MediaRecorderImpl.h:110: ERROR: [SPC_M_OPR] need consistent spacing around '&' (ctx:VxW)
framework/src/media/MediaRecorderImpl.h:111: ERROR: [SPC_M_OPR] need consistent spacing around '&' (ctx:VxW)
framework/src/media/MediaRecorderImpl.h:112: ERROR: [SPC_M_OPR] need consistent spacing around '&' (ctx:VxW)
framework/src/media/MediaRecorderImpl.h:113: ERROR: [SPC_M_OPR] need consistent spacing around '&' (ctx:VxW)
framework/src/media/MediaRecorderImpl.h:117: ERROR: [SPC_M_OPR] need consistent spacing around '&' (ctx:VxW)
framework/src/media/MediaRecorderImpl.h:118: ERROR: [SPC_M_OPR] need consistent spacing around '&' (ctx:VxW)
framework/src/media/MediaRecorderImpl.h:119: ERROR: [SPC_M_OPR] need consistent spacing around '&' (ctx:VxW)
framework/src/media/MediaRecorderImpl.h:120: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:VxO)
framework/src/media/MediaRecorderImpl.h:120: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:OxV)
framework/src/media/MediaRecorderImpl.h:120: ERROR: [SPC_M_OPR] spaces required around that '<' (ctx:VxV)
framework/src/media/MediaRecorderImpl.h:120: ERROR: [SPC_M_OPR] spaces required around that '>' (ctx:VxW)
framework/src/media/MediaRecorderImpl.h:121: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:VxO)
framework/src/media/MediaRecorderImpl.h:121: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:OxV)
framework/src/media/MediaRecorderImpl.h:121: ERROR: [SPC_M_OPR] spaces required around that '<' (ctx:VxV)
framework/src/media/MediaRecorderImpl.h:121: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:VxO)
framework/src/media/MediaRecorderImpl.h:121: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:OxV)
framework/src/media/MediaRecorderImpl.h:121: ERROR: [SPC_M_OPR] spaces required around that '>' (ctx:VxW)
framework/src/media/MediaRecorderImpl.h:121: ERROR: [SPC_M_OPR] need consistent spacing around '&' (ctx:VxW)
framework/src/media/MediaRecorderImpl.h:122: ERROR: [SPC_M_OPR] need consistent spacing around '&' (ctx:VxW)
framework/src/media/MediaRecorderImpl.h:123: ERROR: [SPC_M_OPR] need consistent spacing around '&' (ctx:VxW)
framework/src/media/MediaRecorderImpl.h:126: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:OxV)
framework/src/media/MediaRecorderImpl.h:126: ERROR: [SPC_M_OPR] spaces required around that '<' (ctx:VxV)
framework/src/media/MediaRecorderImpl.h:126: ERROR: [SPC_M_OPR] spaces required around that '>' (ctx:VxW)
framework/src/media/MediaRecorderImpl.h:127: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:OxV)
framework/src/media/MediaRecorderImpl.h:128: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:OxV)
framework/src/media/MediaRecorderImpl.h:128: ERROR: [SPC_M_OPR] spaces required around that '<' (ctx:VxV)
framework/src/media/MediaRecorderImpl.h:128: ERROR: [SPC_M_OPR] spaces required around that '>' (ctx:VxW)
framework/src/media/MediaRecorderImpl.h:130: ERROR: [SPC_M_OPR] need consistent spacing around '&' (ctx:VxW)
framework/src/media/MediaRecorderImpl.h:134: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:OxV)

**Comment by JeongJunSik** [comment]
Please correct typo title (recoding -> recording)

**Comment by jsdosa** [comment]
@JeongJunSik very thanks!

**Pull request merged**
