### PR TITLE
Add read/write APIs to testcase driver

### PR DESCRIPTION
**Pull request by kishore-sn**
Add read/write APIs to testcase driver so that UTC apps can
open /dev/testcase to pass ioctls

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [f8c51390b2884cd42d4d8e87fc75555c4b782f0d] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [f8c51390b2884cd42d4d8e87fc75555c4b782f0d] - Code Rule Check Result:
os/drivers/testcase/testcase_drv.c:93: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/drivers/testcase/testcase_drv.c:93: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
os/drivers/testcase/testcase_drv.c:98: ERROR: [IDT_M_TAB] code indent should use tabs where possible
os/drivers/testcase/testcase_drv.c:98: ERROR: [IDT_M_TAB] please, no spaces at the start of a line

**Comment by sunghan-chang** [comment]
@kishore-sn I don't think this should be merged now. When you implement function inside, I can merge it.

**Comment by kishore-sn** [comment]
@sunghan-chang 
Power team is implementing testcases for os/pm using this method. 
So they need the testcase driver.
I have raised a separate PR for this since we did not want it to be part of the Power PR.

**Comment by seinfra** [comment]
Target : [d21edb4064a7d4ebbe43b102af4fd04ecbea4b3b] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [d21edb4064a7d4ebbe43b102af4fd04ecbea4b3b] - Code Rule Check (C++) OK.

**Comment by sunghan-chang** [comment]
@kishore-sn Is it enough code to work (to use) testcase driver? return 0 and return len?

**Comment by kishore-sn** [comment]
Yes. 
We will never read or write any data /dev/testcase file. 
We will only pass ioctl to indicate which testcase is to be run. 
So, I have added dummy read / write API to allow the app to open the /dev/testcase with proper permissions like O_RDONLY.

**Comment by sunghan-chang** [comment]
@kishore-sn I am sorry, but I don't understand.
```
We will never read or write any data /dev/testcase file.
We will only pass ioctl to indicate which testcase is to be run.
```
Then, why do you need to merge this?

**Comment by kishore-sn** [comment]
Before this change, the file properties are as below:

TASH>>ls -l /dev/testcase
 crw-rw-rw-       0 /dev/testcase


After adding these API, it is changed to :

**Comment by kishore-sn** [comment]
Before this change, the file properties are as below

**Pull request merged**
