### PR TITLE
os/board/rtl8730e: Enable FTL in defconfig for hello_16m, loadable_apps_16m and loadable_apps_8m

### PR DESCRIPTION
**Pull request by yeetee179**

### CODE REVIEW

**Review by sunghan-chang — COMMENTED** [review]
Could you add it in others as well?
1. cpp_loadable_8m
2. cxxtest_8M
3. tc_8M

**Comment by yeetee179** [comment]
> Could you add it in others as well?
> 
> 1. cpp_loadable_8m
> 2. cxxtest_8M
> 3. tc_8M

I have added FTL to defconfig for these 3 as well

**Comment by sunghan-chang** [comment]
Could you change the commit title? (I don't mean the PR title)
how about below?
`configs/rtl8730e: enable CONFIG_FTL_ENABLED in all of defconfigs`

**Comment by yeetee179** [comment]
> Could you change the commit title? (I don't mean the PR title) how about below? `configs/rtl8730e: enable CONFIG_FTL_ENABLED in all of defconfigs`

I have changed the PR title as suggested

**Review by sunghan-chang — APPROVED** [review]

**Pull request merged**
