### PR TITLE
external/webserver: Fix data length miscalculation issue

### PR DESCRIPTION
**Pull request by JeonginKim**
Fix an abort Issue in WGET
with this patch, data abort at the end of file transmission is resolved.

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [7dfc7ec534c0b048b680ec2a88711cc5c0c37c97] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [7dfc7ec534c0b048b680ec2a88711cc5c0c37c97] - Code Rule Check OK.

**Comment by sunghan-chang** [comment]
@JeonginKim Our rule of writing tilte is ```location: what you modify". And needs to fill description with problem, reason and result.

**Comment by seinfra** [comment]
Target : [ec0ce66e09f714de3d47a5e8fb7ae151c837e844] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [ec0ce66e09f714de3d47a5e8fb7ae151c837e844] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [ec0ce66e09f714de3d47a5e8fb7ae151c837e844] -

**Pull request merged**
