### PR TITLE
external/esp_idf_port:remove useless file and code.

### PR DESCRIPTION
**Pull request by ChinaTizenRT**
Remove "esp_smartconfig.h" and "spi_common.h",
they are no longer needed.

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [62c32548915506e547534153696f04029f83df1e] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [62c32548915506e547534153696f04029f83df1e] - Code Rule Check OK.

**Comment by sunghan-chang** [comment]
Hello. You don't need to make a PR per a commit. When we merge a PR, it makes additional commit like "Merge pull request #xxx from xxx".
Actually I don't want it because it does not give any information or advantage.
So, when you want to push several commit at once, let's include them in a PR.
(But when they are simple like as of now. If they are huge, it makes difficult to review.)

**Comment by ChinaTizenRT** [comment]
got it, i will combine them in one PR,

**Comment by ChinaTizenRT** [comment]
close this PR, merged it to https://github.com/Samsung/TizenRT/pull/3778.

**Pull request closed without merging**
