### PR TITLE
build/tools: Remove erase entire flash command.

### PR DESCRIPTION
**Pull request by ChinaTizenRT**
Remove erase entire flash command before downloading all images,
as it will take side effect for applications involves SPIRAM.

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [2e703c9c2118ff286ad72775e5a2bf8074f9a3aa] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [2e703c9c2118ff286ad72775e5a2bf8074f9a3aa] - Code Rule Check OK.

**Comment by sunghan-chang** [comment]
@ChinaTizenRT I can't find where you modify. Let's write `build/tools/esp32`.
And as I remember, you added that recently. Could you let me know what side effect is?

**Comment by ChinaTizenRT** [comment]
yes,  it is added recently. that time we met a strange issue,  that is 
romfs is mounted sucessfully, there is setting files in it but smart things application
 can not read it. so we erase all chip, this issue is fixed, so request to merge.

after a period, we found that system can not boot if add "erase all",
but if removing it when downling image, the system boots okay, 
so I think it will take some side effect, and not very sure  why it leads boot fail.

I will continue to check it.



but after merge it, i found that

**Comment by sunghan-chang** [comment]
@ChinaTizenRT Could you let me know whether I merge this now or not? Do you find the root cause of boot failure?

**Comment by ChinaTizenRT** [comment]
this PR should be merged,  as the second bootloader also resides in the flash,
if erasing entire all chipset, the second bootloader will be damaged.

Currently we can not reproduce the issue that romfs can not access, 
but that is another issue,  currently it needs to roll back.

Regarding the root cause of boot failure, we are asking espressif.

**Comment by sunghan-chang** [comment]
@ChinaTizenRT Ok. then could you check my first comment?
```
@ChinaTizenRT I can't find where you modify. Let's write build/tools/esp32.
```

**Comment by ChinaTizenRT** [comment]
Let's write build/tools/esp32.
  -- done.

**Comment by seinfra** [comment]
Target : [7298f66c68194de7928d90a09e3390d5a3cb9087] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [7298f66c68194de7928d90a09e3390d5a3cb9087] - Code Rule Check (C++) OK.

**Pull request merged**
