### PR TITLE
build/configs/rtl8721csm/: Extend kernel size from 1792 to 2304

### PR DESCRIPTION
**Pull request by fengyunlai**
For BLE app usage, extend kernel size from 1792 to 2304, change bootloader and defconfig.

### CODE REVIEW

**Comment by jeongchanKim** [comment]
Did you test with loadable config?

**Comment by fengyunlai** [comment]
> Did you test with loadable config?

No I didn't, but since I took 512*2 = 1024 KB flash size, I drop 3904 to 2880 to not surpass the flash size.

**Review by deepaksrma — COMMENTED** [review]
could you mention the reason of increasing the kernel size in the commit msg?

**Comment by fengyunlai** [comment]
> could you mention the reason of increasing the kernel size in the commit msg?

Sure, I just mentioned it as for BLE app usage

**Comment by sunghan-chang** [comment]
Because we merged PR #4947 , this PR is unnecessary. Let's close.

**Pull request closed without merging**
