### PR TITLE
apps/examples/smart/smart_main.c : fix a typo error

### PR DESCRIPTION
**Pull request by BONGJJUICE**
fileimage -> file image

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [6baf1e5ed3b3c9d5a711608e4eb7b87a9eda2193] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [6baf1e5ed3b3c9d5a711608e4eb7b87a9eda2193] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [a7714fac2fc1897a26f7be92b4f36c59bb70316c] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [a7714fac2fc1897a26f7be92b4f36c59bb70316c] - Code Rule Check OK.

**Comment by davidfather** [comment]
Would you please re-commit this PR on 'typo_codingrule' branch instead?
In addition, before making your PRs, you need to prepare your own forked repo.
Please, refer to our contribution rules.

**Pull request closed without merging**
