### PR TITLE
apps/testcase/DM : DM ITC rename

### PR DESCRIPTION
**Pull request by arvinmittal**
apps/examples/testcase/ta_tc/device_management/itc : DM ITC rename

Rename of scenario ITCs of DM
TC Naming rule is <TC_Category>_<Module>_<FunctionName>_<Positive/Negative>_<AdditionalInformation>
Current TC name do not have above naming convention

Signed-off-by: Arvin Mittal <arvin.mittal@samsung.com>

### CODE REVIEW

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by sunghan-chang** [comment]
1. Please don't write "description:" in commit message. Content from third line is definitely a description. 
2. Please write why do you raise this commit at description.
```
apps/testcase/DM : DM ITC rename

Naming rule is blah blah. But currently it isn't.

Signed-off-by: Arvin Mittal <arvin.mittal@samsung.com>
```

**Comment by seinfra** [comment]
Code Rule Check OK.

**Pull request merged**
