### PR TITLE
pthread: refactoring pthread APIs to fit POSIX standard

### PR DESCRIPTION
**Pull request by sunghan-chang**
1. register pthread_mutex_consistent as a SYSCALL API
2. move location of prototypes of pthread_kill and pthread_sigmask to signal.h as POSIX says

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [076eb49ba7b0613a0faafbb03a3770a62edc4ca3] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [076eb49ba7b0613a0faafbb03a3770a62edc4ca3] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [5848c172d9013889df2fcafc2a662d9f65591a38] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [5848c172d9013889df2fcafc2a662d9f65591a38] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [ca440beb215b838c8762b9081405b6e705b7f1a8] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [ca440beb215b838c8762b9081405b6e705b7f1a8] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [16b2ea5c1cdc8d7dbe91eb4c15c662238d96294b] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [16b2ea5c1cdc8d7dbe91eb4c15c662238d96294b] - Code Rule Check OK.

**Comment by sunghan-chang** [comment]
@thapav I need your help. I don't know what causes a compilation error.
```
CC:  init/os_start.c
In file included from /root/tizenrt/os/include/tinyara/fs/fs.h:73:0,
                 from /root/tizenrt/os/include/tinyara/semaphore.h:61,
                 from /root/tizenrt/os/include/pthread.h:80,
                 from /root/tizenrt/os/include/signal.h:75,
                 from /root/tizenrt/os/include/tinyara/sched.h:66,
                 from /root/tizenrt/os/include/sched.h:72,
                 from /root/tizenrt/os/include/tinyara/arch.h:119,
                 from init/os_start.c:63:
/root/tizenrt/os/include/tinyara/mqueue.h:99:15: error: field 'ntvalue' has incomplete type
  union sigval ntvalue;  /* Notification: Signal value */
               ^~~~~~~
```

**Comment by seinfra** [comment]
Target : [7a279e2a5bcf7a69d178020828df873d9681e96b] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [7a279e2a5bcf7a69d178020828df873d9681e96b] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [4635fbff323761e51df42eefdf9759d813d14933] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [4635fbff323761e51df42eefdf9759d813d14933] -

**Comment by seinfra** [comment]
Target : [3aa0c29e2dd0d948b097fe4503f47eaa47992297] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [3aa0c29e2dd0d948b097fe4503f47eaa47992297] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [6120d5efb7882685e424713785948a990a50bc7e] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [6120d5efb7882685e424713785948a990a50bc7e] - Code Rule Check (C++) OK.

**Pull request merged**
