### PR TITLE
framework/st_things : [defconfig] NFILE_DESCRIPTORS increased

### PR DESCRIPTION
**Pull request by JeongJunSik**
- change CONFIG_NFILE_DESCRIPTORS=16 to 64

### CODE REVIEW

**Comment by sunghan-chang** [comment]
You modified build/configs, not framework/st_things.
```
configs/artik053(s)/st_thigns: change a default value of NFILE_DESCRIPTORS  to 64

write the reason
```

**Comment by JeongJunSik** [comment]
Hello default config is 64.
so. i follow it

**Comment by JeongJunSik** [comment]
- 64 is not an optimized value, but this config is used by other apps as Ref
It is changed in consideration of convenience.

**Comment by juitem** [comment]
would you please write those reason as a commit comment?

**Pull request merged**
