### PR TITLE
media: Check invalid param early in MediaRecorder

### PR DESCRIPTION
**Pull request by junmin-kim**
Check whether vol is nullptr before enqueuing command

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [cf9f9659d97983887a50921632dfb97353ec6a34] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [cf9f9659d97983887a50921632dfb97353ec6a34] - Code Rule Check (C++) OK.

**Comment by jsdosa** [comment]
I think it is correct to first check whether the worker is alive in the current structure.
Let's think about this part as a whole.

**Comment by Taejun-Kwon** [comment]
good point.

**Pull request merged**
