### PR TITLE
build/tools/amebad/bootloader/: Modify KM0 bootloader and defconfig for OTA2 region offset change.

### PR DESCRIPTION
**Pull request by fengyunlai**
Modify KM0 bootloader and defconfig for OTA2 region offset change. Also set each OTA image size to 1792KB.

### CODE REVIEW

**Comment by Taejun-Kwon** [comment]
Chang has changed some of defconfig, https://github.com/Samsung/TizenRT/pull/4755
please refer to it and update this.

**Comment by fengyunlai** [comment]
> Chang has changed some of defconfig, #4755
> please refer to it and update this.

Sure, just updated. Thanks

**Comment by sunghan-chang** [comment]
@fengyunlai Is there any way to test OTA2 region?

**Comment by fengyunlai** [comment]
> @fengyunlai Is there any way to test OTA2 region?

Dear Mr Chang. From my side I have tested it by using our image tool. 
Our current boot process is if both OTA1, OTA2 are valid, AmebaD will boot from OTA2, if only 1 image is valid, AmebaD will boot from that valid image.
So I actually download different images to OTA1 and OTA2. And boot to see it boots from OTA2.
Then I erase the 1st 4KB of OTA2 offset and boot again, it boots from OTA1.

**Comment by sunghan-chang** [comment]
@fengyunlai 
1. Could you let me know the address of OTA2? Is 0x0824_0000 right? (OTA1 : 0x0808_0000 ?)
2. How do you check the validation of binary?

**Comment by sunghan-chang** [comment]
@fengyunlai Can we test what you say with this PR?

**Comment by fengyunlai** [comment]
> @fengyunlai Can we test what you say with this PR?

Yes certainly.

**Comment by fengyunlai** [comment]
> @fengyunlai
> 
> 1. Could you let me know the address of OTA2? Is 0x0824_0000 right? (OTA1 : 0x0808_0000 ?)
> 2. How do you check the validation of binary?

1. You are right,  OTA1 : 0x0808_0000, OTA2 : 0x0824_0000.
2. I think the test method I used have testd each OTA's start offset correctness. And as long as the image size is within given region, the images should be valid.

**Review by sunghan-chang — APPROVED** [review]

**Pull request merged**
