### PR TITLE
Added functions to read RSSI and IP address into LWM2M connectivity o…

### PR DESCRIPTION
**Pull request by dr-venkman**
…bject

### CODE REVIEW

**Comment by dr-venkman** [comment]
@Taejun-Kwon Please check the RSSI and IP address functionality
@sunghan-chang Please check whether code formatting looks ok

**Comment by sunghan-chang** [comment]
@dr-venkman This file is in extern folder. You don't need to follow Tizen coding style.

**Comment by dr-venkman** [comment]
@sunghan-chang Thanks, will retain the code as is then.
@Taejun-Kwon Please chek the RSSI and IP address read functions. For now, I have used the dm_conn APIs directly. Replacing them by syscalls is future work.

**Comment by sunghan-chang** [comment]
@dr-venkman I have a question. Is this come from wakaama or modified by you? The reason I asked is that this is in extern and extern folder shows we will not modify and we don't have any responsibility to resolve any problem.

**Comment by dr-venkman** [comment]
@sunghan-chang Very valid question. Actually we modified it, and yes, it should therefore not be in external folder. Once we have decided on a folder structure (mostly under dm framework), we will move wakaama there.

**Pull request merged**
