### PR TITLE
Remove three ITC from itc_arastorage_main.c

### PR DESCRIPTION
**Pull request by bipin4321**
Remove below ITCs:
itc_arastorage_db_print_header_n_after_deinit
itc_arastorage_cursor_get_count_n_after_deinit
itc_arastorage_cursor_get_row_n_after_deinit

Signed-off-by: bipinkumar <bipin.k@samsung.com>

### CODE REVIEW

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by sunghan-chang** [comment]
@bipin4321 Please write the reason why you remove them on commit description.

**Comment by bipin4321** [comment]
@manoj11588612 please review

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by jeongarmy** [comment]
please update commit message about the reason why these testcase are invalid.
When we call db_deinit, real data of db will be deinitialized, not cursor.
That means we can get a cursor data after db_deinit and it is not a wrong operation.
When we try to access db data through cursor, we can meet an error.

**Comment by samegautam** [comment]
@jeongarmy  : we have discussed with developer on same.
Developer response was "I think these are not needed. remains which call db functions are enough for testing 'after deinit'.
".

**Comment by seinfra** [comment]
Code Rule Check OK.

**Pull request merged**
