### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by sunghan-chang**
1. external/iotivity: fix compilation warning
2. framework/wifi_manager: fix menuconfig warnings
3. remove "NSH" word
4. app/system/poweroff, flash_eraseall: enable builtin functionality

### CODE REVIEW

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by lokeshbv** [comment]
Hello @sunghan-chang , If possible please remove word "nsh"(see image below) also from the code base as in this commit [remove "NSH" word](https://github.com/Samsung/TizenRT/pull/1266/commits/0b94b193825dbbda0801ab69c0f0333ad3ac2b3b)

screenshot from 2018-02-12 12 55 00

**Comment by seinfra** [comment]
Code Rule Check OK.

**Pull request merged**
