### PR TITLE
drivers/audio: fix some bad NULL checks

### PR DESCRIPTION
**Pull request by junmin-kim**

### CODE REVIEW

**Comment by sunghan-chang** [comment]
@junmin-kim Why don't you say `audio` in commit title?

**Comment by junmin-kim** [comment]
@sunghan-chang Fixed it

**Comment by seinfra** [comment]
Target : [d0cf8f054ae1f7d73c87621fd738a311af089c97] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [d0cf8f054ae1f7d73c87621fd738a311af089c97] - Code Rule Check (C++) OK.

**Pull request merged**
