### PR TITLE
os/LibTargets.mk : modify call to Makefile for mm, wqueue and lib

### PR DESCRIPTION
**Pull request by abhishek-samsung**
Currently, the following mm, wqueue and lib are not being recompiled
when changes are made. Modified their respective calls to the Makefile
so that they are recompiled.

Signed-off-by: Abhishek Akkabathula <a.akkabathul@samsung.com>

### CODE REVIEW

**Review by jeongchanKim — COMMENTED** [review]
Only those three libs needed? Any other libs are okay?

**Comment by abhishek-samsung** [comment]
> Only those three libs needed? Any other libs are okay?
This was happening for libs that had two pass build. libuarch and libkarch were being compiled without any problem. I found the problem with mm, lib, and wqueue only.

**Comment by jeongchanKim** [comment]
> > Only those three libs needed? Any other libs are okay?
> 
> This was happening for libs that had two pass build. libuarch and libkarch were being compiled without any problem. I found the problem with mm, lib, and wqueue only.

Okay. But arch is also two pass build, I think. libkarch, libuarch.
They are also okay?

**Comment by abhishek-samsung** [comment]
> > > Only those three libs needed? Any other libs are okay?
> > 
> > 
> > This was happening for libs that had two pass build. libuarch and libkarch were being compiled without any problem. I found the problem with mm, lib, and wqueue only.
> 
> Okay. But arch is also two pass build, I think. libkarch, libuarch. They are also okay?

Yes, arch is getting build fine as the rules of libkarch and libuarch are directly available in the Makefile
https://github.com/Samsung/TizenRT/blob/67cc2cb1d43b58c9eac89dca71ee6c2d57f3f994/os/arch/arm/src/Makefile#L189-L193
In the case of mm (wqueue/lib), during 2 pass build, the Makefile is calling itself recursively by passing a couple of more variables. This recursive call can be skipped by providing the additional variables during the first call (LibTargets.mk) itself.
https://github.com/Samsung/TizenRT/blob/67cc2cb1d43b58c9eac89dca71ee6c2d57f3f994/os/mm/Makefile#L110-L122

**Comment by jeongchanKim** [comment]
> > > > Only those three libs needed? Any other libs are okay?
> > > 
> > > 
> > > This was happening for libs that had two pass build. libuarch and libkarch were being compiled without any problem. I found the problem with mm, lib, and wqueue only.
> > 
> > 
> > Okay. But arch is also two pass build, I think. libkarch, libuarch. They are also okay?
> 
> Yes, arch is getting build fine as the rules of libkarch and libuarch are directly available in the Makefile
> 
> https://github.com/Samsung/TizenRT/blob/67cc2cb1d43b58c9eac89dca71ee6c2d57f3f994/os/arch/arm/src/Makefile#L189-L193
> 
> 
> In the case of mm (wqueue/lib), during 2 pass build, the Makefile is calling itself recursively by passing a couple of more variables. This recursive call can be skipped by providing the additional variables during the first call (LibTargets.mk) itself.
> https://github.com/Samsung/TizenRT/blob/67cc2cb1d43b58c9eac89dca71ee6c2d57f3f994/os/mm/Makefile#L110-L122

Thanks for reply.

**Review by jeongchanKim — APPROVED** [review]
Looks good to me.

**Review by thapav — APPROVED** [review]
lgtm

**Review by sunghan-chang — APPROVED** [review]

**Pull request merged**
