### PR TITLE
build/tools/amebad/bootloader/: Add erase binary flow for hotfix.

### PR DESCRIPTION
**Pull request by fengyunlai**
Adding erase binary feature and "da""ea""es""dd" flow for hotfix.

### CODE REVIEW

**Review by jeongarmy — APPROVED** [review]
LGTM

**Review by sunghan-chang — APPROVED** [review]

**Comment by fengyunlai** [comment]
From Mr Chang: @fengyunlai When I check this latest km0 bootloader, it prints version as 6099f3d_2021/08/16 even it was released at Nov. Could you check the version? We can't distinguish the bootloader by the version now.

Yes you are right. Sorry that the version does not change at last commit. Do you want me to raise new PR of bootloader with correct version?

**Comment by sunghan-chang** [comment]
@fengyunlai Could you update it with our new requirement @jeongarmy sent yesterday? No need to update current one.

**Comment by fengyunlai** [comment]
> @fengyunlai Could you update it with our new requirement @jeongarmy sent yesterday? No need to update current one.

Sure. Thank you

**Pull request merged**
