### PR TITLE
i2c: Fix makefile to enable i2c app

### PR DESCRIPTION
**Pull request by rzr**
It has been tested on ARTIK053

Change-Id: I08d87bffb50332e603dd9308622747bbe950d585
Signed-off-by: Philippe Coval <p.coval@samsung.com>

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [4d3636d171e6a9c6cd92958bdca301ae0cc85dd0] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [4d3636d171e6a9c6cd92958bdca301ae0cc85dd0] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [2acb6dc3b8d764ec18a5a550837cfaa3da1b88ce] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [2acb6dc3b8d764ec18a5a550837cfaa3da1b88ce] - Code Rule Check (C++) OK.

**Comment by rzr** [comment]
Should I make 2 PR for this ?

Maybe I should change order to prevent:
https://travis-ci.org/Samsung/TizenRT/jobs/453097081

**Pull request merged**
