### PR TITLE
apps/examples/elf: add distclean command support

### PR DESCRIPTION
**Pull request by sangam-swami**
This patch fix the build error due to previous distclean failure.

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [961dfaadc8f1777c2dba03257b90f403805047f5] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [961dfaadc8f1777c2dba03257b90f403805047f5] - Code Rule Check (C++) OK.

**Comment by sunghan-chang** [comment]
@sangam-swami To know what you include in this PR, how about below as a title?
```
apps/examples/elf: add distclean command support
```

We want what you do instead of what result is as a title.

**Comment by sangam-swami** [comment]
> @sangam-swami To know what you include in this PR, how about below as a title?
> 
> ```
> apps/examples/elf: add distclean command support
> ```
> 
> We want what you do instead of what result is as a title.

yes updated..

**Pull request merged**
