### PR TITLE
libc/misc : Fix crc32 algorithm

### PR DESCRIPTION
**Pull request by YiHyunJin**
The crc32 function was not operate. So modified to operate.

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [04463c5c51fcca1c23ee1a38971470ec8740d39f] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [04463c5c51fcca1c23ee1a38971470ec8740d39f] - Code Rule Check (C++) OK.

**Comment by jeongchanKim** [comment]
Please divide the PR for modifying libc and TC.

**Comment by seinfra** [comment]
Target : [ece07bd16b5fc9239d46f223abe4bcff2290ad14] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [ece07bd16b5fc9239d46f223abe4bcff2290ad14] - Code Rule Check (C++) OK.

**Pull request merged**
