### PR TITLE
build/tools/amebad/bootloader: Fix missing bootloader for KM0

### PR DESCRIPTION
**Pull request by fengyunlai**
This change is to add missing KM0 bootloader.

### CODE REVIEW

**Comment by sunghan-chang** [comment]
@fengyunlai Thank you for PR.  But because this is the open source project, we try to manage commit history. This commit title is difficult to know what it is. 
Could you add the location in title to say for which board?
```
build/tools/amebad: Fix missing bootloader for KM0.
```

**Comment by fengyunlai** [comment]
> @fengyunlai Thank you for PR.  But because this is the open source project, we try to manage commit history. This commit title is difficult to know what it is.
> Could you add the location in title to say for which board?
> build/tools/amebad: Fix missing bootloader for KM0.

**Comment by fengyunlai** [comment]
> @fengyunlai Thank you for PR.  But because this is the open source project, we try to manage commit history. This commit title is difficult to know what it is.
> Could you add the location in title to say for which board?
> build/tools/amebad: Fix missing bootloader for KM0.

Thank you for review, Mr Chang. May I know what kind of changes exactly you want me to make? Because the current title has already included board "RTL8721CSM" and location "/build/tools/amebad/bootloader":

[Realtek][RTL8721CSM] /build/tools/amebad/bootloader Fix missing bootloader for KM0.

**Comment by sunghan-chang** [comment]
> Thank you for review, Mr Chang. May I know what kind of changes exactly you want me to make?  Because the current title has already included board "RTL8721CSM" and location > "/build/tools/amebad/bootloader":
> 
> [Realtek][RTL8721CSM] /build/tools/amebad/bootloader Fix missing bootloader for KM0.

@fengyunlai That is written in PR, not in commit. User would see the commit history, not PR. You can write that using below
```sh
$ git commit --amend
```

**Comment by sunghan-chang** [comment]
Title is disappered. Only description is remain. Let me merge this using admin permission.

**Pull request merged**
