### PR TITLE
Qemu network module

### PR DESCRIPTION
**Pull request by vinaykadam1**
In this patch we have,
1) Sync with upstream.
2) Reverted all Code Coverage UTCs changes.
3) Added functionalities for Qemu.

### CODE REVIEW

**Comment by vinaykadam1** [comment]
Removed old qemu_codecoverage_tc branch and created qemu_network_module. Added tx source code for qemu.

**Comment by sunghan-chang** [comment]
@vinaykadam1 I don't understand what you do.
Why do you add "codecoverage : lwip : add unit test case" and "Merge branch 'master' of https://github.com/Samsung/TizenRT" in this pull request, qemu?

**Comment by sunghan-chang** [comment]
@vinaykadam1 Inside a commit, you should add a kind of changes. Inside qemu commit (last one), there are another kind of changes. That is not allowed.

**Comment by vinaykadam1** [comment]
@sunghan-chang: 
-Those test cases were not added by us. it was already present in master branch.
-We were getting many merge conflicts after pushing the code so took latest code from master to sync-up.
Please guide us for further corrections.

**Comment by vinaykadam1** [comment]
Ok I will remove that commit id.

**Pull request closed without merging**
