### PR TITLE
media: Remove redundant method in MediaWorker

### PR DESCRIPTION
**Pull request by junmin-kim**
increaseRefCnt, decreaseRefCnt can be replace with simple code.
And these methods are only used once.

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [c14b68bfed21c3eddc70faf2c369f077bd1f1efe] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [c14b68bfed21c3eddc70faf2c369f077bd1f1efe] - Code Rule Check Result:
framework/src/media/MediaWorker.h:44: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:OxV)
framework/src/media/MediaWorker.h:44: ERROR: [SPC_M_OPR] spaces required around that '<' (ctx:VxV)
framework/src/media/MediaWorker.h:44: ERROR: [SPC_M_OPR] spaces required around that '>' (ctx:VxW)
framework/src/media/MediaWorker.h:48: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:OxV)
framework/src/media/MediaWorker.h:49: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:OxV)

**Comment by jsdosa** [comment]
It is better to keep it functionally divided.

**Comment by jsdosa** [comment]
getRefCnt is not need.

**Comment by jsdosa** [comment]
I refer to shared_ptr for this logic.

**Comment by seinfra** [comment]
Target : [4ec590f69aa1d7c547b6844bece96951d505582a] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [4ec590f69aa1d7c547b6844bece96951d505582a] - Code Rule Check Result:
framework/src/media/MediaWorker.h:37: ERROR: [SPC_M_OPR] spaces required around that '<' (ctx:WxV)
framework/src/media/MediaWorker.h:37: ERROR: [SPC_M_OPR] spaces required around that '>' (ctx:VxE)
framework/src/media/MediaWorker.h:38: ERROR: [BRC_M_FTN] open brace '{' following function declarations go on the next line
framework/src/media/MediaWorker.h:38: ERROR: [SPC_M_OPR] spaces required around that '&&' (ctx:WxV)
framework/src/media/MediaWorker.h:38: ERROR: [SPC_M_OPR] spaces required around that '&&' (ctx:WxV)
framework/src/media/MediaWorker.h:41: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:OxV)
framework/src/media/MediaWorker.h:41: ERROR: [SPC_M_OPR] spaces required around that '<' (ctx:VxV)
framework/src/media/MediaWorker.h:41: ERROR: [SPC_M_OPR] spaces required around that '>' (ctx:VxW)
framework/src/media/MediaWorker.h:51: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:OxV)
framework/src/media/MediaWorker.h:51: ERROR: [SPC_M_OPR] spaces required around that '<' (ctx:VxV)
framework/src/media/MediaWorker.h:51: ERROR: [SPC_M_OPR] spaces required around that '>' (ctx:VxW)
framework/src/media/MediaWorker.h:53: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:OxV)
framework/src/media/MediaWorker.h:54: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:OxV)

**Pull request merged**
