### PR TITLE
os/board/rtl8720e: Add runtime image signature verify API

### PR DESCRIPTION
**Pull request by ziyik**

### CODE REVIEW

**Comment by jeongarmy** [comment]
@ziyik Hi, Are these trustzone libraries made based on ecode rtl8721csm_trustzone repo, https://github.ecodesamsung.com/TizenRT/rtl8721csm_trustzone?
tp1x and 8721e use same trustzone code?

**Comment by ziyik** [comment]
> @ziyik Hi, Are these trustzone libraries made based on ecode rtl8721csm_trustzone repo, https://github.ecodesamsung.com/TizenRT/rtl8721csm_trustzone? tp1x and 8721e use same trustzone code?

No, Tp1x and Tp1e do not share same trustzone code.
Once the base is ready we will inform to have another repo like Tp1x

**Comment by jeongarmy** [comment]
> > @ziyik Hi, Are these trustzone libraries made based on ecode rtl8721csm_trustzone repo, https://github.ecodesamsung.com/TizenRT/rtl8721csm_trustzone? tp1x and 8721e use same trustzone code?
> 
> No, Tp1x and Tp1e do not share same trustzone code. Once the base is ready we will inform to have another repo like Tp1x

1. Then did you make these trustzone libraries based on tp1x trustzone code?
2. Loadable verify API has hard-coded key in tp1x. Does it have same hard-coded key with tp1x?
3. I received some sample code from eric.kim and it called with up_allocate/free_secure_context.
Should it be called with up_allocate/free_secure_context on TP1e? We call verify API without secure context on TP1x. Please check.

**Comment by ziyik** [comment]
> > > @ziyik Hi, Are these trustzone libraries made based on ecode rtl8721csm_trustzone repo, https://github.ecodesamsung.com/TizenRT/rtl8721csm_trustzone? tp1x and 8721e use same trustzone code?
> > 
> > 
> > No, Tp1x and Tp1e do not share same trustzone code. Once the base is ready we will inform to have another repo like Tp1x
> 
> 1. Loadable verify API has hard-coded key in tp1x. Does it have same hard-coded key with tp1x?
> 2. I received some sample code from eric.kim and it called with up_allocate/free_secure_context.
>    Should it be called with up_allocate/free_secure_context on TP1e? We call verify API without secure context on TP1x. Please check.
> 3. Could you please tell me when you can share  tp1e trustzone codes?

1. Yes, currently it used the same hard-coded key as Tp1x. (default key)
2. Yes, it should be called with up_allocate/free_secure_context for both TP1x and TP1e. This API is an NSC, OS should allocate secure context for it. Could I know where TP1x called this API?
3. For this I can't give you an exact time, we will discuss it with Eric when it is ready.

**Comment by jeongarmy** [comment]
> > > > @ziyik Hi, Are these trustzone libraries made based on ecode rtl8721csm_trustzone repo, https://github.ecodesamsung.com/TizenRT/rtl8721csm_trustzone? tp1x and 8721e use same trustzone code?
> > > 
> > > 
> > > No, Tp1x and Tp1e do not share same trustzone code. Once the base is ready we will inform to have another repo like Tp1x
> > 
> > 
> > 
> > 1. Loadable verify API has hard-coded key in tp1x. Does it have same hard-coded key with tp1x?
> > 2. I received some sample code from eric.kim and it called with up_allocate/free_secure_context.
> >    Should it be called with up_allocate/free_secure_context on TP1e? We call verify API without secure context on TP1x. Please check.
> > 3. Could you please tell me when you can share  tp1e trustzone codes?
> 
> 1. Yes, currently it used the same hard-coded key as Tp1x. (default key)
> 2. Yes, it should be called with up_allocate/free_secure_context for both TP1x and TP1e. This API is an NSC, OS should allocate secure context for it. Could I know where TP1x called this API?
> 3. For this I can't give you an exact time, we will discuss it with Eric when it is ready.

This API is used in commercial repo only. It is wrapped by up_verify_usersignature and binary manager calls up_verify_usersignature to verify loadable binaries. You can see it in up_verify_usersignature.c in commercial repo.

**Comment by ziyik** [comment]
> > > > > @ziyik Hi, Are these trustzone libraries made based on ecode rtl8721csm_trustzone repo, https://github.ecodesamsung.com/TizenRT/rtl8721csm_trustzone? tp1x and 8721e use same trustzone code?
> > > > 
> > > > 
> > > > No, Tp1x and Tp1e do not share same trustzone code. Once the base is ready we will inform to have another repo like Tp1x
> > > 
> > > 
> > > 
> > > 1. Loadable verify API has hard-coded key in tp1x. Does it have same hard-coded key with tp1x?
> > > 2. I received some sample code from eric.kim and it called with up_allocate/free_secure_context.
> > >    Should it be called with up_allocate/free_secure_context on TP1e? We call verify API without secure context on TP1x. Please check.
> > > 3. Could you please tell me when you can share  tp1e trustzone codes?
> > 
> > 
> > 
> > 1. Yes, currently it used the same hard-coded key as Tp1x. (default key)
> > 2. Yes, it should be called with up_allocate/free_secure_context for both TP1x and TP1e. This API is an NSC, OS should allocate secure context for it. Could I know where TP1x called this API?
> > 3. For this I can't give you an exact time, we will discuss it with Eric when it is ready.
> 
> This API is used in commercial repo(ecode TizenRT_RF) only. It is wrapped by `up_verify_usersignature` and binary manager calls it to verify loadable binaries. You can see it in up_verify_usersignature.c in commercial repo. We didn't call up_allocate/free_secure_context when calling verify API on TP1x. Could you check usages in TP1x commercial repo?

I don't have access to commercial repo (ecode TizenRT_RF). I have verified that calling NSC API from non-seucre will cause hardfault. Could you check is up_verify_usersignature a secure or non-secure area API?

**Comment by sunghan-chang** [comment]
@ziyik It's non-secure. It directly calls `ameba_hal_SignatureVerify` without any other code. Doesn't it execute context APIs internally?

**Comment by ziyik** [comment]
> @ziyik It's non-secure. It directly calls `ameba_hal_SignatureVerify` without any other code. Doesn't it execute context APIs internally?

Nope, it does not execute context APIs internally. If you used the test code I provided and remove up_allocate/free_secure_context it will cause hardfault.

**Review by jeongarmy — COMMENTED** [review]
Could you add the example to commit message?
```
int result;
up_allocate_secure_context(CONFIG_SE_SECURE_CONTEXT_SIZE);
uint32_t* loadable_addr = (uint32_t*)0x08680000;
result = ameba_hal_SignatureVerify(loadable_addr);
sedbg("wrap_ameba_hal_SignatureVerify: %d\n", result);
up_free_secure_context();
```

**Comment by ziyik** [comment]
> Could you add the example to commit message?
> 
> ```
> int result;
> up_allocate_secure_context(CONFIG_SE_SECURE_CONTEXT_SIZE);
> uint32_t* loadable_addr = (uint32_t*)0x08680000;
> result = ameba_hal_SignatureVerify(loadable_addr);
> sedbg("wrap_ameba_hal_SignatureVerify: %d\n", result);
> up_free_secure_context();
> ```

Added.

**Review by jeongarmy — APPROVED** [review]
It looks good

**Pull request merged**
