### PR TITLE
Add bootprep.sh script.

### PR DESCRIPTION
**Pull request by btheosam**
This script generates a c file with partition table so that
it can be compiled and stored in flash to aid bootloader in
image upgrade.

### CODE REVIEW

**Comment by btheosam** [comment]
created bootprep.c file .

/*Auto Generated file.Dont edit here */

#include <stdint.h>
#include <stddef.h> /* for NULL */

typedef struct __attribute__((packed))
{
        uint8_t bin_name[16];   /* Binary Name */
        uint32_t offset;        /* Location address */
        uint32_t size;          /* Size in bytes */
        uint8_t type[16];       /* Partition type - smartfs, none, ftl etc */
        uint8_t subtype[8];     /* Subtype - data, code, etc */
        uint8_t flags;          /* Reserved for now */
} partition_entry_t;

partition_entry_t partitions[11]={
        {"bl1",0x4000000,16384,"none",NULL,0},
        {"sssro",0x4004000,49152,"ftl",NULL,0},
        {"bl2",0x4010000,196608,"none",NULL,0},
        {"sssfw",0x4040000,32768,"none",NULL,0},
        {"wlanfw",0x4048000,524288,"none",NULL,0},
        {"os",0x40c8000,2457600,"none",NULL,0},
        {"factory",0x4320000,1572864,"none",NULL,0},
        {"ota",0x44a0000,1572864,"ftl",NULL,0},
        {"user",0x4620000,1433600,"smartfs",NULL,0},
        {"nvram",0x477e000,8192,"config",NULL,0},
        {"sssrw",0x4780000,524288,"none",NULL,0},
}
~                                                                                                                          
~                                                                                                                          
~                                                                                                                          
~                                                                                                                          
~

**Comment by seinfra** [comment]
Target : [081baa564db89176ff486936d7fac0a32d30a3f4] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [081baa564db89176ff486936d7fac0a32d30a3f4] - Code Rule Check OK.

**Comment by sunghan-chang** [comment]
two things
1. Is there any ARTIK-specific code? If it isn't, let's make a common folder and put this in it to use it for all of boards.
2. Can we replace partition_gen.sh in ARTIK05x?

**Comment by seinfra** [comment]
Target : [40d2c20f15ebe9314396615e8f0c16cc5b56764c] -

**Comment by seinfra** [comment]
Target : [40d2c20f15ebe9314396615e8f0c16cc5b56764c] -

**Comment by seinfra** [comment]
Target : [c89784aea9d468deb8cabf8d4e769315e5239f85] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [c89784aea9d468deb8cabf8d4e769315e5239f85] - Code Rule Check OK.

**Comment by btheosam** [comment]
Yes, bootprep script functionality can replace the partitioin gen script and will perform extra work. 
In future, once bootprep is completed and tested for image upgrade, it can be merged into parititon gen script or vice versa. Until then not-wise to disturb existing script. For sure, there will be just ' one of these' in future.

Regarding moving into common artik05x directory, for now, it is being tested on artik053 only. In future, if it works on all, then can move inside.

**Comment by seinfra** [comment]
Target : [ca92b0aa8b9547229756f8e583b025cea4fa5965] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [ca92b0aa8b9547229756f8e583b025cea4fa5965] - Code Rule Check OK.

**Comment by btheosam** [comment]
This bootprep.sh script is planned in such a way to NOT disturb existing infrastructure of ARTIK and this is NOT integrated into mainstream. There are atleast 3 TODO & NOTE in this script. The primary objective of pushing this script early is to continue developing the image upgrade in the main branch without disturbing existing infra.

**Comment by btheosam** [comment]
Test Result from ARTIK053 (after excedution of this script)

U-BOOT >
U-BOOT >
U-BOOT > md 0x04780000 0x21b
04780000: 00316c62 00000000 00000000 00000000    bl1.............
04780010: 04000000 00004000 656e6f6e 00000000    .....@..none....
04780020: 00000000 00000000 00000000 00000000    ................
04780030: 73737300 00006f72 00000000 00000000    .sssro..........
04780040: 00400000 00c00004 6c746600 00000000    ..@......ftl....
04780050: 00000000 00000000 00000000 00000000    ................
04780060: 6c620000 00000032 00000000 00000000    ..bl2...........
04780070: 00000000 00000401 6f6e0003 0000656e    ..........none..
04780080: 00000000 00000000 00000000 00000000    ................
04780090: 73000000 77667373 00000000 00000000    ...sssfw........
047800a0: 00000000 00040400 6e000080 00656e6f    ...........none.
047800b0: 00000000 00000000 00000000 00000000    ................
047800c0: 00000000 6e616c77 00007766 00000000    ....wlanfw......
047800d0: 00000000 04048000 00080000 656e6f6e    ............none
047800e0: 00000000 00000000 00000000 00000000    ................
047800f0: 00000000 00736f00 00000000 00000000    .....os.........
04780100: 00000000 0c800000 25800004 6e6f6e00    ...........%.non
04780110: 00000065 00000000 00000000 00000000    e...............
04780120: 00000000 61660000 726f7463 00000079    ......factory...
04780130: 00000000 00000000 00000432 6f6e0018    ........2.....no
04780140: 0000656e 00000000 00000000 00000000    ne..............
04780150: 00000000 6f000000 00006174 00000000    .......ota......
04780160: 00000000 00000000 00044a00 66001800    .........J.....f
04780170: 00006c74 00000000 00000000 00000000    tl..............
04780180: 00000000 00000000 72657375 00000000    ........user....
04780190: 00000000 00000000 04620000 0015e000    ..........b.....
047801a0: 72616d73 00736674 00000000 00000000    smartfs.........
047801b0: 00000000 00000000 72766e00 00006d61    .........nvram..
047801c0: 00000000 00000000 77e00000 00200004    ...........w.. .
047801d0: 6e6f6300 00676966 00000000 00000000    .config.........
047801e0: 00000000 00000000 73730000 00777273    ..........sssrw.
047801f0: 00000000 00000000 00000000 00000478    ............x...
04780200: 6f6e0008 0000656e 00000000 00000000    ..none..........
04780210: 00000000 00000000 ff000000 ffffffff    ................
04780220: ffffffff ffffffff ffffffff ffffffff    ................

**Comment by btheosam** [comment]
Had to close as this local branch was deleted.

**Pull request closed without merging**
