### PR TITLE
build/tools/amebalite/bootloader/ : Change hotfix download baud rate from 921600 to 1500000

### PR DESCRIPTION
**Pull request by fengyunlai**
Change hotfix download baud rate from 921600 to 1500000.
Increase FLASH write data phase bytes.
After above modifications, hotfix takes shorter time.

### CODE REVIEW

**Comment by sunghan-chang** [comment]
@fengyunlai This requires our script change together. But I get no requirement for this. Do you?
Is this just improvement without requirement?

**Comment by fengyunlai** [comment]
> @fengyunlai This requires our script change together. But I get no requirement for this. Do you? Is this just improvement without requirement?

Dear Mr Chang @sunghan-chang , Yes, only need to change the download_baudrate=1500000 in the script. This improvement is from Samsung HW RD team according to Eric.

**Comment by sunghan-chang** [comment]
> Dear Mr Chang @sunghan-chang , Yes, only need to change the download_baudrate=1500000 in the script. This improvement is from Samsung HW RD team according to Eric.

@fengyunlai Correct, we need only baudrate change in the script. But this causes we should maintain different script files for RTL8721CSM with only baudrate difference.

**Comment by fengyunlai** [comment]
> @fengyunlai Once we prepare two file management, I will merge this. It could take some time.

Got it, I think it's okay, thanks Mr Chang.

**Review by ewoodev — COMMENTED** [review]
LGTM.

**Review by jylee9613 — APPROVED** [review]
LGTM

**Review by jylee9613 — COMMENTED** [review]
I applyed this PR and downloaded binary files through hotfix (change download_baudrate to 1500000), but it still works with 921600. Could you check this bin file again?

**Comment by fengyunlai** [comment]
> 

Dear Lee, I double checked the binary again, it seems okay on my side.
It can work with 1500000, and it will fail when work with 921600.
Can you help check on your side about it? Thank you.

**Comment by jylee9613** [comment]
@fengyunlai I downloaded the binary using ttl macro files below. The addresses in ttl files are based on TizenRT_RF repo, so you should change to public code addresses. Thank you.

https://github.sec.samsung.net/RS6-RTOS/Hotfix/pull/10

**Comment by sunghan-chang** [comment]
@fengyunlai 1. There are two booloaders in RTL8720E, one is for tz enabled, another is for tz disabled. But This PR has `_tz` only.  Please upload both.
2. @jylee9613 've checked it with changed baudrate. But it does not work.

**Comment by sunghan-chang** [comment]
@fengyunlai Could you leave new bootloader version in the commit description? Sometimes we should know the version, it will help us to find the version.

**Comment by fengyunlai** [comment]
@sunghan-chang I have uploaded both tz and is(ignore) bootloaders. I added the version in the commit log. I also fixed a minor issue that ttl might not able to wait the string READY = 'HASH_CHECK_DONE' . Thank you Mr Chang for reminder.

**Review by sunghan-chang — COMMENTED** [review]
When I check the size change, 
```
BIN +4.13 KB (110%) 
build/tools/amebalite/bootloader/km4_boot_all.bin

 BIN -32 Bytes (100%) 
build/tools/amebalite/bootloader/km4_boot_all_tz.bin
```
IS is increased, but NS is decreased. Is this correct?

**Comment by fengyunlai** [comment]
> When I check the size change,
> 
> ```
> BIN +4.13 KB (110%) 
> build/tools/amebalite/bootloader/km4_boot_all.bin
> 
>  BIN -32 Bytes (100%) 
> build/tools/amebalite/bootloader/km4_boot_all_tz.bin
> ```
> 
> IS is increased, but NS is decreased. Is this correct?

Hi @sunghan-chang . I think it is correct, you see size increasement for km4_boot_all.bin because we have not maintained km4_boot_all.bin for 5 months. Previous changes are included in this latest version.

**Comment by sunghan-chang** [comment]
@fengyunlai Thank you for confirmation. But we could not check the baudrate changed. I asked Eric to check. Let's wait result and then let's merge.

**Comment by sunghan-chang** [comment]
@fengyunlai We are checking on it again. 
 @jylee9613 Please share your test result here again.

**Comment by fengyunlai** [comment]
@sunghan-chang  Thank you for your information, Mr Chang. @jylee9613 Thank you for your verification, glad to here that.

**Review by jylee9613 — APPROVED** [review]
LGTM

**Review by ewoodev — APPROVED** [review]
LGTM

**Review by sunghan-chang — APPROVED** [review]

**Pull request merged**
