### PR TITLE
apps/examples/ftpc/ftpc_cmds.c Fix typo error

### PR DESCRIPTION
**Pull request by csjs0820**
106 line Exitting -> Exiting

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [691639aa9667de5d966f040f0291a402727ab6ae] - Code Rule Check Result:
framework/src/media/voice/HardwareEndPointDetector.h:28: ERROR: [SPC_M_OPR] spaces prohibited around that ':' (ctx:WxW)
framework/src/media/voice/HardwareKeywordDetector.h:28: ERROR: [SPC_M_OPR] spaces prohibited around that ':' (ctx:WxW)

**Comment by seinfra** [comment]
Target : [691639aa9667de5d966f040f0291a402727ab6ae] - Code Rule Check (C++) OK.

**Comment by csjs0820** [comment]
I see. I will write the message again.

**Comment by csjs0820** [comment]
> I see. I will write the message again.

**Pull request closed without merging**
