### PR TITLE
(tools): fix memory/resource leaks

### PR DESCRIPTION
**Pull request by ravisankarg**
fixes below leaks:

tools/ttrace_parser/scripts/parse_dump.c:174]: (error) Memory leak: buffer
tools/ttrace_parser/scripts/parse_dump.c:201]: (error) Resource leak: file

### CODE REVIEW

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by sunghan-chang** [comment]
Could you let me know what's the meaning of ( )?

**Comment by ravisankarg** [comment]
@sunghan-chang (tools) in heading is supposed to tell the change is in tools sub-folder/module under RT code.

**Comment by sunghan-chang** [comment]
@ravisankarg Let's remove (). We already use ':' to split location and content.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by sunghan-chang** [comment]
Please remove a last commit, "Merge branch 'master' of https://github.com/ravisankarg/TizenRT".
```
git reset --hard HEAD^
git push -f
```

**Comment by ravisankarg** [comment]
@sunghan-chang , thanks for the tip!

**Comment by seinfra** [comment]
Code Rule Check OK.

**Pull request merged**
