### PR TITLE
Fix lwip2.0 related build issues

### PR DESCRIPTION
**Pull request by dr-venkman**
Add AF_UNIX, PF_UNIX and MSG_NOSIGNAL enums to lwip sockets.h file.

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [91d7a6a141132d77f5cac31b222dab125796714e] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [91d7a6a141132d77f5cac31b222dab125796714e] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [1bcab59e32eafba89b92bc64c369adfbab8e5149] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [1bcab59e32eafba89b92bc64c369adfbab8e5149] - Code Rule Check OK.

**Comment by sunghan-chang** [comment]
@dr-venkman 
@sinzah who is maintainer of lwip on RT said, lwip does NOT support AF UNIX. Because of that, he removed definition of AF UNIX. Do we merge this?

**Comment by sunghan-chang** [comment]
@dr-venkman @pillip8282 Please find #1463 's third commit.

**Pull request closed without merging**
