### PR TITLE
net/bluetooth: Fix warning messages

### PR DESCRIPTION
**Pull request by Wootak**
Fix net/bluetooth warning messages.

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [1c9617cbc2a39ecc3e6ca9a49f04da600783a890] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [1c9617cbc2a39ecc3e6ca9a49f04da600783a890] - Code Rule Check OK.

**Comment by sunghan-chang** [comment]
@Wootak Could you check our [commit rules](https://github.com/Samsung/TizenRT/wiki/Documentations#commit-rules)? This is not acceptable.

**Comment by Wootak** [comment]
I updated the commit message.

**Pull request merged**
