### PR TITLE
Fix memory leaks.

### PR DESCRIPTION
**Pull request by krantideep95**
[tools/ramdump/ramdump_tool.c:122]:  Resource leak: bin_fp
[tools/ttrace_parser/scripts/parse_dump.c:174]:  Memory leak: buffer
[tools/ttrace_parser/scripts/parse_dump.c:201]:  Resource leak: file

### CODE REVIEW

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by krantideep95** [comment]
I didn't know github will include all the commits from forked branch into one pull request. 
Basically, all these commits fix memory/resource leaks I found by running cppcheck tool.

**Comment by sunghan-chang** [comment]
1. You should resolve conflicts.
2. Don't use full path on commit title. Module name is enough.
```
tools/ramdump: fix resource leak bin_fp
tools/ttrace_parser : Fix memory leak
```

**Comment by krantideep95** [comment]
I'll submit a new pull request. Thanks for the review!

**Pull request closed without merging**
