### PR TITLE
[ITC] Fixing mismatch in data bytes sent and received between server and client

### PR DESCRIPTION
**Pull request by bipin4321**
by bipin.k

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [b42b651ca239d5bda6265c4e28f72b9818becf4e] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [b42b651ca239d5bda6265c4e28f72b9818becf4e] - Code Rule Check OK.

**Comment by samegautam** [comment]
@bipin4321 : Please remove extra space from line 123 before comma like strlen(buffer) - send_len ,

**Comment by seinfra** [comment]
Target : [8d769791b9ac74cc1f6d1cf33398a46539c6de31] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [8d769791b9ac74cc1f6d1cf33398a46539c6de31] - Code Rule Check (C++) OK.

**Comment by samegautam** [comment]
Look good to me.

**Comment by bipin4321** [comment]
@pillip8282 ,please review the comment has been updated .

**Comment by seinfra** [comment]
Target : [8ebc2998dcc702bbbc91af0a1d65c8442fbb9188] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [8ebc2998dcc702bbbc91af0a1d65c8442fbb9188] - Code Rule Check OK.

**Pull request merged**
