### PR TITLE
os\board\rtl8720e\src\component\bluetooth\driver\platform\amebalite\hci: Fix BLE scan stop delay issue.

### PR DESCRIPTION
**Pull request by yeetee179**

### CODE REVIEW

**Review by sunghan-chang — COMMENTED** [review]
Could you revert a file permission to 644 for os/board/rtl8720e/src/component/bluetooth/driver/platform/amebalite/hci/bt_normal_patch.c?

**Comment by sunghan-chang** [comment]
The title is too long.  How about below for commit title? (I don't mean the PR title, I mean the commit title)
```
board/rtl8720e/bluetooth: fix BLE scan ......

what issue is
why happened
how to resolve
```
And could you add description as well?

**Comment by sunghan-chang** [comment]
@yeetee179 Do you resolve the BLE scan issue? or resolve SVACE issue? Title looks the BLE scan issue, but modification location looks the SVACE issue. Are they the same reason??

**Comment by yeetee179** [comment]
@sunghan-chang I have modified the commit message as required.

**Comment by sunghan-chang** [comment]
@yeetee179 Once @taehwan-hwang checks the issue with this PR, he will merge.

**Comment by sunghan-chang** [comment]
@yeetee179 Due to RTL8720E_Support branch deletion, this PR is closed. Could you make a PR for the master again?

**Pull request closed without merging**
