### PR TITLE
Update ARTIK05x

### PR DESCRIPTION
**Pull request by sunghan-chang**
1. Supports new boards, ARTIK053s and ARTIK055s
2. Use artik05x for common operations including tools
3. Refactor arch and configs

### CODE REVIEW

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by JunhwanPark** [comment]
@sunghan-chang 
Thanks for making PR.
You can check [my release notes](https://github.com/SamsungARTIK/TizenRT/releases).
The @SamsungARTIK team will issue [v1.7.0](https://github.com/SamsungARTIK/TizenRT/releases/tag/ARTIK_SDK_1.7.0) on November 25th. 
I hope this news is a reference for you.
[Github Release](https://github.com/SamsungARTIK/TizenRT/releases)

**Comment by JunhwanPark** [comment]
If you want ac0b5db patch, you have to use this 5ac6fd720820914cbe5b54559c0ea5b9cbed12d4.
u-Boot version is `U-Boot 2017.01-g59977f7`.
I made the `bl2.bin` file used [here](https://github.com/SamsungARTIK/u-boot-artik/commit/59977f724fd9d5b2b114d0b3eedb5a5912ce16fa).

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Pull request merged**
