### PR TITLE
os/kernel/debug: Remove wrong description of sysdbg_read function

### PR DESCRIPTION
**Pull request by sangam-swami**
Remove wrong function description.

Signed-off-by: sangamanatha <sangam.swami@samsung.com>

### CODE REVIEW

**Review by sunghan-chang — APPROVED** [review]
Regardless of this change, how about renaming function name?
1. This function's main purpose is printing.
2. This function is not hooked into the read operation of ops.

**Comment by sunghan-chang** [comment]
How about title like below?
```
os/kernel/debug: Remove wrong description of sysdbg_read function
```

**Comment by sangam-swami** [comment]
> Regardless of this change, how about renaming function name?
> 
> 1. This function's main purpose is printing.
> 2. This function is not hooked into the read operation of ops.

yes will change this function name in other PR

**Comment by sangam-swami** [comment]
> How about title like below?
> 
> ```
> os/kernel/debug: Remove wrong description of sysdbg_read function
> ```

yes changed..

**Comment by deepaksrma** [comment]
LGTM

**Review by sunghan-chang — APPROVED** [review]

**Pull request merged**
