### PR TITLE
media: Enable audio, media utc in artik055s/audio

### PR DESCRIPTION
**Pull request by junmin-kim**
Enable audio_utc, media_utc.
Set entypoint as tc_main

### CODE REVIEW

**Comment by junmin-kim** [comment]
@Taejun-Kwon If you don't want this PR, I'll close it

**Comment by seinfra** [comment]
Target : [ec6b2b3a596507f8c32f7d8cab667eb8fac050f7] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [ec6b2b3a596507f8c32f7d8cab667eb8fac050f7] - Code Rule Check (C++) OK.

**Comment by sunghan-chang** [comment]
@junmin-kim Please write the location at first tab of title. "media" is wrong. "configs/artik055s/audio: xxxx"

**Pull request merged**
