### PR TITLE
Porting guide update for pehipherals

### PR DESCRIPTION
**Pull request by btheosam**
Add i2c porting instructions on pheripherals porting guide.

### CODE REVIEW

**Comment by btheosam** [comment]
Comments migrated from old review which got closed accidently due to branch deletion:
manoharahk:
Should it be instance?
btheosam: Yes

pradeepns85: Can we add information on how i2c clients are registered to I2C bus ?
btheosam: Could you elaborate here what you mean by i2c clients?
              coz, in i2c bus, there is no regisration. 


manoharahk:
Shall we provide a link to s5j i2c driver (arch/arm/src/s5j/s5j_i2c.c) as a reference?
Low level I2C driver usually bound to higher level device driver to provide a device node to application layer. Hence shall we add details about "i2c_uioregister()" which does a driver registration?
btheosam: Agreed and added.

**Comment by btheosam** [comment]
@manoharahk @pradeepns85 

I have migrated your comments from old reivew (which got closed accidently here).
Kindly echo your comments here.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by Taejun-Kwon** [comment]
@sunghan-chang please confirm this.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Pull request merged**
