### PR TITLE
build/configs/rtl8730e: Remove Support for Internal Flash 8M & Update Flash Status Bit for DDR Package

### PR DESCRIPTION
**Pull request by ZhenBei-Sin**

### CODE REVIEW

**Comment by ZhenBei-Sin** [comment]
Verification:

sstorage region (512KB) protected for PSARM and DDR package.
image

format internal (>512KB region) non-protect and success for erase.
image

**Comment by sunghan-chang** [comment]
@ZhenBei-Sin Does this resolve the internal flash issue with PR #6462 ?

**Comment by ZhenBei-Sin** [comment]
> @ZhenBei-Sin Does this resolve the internal flash issue with PR #6462 ?

Yes it solve for the PR#6462, Confirmed it working fine. As attached the above ss: format internal.

**Comment by jeongarmy** [comment]
Hi, I tested agin with a change, `CONFIG_FLASH_STATUS_BITS=0x50`.
But I still get errors like below.
What should I change or modify something more?

```
TASH>>cd mnt
TASH>>ls
/mnt:
TASH>>mkdir hello
smart_journal_checkin: Checkin Error, verify crc failed buf crc16 : 65535 calc crc : 54563
smart_writesector: Error writing to physical sector 8 ret : -5
smartfs_alloc_firstsector: Error setting new sector type for sector 12, ret : -5
smartfs_mkdir: Unable to allocate data sector for new entry, ret : -5
mkdir : mkdir failed

TASH>>format internal
amebasmart_flash_erase_verify: Not erased, address : 524288 value : 1251409920
smart_ioctl: Format Finished
```

**Comment by jeongarmy** [comment]
After erasing userfs region, I got same error. Could you please check again?

==========================
Erasing userfs partition
==========================

ImageTool 8730e for SDA V1.3

Number of Images: 1

Erase 2048  KB of flash from 0x08080000
Open serial port         ......    OK

UART erase...
Check download mode      ......    OK
Download flashloader     ......    OK
Internal flash size: 32 MB + External flash size: 64 MB
--> Package 2:DDR.
Check flash size         ......    OK
error: Flash is locked! Try to unlock...
Flash protection         ......    OK
Erase flash              ......    OK

**Comment by jeongarmy** [comment]
Please verify this example as well. Currently these values are different.
```
Copy SUCCESS. Write CRC = 2943736005
READ!!!! Path : /dev/mtdblock8

READ SUCCESS. READ CRC = 1413774052
```

```
#include <fcntl.h>
#include <crc32.h>

#define MTD_PATH "/dev/mtdblock8"

void mtd_test(void)
{
	int fd;
	int ret;
	char* download_path = MTD_PATH;
	uint32_t cal_crc = 0;
	char buffer[1024] = {0xff,};

	fd = open(download_path, O_WRONLY);
	if (fd < 0) {
		printf("Failed to open %s: errno %d\n", download_path, get_errno());
		return 0;
	}

	printf("Path : %s\n", MTD_PATH);

	int size = 1536 * 1024;
	int iteration = size / sizeof(buffer);
	int total = 0;
	for (int i = 0; i < iteration; i++){
		ret = write(fd, buffer, sizeof(buffer));
		if (ret != sizeof(buffer)) {
			printf("Failed to write buffer: %d. errno %d\n", ret, get_errno());
			close(fd);
			return 0;
		}
		cal_crc = crc32part(buffer, ret, cal_crc);
		total += ret;
		//printf("Write total %d [%d%%]\n", total, i * 100 / iteration);
	}
	printf("\nCopy SUCCESS. Write CRC = %u\n", cal_crc);
	close(fd);

	fd = open(download_path, O_RDONLY);
	if (fd < 0) {
		printf("Failed to open %s: errno %d\n", download_path, get_errno());
		return 0;
	}

	cal_crc = 0;
	printf("READ!!!! Path : %s\n", MTD_PATH);

	for (int i = 0; i < iteration; i++){
		ret = read(fd, buffer, sizeof(buffer));
		if (ret != sizeof(buffer)) {
			printf("Failed to read buffer: %d. errno %d\n", ret, get_errno());
			close(fd);
			return 0;
		}
		cal_crc = crc32part(buffer, ret, cal_crc);
		total += ret;
		//printf("Read total %d [%d%%]\n", total, i * 100 / iteration);
	}
	printf("\nREAD SUCCESS. READ CRC = %u\n", cal_crc);
	close(fd);
}
```

**Comment by ZhenBei-Sin** [comment]
> Hi, I tested agin with a change, `CONFIG_FLASH_STATUS_BITS=0x50`. But I still get errors like below. What should I change or modify something more?
> 
> ```
> TASH>>cd mnt
> TASH>>ls
> /mnt:
> TASH>>mkdir hello
> smart_journal_checkin: Checkin Error, verify crc failed buf crc16 : 65535 calc crc : 54563
> smart_writesector: Error writing to physical sector 8 ret : -5
> smartfs_alloc_firstsector: Error setting new sector type for sector 12, ret : -5
> smartfs_mkdir: Unable to allocate data sector for new entry, ret : -5
> mkdir : mkdir failed
> 
> TASH>>format internal
> amebasmart_flash_erase_verify: Not erased, address : 524288 value : 1251409920
> smart_ioctl: Format Finished
> ```
> 
> After erasing userfs region, I got same error. Could you please check again?
> 
> ```
> ==========================
> Erasing userfs partition
> ==========================
> 
> ImageTool 8730e for SDA V1.3
> 
> Number of Images: 1
> 
> Erase 2048  KB of flash from 0x08080000
> Open serial port         ......    OK
> 
> UART erase...
> Check download mode      ......    OK
> Download flashloader     ......    OK
> Internal flash size: 32 MB + External flash size: 64 MB
> --> Package 2:DDR.
> Check flash size         ......    OK
> error: Flash is locked! Try to unlock...
> Flash protection         ......    OK
> Erase flash              ......    OK
> ```

Hi @jeongarmy , 
Please provide the complete log and your current **.config** file. The file path is /os/.config. 
You can send it to me via email.

Thank You.

**Comment by Taejun-Kwon** [comment]
> > Hi, I tested agin with a change, `CONFIG_FLASH_STATUS_BITS=0x50`. But I still get errors like below. What should I change or modify something more?
> > ```
> > TASH>>cd mnt
> > TASH>>ls
> > /mnt:
> > TASH>>mkdir hello
> > smart_journal_checkin: Checkin Error, verify crc failed buf crc16 : 65535 calc crc : 54563

Last line means that it write to wrong address or read from wrong address.
In my opinion, status bit is not matter. As I checked your code, you using value of 24bit address... (for example 0x20 for erase, 0x21 is proper value)

**Comment by jeongarmy** [comment]
I applied bl32.bin file wrongly. It works well after applying this file again.

**Comment by ZhenBei-Sin** [comment]
> I applied bl32.bin file wrongly. It works well after applying this file again.

In the 1st comment, I was attached my $format internal result ss log (success).
Once Samsung side verification was done.
Please ensure that the product code for both Secure and TizenRT branches is applied accordingly, once this PR was merged.

Thank you.

**Review by sunghan-chang — APPROVED** [review]

**Pull request merged**
