### PR TITLE
build/configs/artik053 : changes in config file for artik053/tc

### PR DESCRIPTION
**Pull request by manoj11588612**
Configuration for Kernel and Filesystem changes as below
Enable Filesystem ITC
Enable Kernel ITC

Signed-off-by: manoj <manoj.g2@samsung.com>

### CODE REVIEW

**Comment by manoj11588612** [comment]
@sunghan-chang @sangwon03 @samegautam 
Please review.

**Comment by seinfra** [comment]
Target : [97e0d6d958a521893a5887065785d69a0d710ee8] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [97e0d6d958a521893a5887065785d69a0d710ee8] - Code Rule Check OK.

**Comment by sunghan-chang** [comment]
configs/artik053/tc : enable ITC of fs and kernel defaultly

I think above is better to know what you do by this commit.

**Comment by seinfra** [comment]
Target : [69fbcae9fe92c2c0fa85fedb30a1af57bd3fe0d7] -

**Comment by seinfra** [comment]
Target : [69fbcae9fe92c2c0fa85fedb30a1af57bd3fe0d7] -

**Comment by seinfra** [comment]
Target : [3572159562a373236cd2bd2bdfa959105a56914f] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [3572159562a373236cd2bd2bdfa959105a56914f] - Code Rule Check (C++) OK.

**Pull request merged**
