### PR TITLE
refactoring iotivity/iotjs build

### PR DESCRIPTION
**Pull request by sunghan-chang**
1. external/iotivity: fix syntax error on build_iotivity.sh
2. Makefile: move iotivity-specific build step to iotivity folder 
3. external/iotivity: support build log level

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [7bb639dd09dde35a126ca530bda56814b3a43068] -

**Comment by seinfra** [comment]
Target : [7bb639dd09dde35a126ca530bda56814b3a43068] -

**Comment by seinfra** [comment]
Target : [afd49cddfac883b003c747e60da58a83941ab106] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [afd49cddfac883b003c747e60da58a83941ab106] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [bbd3cdbd498ff11eeca3f021496423cc0222497e] - Code Rule Check OK.

**Comment by rzr** [comment]
I am considering to relocate this file outside external/iotjs to avoid overlapping with upstream tree...

Relate-to: https://github.com/Samsung/iotjs/pull/1732

**Pull request merged**
