### PR TITLE
os/board/rtl8721csm: Add prevention check in wlan lib and timer

### PR DESCRIPTION
**Pull request by lu04-wang**
- add lock to prevent from accessing 0 address
- add data length check to avoid hardfault
- fix hardfault caused by timer task preempt wifi driver task

### CODE REVIEW

**Comment by sunghan-chang** [comment]
@lu04-wang Could you check those wlan libraries including any other unmerged PR?

**Comment by lu04-wang** [comment]
> 



> @lu04-wang Could you check those wlan libraries including any other unmerged PR?

Hi @sunghan-chang
 this changes includes https://github.com/Samsung/TizenRT/pull/5715 changes

**Comment by lu04-wang** [comment]
> > 
> 
> > @lu04-wang Could you check those wlan libraries including any other unmerged PR?
> 
> Hi @sunghan-chang this changes includes #5715 changes

Hi @sunghan-chang I have recommit the changes which exclude  #5715 changes

**Comment by sunghan-chang** [comment]
@lu04-wang One question. There are some other PRs which includes lib changes. If we merge this and then merge other PR, then is it ok? I guess this PR change will be lost in the lib. Could you leave some caution description about this in the PRs?

**Comment by lu04-wang** [comment]
> @lu04-wang One question. There are some other PRs which includes lib changes. If we merge this and then merge other PR, then is it ok? I guess this PR change will be lost in the lib. Could you leave some caution description about this in the PRs?

Hi @sunghan-chang This commit exclude https://github.com/Samsung/TizenRT/pull/5715 changes, When https://github.com/Samsung/TizenRT/pull/5715 is reviewed and try to merge into master, there will be a conflict, at that moment, we will solve the conflict. And we also have os\board\rtl8721csm\src\libs\RELEASE_NOTE.txt to take care about the library version.

**Comment by keerthanalex** [comment]
Hi all,
Created new PR #5787 to resolve conflict of this PR.

**Pull request closed without merging**
