### PR TITLE
os/drivers/audio Modify a typo

### PR DESCRIPTION
**Pull request by wodonggun**
os/drivers/audio/alc5658.c : Modify a typo 
Line 1584 hardwaqre -> hardware

os/drivers/audio/alc5658.h : Modify a typo  …
Line 104 IN -> In
Line 119 IN -> In

os/drivers/audio/Kconfig : Modify a typo  …
Line 50 nothinig -> nothing

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [80e6391d743d1142c642d04f9b9aec7971e65ad8] - Code Rule Check Result:
apps/examples/mediaplayer/BufferInputDataSource.h:25: ERROR: [SPC_M_OPR] spaces prohibited around that ':' (ctx:WxW)
apps/examples/mediaplayer/BufferInputDataSource.h:25: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:VxO)
apps/examples/mediaplayer/BufferInputDataSource.h:25: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:OxV)
apps/examples/mediaplayer/BufferInputDataSource.h:25: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:VxO)
apps/examples/mediaplayer/BufferInputDataSource.h:25: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:OxV)
apps/examples/mediaplayer/BufferInputDataSource.h:39: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:OxV)
apps/examples/mediaplayer/BufferInputDataSource.h:39: ERROR: [SPC_M_OPR] spaces required around that '<' (ctx:VxV)
apps/examples/mediaplayer/BufferInputDataSource.h:39: ERROR: [SPC_M_OPR] spaces required around that '>' (ctx:VxW)
apps/examples/testcase/ta_tc/media/utc/gmock/utc_media_common.h:29: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:OxV)
apps/examples/testcase/ta_tc/media/utc/gmock/utc_media_common.h:31: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:WxO)
apps/examples/testcase/ta_tc/media/utc/gmock/utc_media_common.h:31: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:OxV)
apps/examples/testcase/ta_tc/media/utc/gmock/utc_media_common.h:31: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:VxO)
apps/examples/testcase/ta_tc/media/utc/gmock/utc_media_common.h:31: ERROR: [SPC_M_OPR] spaces required around that ':' (ctx:OxV)

**Comment by seinfra** [comment]
Target : [80e6391d743d1142c642d04f9b9aec7971e65ad8] - Code Rule Check (C++) OK.

**Comment by wodonggun** [comment]
I'm sorry. My repository is old version. 
so, retry again.

**Comment by sunghan-chang** [comment]
@wodonggun You re-opened this with #2487 so that I close this.

**Pull request closed without merging**
