### PR TITLE
os/drivers/wireless/realtek: Build fix in non protected configs.

### PR DESCRIPTION
**Pull request by sangam-swami**
Fix build error in non protected build environments.

Signed-off-by: Sangamanatha <sangam.swami@samsung.com>

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [5fb57d0a4e38504e32f79c1534384b75fe2d2e8b] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [5fb57d0a4e38504e32f79c1534384b75fe2d2e8b] - Code Rule Check OK.

**Comment by drashti304** [comment]
Looks good to me

**Comment by sunghan-chang** [comment]
@sangam-swami Could you write what and why you modify? I only know what result is from your title and description.

**Comment by sangam-swami** [comment]
> @sangam-swami Could you write what and why you modify? I only know what result is from your title and description.

Updated the commit description,
--------
rtk_drv driver display kmm_malloc as undefined error in non protected builds.
Add defination of the function through kmalloc.h to fix build error.
--------

**Comment by seinfra** [comment]
Target : [85aa42d0ff226a47cae261adef4b367f9aeba8d0] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [85aa42d0ff226a47cae261adef4b367f9aeba8d0] - Code Rule Check (C++) OK.

**Pull request merged**
