### PR TITLE
build configuration method refactor and enhancment

### PR DESCRIPTION
**Pull request by lokeshbv**
- os: update info about running of build configuration tool

- os: Add support for nconfig frontend 'make nconfig'

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [df05ca32d58936d80307b69f31d6cbe9bc11488f] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [df05ca32d58936d80307b69f31d6cbe9bc11488f] - Code Rule Check OK.

**Comment by sunghan-chang** [comment]
@lokeshbv Could you share the usages and purpose of nconfig?

**Comment by lokeshbv** [comment]
@sunghan, make nconfig is an alternative to menuconfig.
Usage is same as `make menuconfig` i.e. `make nconfig`

**Pull request merged**
