### PR TITLE
configs/imxrt1050-evk/nxp_demo : Enable CONFIG_C99_BOOL8 in defconfig

### PR DESCRIPTION
**Pull request by jeongchanKim**
To use SEMC, CONFIG_C99_BOOL8 should be enabled.

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [5114f1d49dfec5dc8295b3a83c1ccb2512b5caad] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [5114f1d49dfec5dc8295b3a83c1ccb2512b5caad] - Code Rule Check OK.

**Comment by sunghan-chang** [comment]
1. nxp_demo is in master so that we had better modify it in master first and then sync it.
2. nxp_demo does not require binary manager.

**Comment by sunghan-chang** [comment]
I already made a PR to update nxp_demo's defconfig. It enables SDRAM including C99_BOOL8. Let's close this.

**Pull request closed without merging**
