### PR TITLE
build/tools/amebasmart: Update pmc code for sleep type

### PR DESCRIPTION
**Pull request by ZhenBei-Sin**
build/tools/amebasmart: Update pmc code for sleep type
* The Long Run PM test encountered hang at CA32PG-KM4PG- and could not wake up, requiring a long press of the reset button to reboot.
* Issue: Long Run PG and Wakeup by LOGUART Causing KM4 to Unexpectedly Enter CG Mode, which requires a long press of the reset button to wake it up.
* Root Cause: During the execution of the AP PG flow, KM4 performed a sleep check before PWC was turned off, leading to an incorrect judgment.
* Solution:
- update pmc code for possible sleep type error
- update the flow to ensure that the AP sleep process completes before KM4 enters its sleep sequence
- ap_status_on check for HSYS_BIT_PSW_HP_AP_L2 in REG_HSYS_HP_PWC is replaced with a check for HSYS_BIT_FEN_AP in REG_HSYS_HP_FEN
* Verification:
- After entering CA32PG-KM4PG-, the system can be rebooted using a short press of the reset button.
- The long run PM test and wakeup process via LOG UART no longer results in a hang.

### CODE REVIEW

**Comment by ZhenBei-Sin** [comment]
Hi @ewoodev 

This is related to the LOGUART hang issue. 
Please help to verify this PR for the PSRAM and DDR board.

Thank You.

**Comment by zhongnuo-tang** [comment]
I have ran long run test for 3 days, no LOGUART hang observed during sleep-wakeup process in DDR package.

**Review by ewoodev — COMMENTED** [review]
PSRAM is not working 
I faced device hang during the booting seq

**Comment by ZhenBei-Sin** [comment]
> PSRAM is not working I faced device hang during the booting seq

Hi @ewoodev 

These changes should not affect boot-related processes; This PR is related to power management (PM) changes.
Verified with the loadable_ext_psram config: 
The system successfully booted up and ran for a 30-minute PM test period with the wakeup source set to LOG UART.

Attached: 
image

Please ensure your local PC includes these few changes PR:
**Compulsory**
PR6465: Update Flash Status Bit for DDR Package  (Merged TizenRT public)
PR6484: Sync PR#6102 into the SE (Merged TizenRT public)
PR6486: Change to polling mode when using IPC send in FLASH_Write_Lock (Merged TizenRT public)
 
PM-related 
PR#6489: build/tools/amebasmart: Update pmc code for sleep type

**Comment by sunghan-chang** [comment]
@ZhenBei-Sin I heard because of this, reset button works slowly. Could you write it in the issue as well? In SS, it's the main issue.

**Comment by ZhenBei-Sin** [comment]
> * Cause: During the execution of the AP PG flow, KM4 performed a sleep check before PWC was turned off, leading to an incorrect judgment.
> * Solution:

Hi @sunghan-chang  
Updated the commit message, please review. Thank You.

**Review by sunghan-chang — APPROVED** [review]

**Comment by ZhenBei-Sin** [comment]
> @ZhenBei-Sin Unfortunately, with this PR, we reproduced the issue again.. When we put a device idle for a long time, and then it also requires two seconds to reboot using the reset button..

Hi @sunghan-chang 
I’ll check it tomorrow.
To reproduce the issue:
1. Enter PG mode log displayed CA32PG-KM4PG.
2. Allow the device to idle for a few minutes or hours.
3. Send 1234567890 via loguart to wake it up.

Could you confirm if the reproduction steps are correct, and specify any exact idle time you've tested?

Thank you.

**Comment by sunghan-chang** [comment]
@ZhenBei-Sin At 3rd step, we pushed the reset button shortly. It does not do reboot. When we push 2 secs, it does.

**Comment by ZhenBei-Sin** [comment]
> @ZhenBei-Sin At 3rd step, we pushed the reset button shortly. It does not do reboot. When we push it in 2 secs, it does.

Ok get it. Let me try on tomorrow.

**Comment by ZhenBei-Sin** [comment]
Hi @sunghan-chang 

I tested the public code with the loadable_ext_psram config.
After entered PG mode (CA32PG-KM4PG-), the device remained idle for 5 minutes, 2 hours, and 4 hours, and it could be rebooted with a short press of the button (no need for a long and hold press).
You can refer to the video I shared with ZhongNuo/Dane.

However, as per Dane's report, in the product code, the issue of requiring a long press to boot can still be reproduced.
A debug .bin file has been provided, but with the debug.bin the reproduction rate is low.
Please allow some time for further investigation and testing.

Thank You.

**Pull request merged**
