### PR TITLE
framework/app: Appfw skeleton code from Tizen

### PR DESCRIPTION
**Pull request by zhouxinhe**
PR is not ready, status:
- AUL & AMD are missing
- Building pass
- Does not work

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [b737b95a6f67e3750c0964c6b122a7f40dfe6e8d] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [b737b95a6f67e3750c0964c6b122a7f40dfe6e8d] - Code Rule Check (C++) OK.

**Comment by Taejun-Kwon** [comment]
Will review this after UDS applied.

**Comment by zhouxinhe** [comment]
Made PR to internal repo.

**Pull request closed without merging**
