### PR TITLE
media: Add return value of DataSource API

### PR DESCRIPTION
**Pull request by junmin-kim**
if setChannels, setSampleRate, setPcmFormat get invlalid parameter,
it returns false

### CODE REVIEW

**Comment by junmin-kim** [comment]
@jsdosa I need your review

**Comment by seinfra** [comment]
Target : [8831c610b8d5b8a11e5b941efc41794897b9b5c7] -

**Comment by seinfra** [comment]
Target : [8831c610b8d5b8a11e5b941efc41794897b9b5c7] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [8831c610b8d5b8a11e5b941efc41794897b9b5c7] - Code Rule Check Result:
framework/include/media/DataSource.h:92: ERROR: [SPC_M_OPR] need consistent spacing around '&' (ctx:VxW)
framework/include/media/DataSource.h:92: ERROR: [SPC_M_OPR] spaces required around that '=' (ctx:VxV)

**Pull request closed without merging**
