### PR TITLE
build/configs, os: fix crash due to misaligned text and flash start

### PR DESCRIPTION
**Pull request by abhishek-samsung**
force text start to start at the start of flash partition. Also create map file for common which will be useful for debugging

### CODE REVIEW

**Review by r-prabu — APPROVED** [review]
crash fi changes looks fine for me

**Review by sunghan-chang — APPROVED** [review]

**Comment by sunghan-chang** [comment]
@abhishek-samsung When you get test result, could you leave it here as well?

**Comment by sunghan-chang** [comment]
@abhishek-samsung @r-prabu @kishore-sn Abhilash replied this worked well. Can we merge this now?

**Comment by abhishek-samsung** [comment]
> @abhishek-samsung @r-prabu @kishore-sn Abhilash replied this worked well. Can we merge this now?

Yes, it can be merged now.

**Review by kishore-sn — APPROVED** [review]

**Pull request merged**
