### PR TITLE
build/tools/amebad/bootloader/: Change CRC check for whole boot param(4K-4 Bytes), cut version Git sha to 1st 7 characters.

### PR DESCRIPTION
**Pull request by fengyunlai**
CRC check for whole bp, version print reduce to 7 chars.

Based on https://github.com/Samsung/TizenRT/pull/5359

### CODE REVIEW

**Review by sunghan-chang — APPROVED** [review]

**Comment by sunghan-chang** [comment]
@fengyunlai All are the same commit hash. Is that correct? Could you confirm?
```
bootloader_version km0_bootloader_ver_1275267_2021/12/15-21:26:58
bootloader_version km0_application_ver_1275267_2021/12/15-21:04:26
calibration_ok:[2:19:11]
bootloader_version km4_bootloader_ver_1275267_2021/12/15-21:10:03
```

**Comment by fengyunlai** [comment]
> @fengyunlai All are the same commit hash. Is that correct? Could you confirm?
> 
> ```
> bootloader_version km0_bootloader_ver_1275267_2021/12/15-21:26:58
> bootloader_version km0_application_ver_1275267_2021/12/15-21:04:26
> calibration_ok:[2:19:11]
> bootloader_version km4_bootloader_ver_1275267_2021/12/15-21:10:03
> ```

Sure Mr Chang, it's correct. Because the Git Sha is based on Realtek Tizenrt branch commit. Since I commit the changes of shorten Git version to 7 character the same time the same day on our SDK. So their commit hash should be the same.

**Comment by sunghan-chang** [comment]
@fengyunlai Thank you for confirmation.

**Comment by fengyunlai** [comment]
> @fengyunlai Thank you for confirmation.

No problem at all, you are welcome~

**Pull request merged**
