### PR TITLE
Merge CONFIG_LIBC_SCANSET from NuttX upstream code

### PR DESCRIPTION
**Pull request by Shyamakshi**
Current sscanf did not support regular expression parsing which is required for libcurl.

### CODE REVIEW

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by sunghan-chang** [comment]
@Shyamakshi As I left previous P.R., empty commit description is not allowed to merge.
```
Please fill commit description what you do in detail.
```
Above is written in commit rule. Please fill your P.R description into commit description.

**Comment by Shyamakshi** [comment]
@sunghan-chang, Updated the commit description. Please check. Thanks.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by juitem** [comment]
waiting for the review result from diffs from nuttx's for maintenances.
https://bitbucket.org/nuttx/nuttx/src/00d8d6698e5bfd5b93063f4bdab5c4b3c4fede5a/libc/stdio/lib_sscanf.c?at=master&fileviewer=file-view-default

**Comment by Shyamakshi** [comment]
@juitem, Thanks for sharing the nuttx upstream code reference. The nuttx upstream code can handle regular expressions. Hence this patch is not required.
I'll update this commit with the nuttx upstream code as it will be required for libcurl url parsing.

Thanks.

**Comment by seinfra** [comment]
Code Rule Check Result:
lib/libc/stdio/lib_sscanf.c:187: ERROR: [IDT_M_TAB] code indent should use tabs where possible
lib/libc/stdio/lib_sscanf.c:187: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
lib/libc/stdio/lib_sscanf.c:292: ERROR: [IDT_M_TAB] code indent should use tabs where possible
lib/libc/stdio/lib_sscanf.c:292: ERROR: [IDT_M_TAB] please, no spaces at the start of a line

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by sunghan-chang** [comment]
@Shyamakshi Main title should be what is changed. And you can write where you got it like " merged from Nuttx commit xxxx" at commit description.
```
libc/stdio: support CONFIG_LIBC_SCANSET  to process regular expressions

Current sscanf did not support regular expression parsing which is required for libcurl.
This commit comes from Nuttx commit xxxx
```

**Comment by Shyamakshi** [comment]
@sunghan-chang, Updated the commit message as per your recommendation.Please check.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by juitem** [comment]
I think we should decide the default value of this feature as Y or N.

**Comment by juitem** [comment]
the default value will be discussed separately

**Pull request merged**
