### PR TITLE
build/tools/amebasmart: update channel plan version

### PR DESCRIPTION
**Pull request by jwei5**
- Update version of wifi channel plans

### CODE REVIEW

**Comment by sunghan-chang** [comment]
@jwei5 I don't get what it is. Is this required from someone? Could you fill more explanation of this in the commit description?

**Comment by jwei5** [comment]
Hi @sunghan-chang , I have updated the commit with more details.
There was a request from Samsung HW to add new wifi channel plans to meet their certification requirements. This PR is to meet the requirements.

**Comment by sunghan-chang** [comment]
@jwei5 How to know the version updated? Is there any way to know applied channel plan from device console logs?

**Comment by Dane-Kang** [comment]
@sunghan-chang 
== version 4fe8863a2a 2024/07/12-11:15:18 ==
I think this version of Wi-Fi can tell whether the channel plan has been updated or not.

Is there any way to know applied channel plan from device console logs?
  -> We prepared additional PR for API change channel plan. and will print log whenever API is called. 
        https://github.com/Samsung/TizenRT/pull/6289 
  @jwei5 , Could you let us to know whether log will print whenever call wifi_set_chplan() ?

**Comment by jwei5** [comment]
Hi @sunghan-chang , @Dane-Kang 
Yes, for #6289 logs will be printed to show if wifi_set_chplan() returns success/fail and the channel plan set.
image

**Comment by hk-gwak** [comment]
Hello @jwei5,
"Added new channel plans to meet Samsung requirements" -> What is newly added channel plan at this PR?

**Comment by Dane-Kang** [comment]
@hk-gwak I just passed email to you.
Please check history.

**Comment by jwei5** [comment]
Rebased PR to include KM4 changes from adce04a

**Comment by jwei5** [comment]
Rebased PR to include KM4 changes from c727104

**Comment by jwei5** [comment]
Rebased PR to 7f0c9439cb93bf2bf175e4641fb0fb9418ac3e79

**Comment by jwei5** [comment]
Rebased PR to resolve conflict with dc0d941c9a3ed1bd94119f93f98bb875f43d43c7

**Review by hk-gwak — APPROVED** [review]
Looks good to me.

**Pull request merged**
