### PR TITLE
README.md : Tizen RT is renamed TizenRT.

### PR DESCRIPTION
**Pull request by davidfather**
For better look and feel, the space between 'Tizen' and 'RT' is removed.

### CODE REVIEW

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by jeongchanKim** [comment]
There are many "Tizen RT"s in md files and header files.
How about changing them all together?
You can use the below command line.
find . -type f -exec sed -i 's/Tizen RT/TizenRT/g' {} \;

**Comment by davidfather** [comment]
I did complete replacement as you recommended.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Pull request merged**
