### PR TITLE
media/utils : Move file position to 0 when id3 tag is no exist

### PR DESCRIPTION
**Pull request by Taejun-Kwon**

### CODE REVIEW

**Review by aadotverma — COMMENTED** [review]
Changes looks fine

**Review by s1-vivek — APPROVED** [review]
LGTM

**Review by vibhor-m — APPROVED** [review]
changes are OK

**Review by vibhor-m — APPROVED** [review]
changes are OK

**Comment by vibhor-m** [comment]
please add description in PR.

**Review by jsdosa — APPROVED** [review]
LGTM.

**Pull request merged**
