### PR TITLE
remove white space of tc

### PR DESCRIPTION
**Pull request by jsdosa**
remove white space of tc according to coding rules.

### CODE REVIEW

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by sunghan-chang** [comment]
@jsdosa I don't think we should make a commit only for this. Could you find same things in other places?

**Comment by jsdosa** [comment]
white space is a common thing that must be cleared according to coding rules.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Pull request merged**
