### PR TITLE
build/configs/imxrt1050-evk: Add userfs flash provision in download.sh script for Imxrt1050-evk.

### PR DESCRIPTION
**Pull request by amogh-samsung**
… script

-Added provision in download script to flash
 userfs (smartfs.bin) image to imxrt1050-evk board.
-Do a "sudo make download userfs" after
 "sudo make downlaod ALL" to flash smartfs.bin image.

Signed-off-by: Amogh Hassija <a.hassija@samsung.com>

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [e01dcbf9ab322c055221a87bf7b38b9a9a9925c2] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [e01dcbf9ab322c055221a87bf7b38b9a9a9925c2] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [27695e2bb608bef86184e92f3c58f0ad30cb8481] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [27695e2bb608bef86184e92f3c58f0ad30cb8481] - Code Rule Check OK.

**Comment by sijupunnnoose** [comment]
Why 2 commits?

**Comment by seinfra** [comment]
Target : [45e6adf193d414adb30f1dab8d7ac03a94a7ee6b] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [45e6adf193d414adb30f1dab8d7ac03a94a7ee6b] - Code Rule Check OK.

**Comment by sunghan-chang** [comment]
@amogh-samsung Could you modify commit title instead of PR title? PR title is not important, commit title is important.

**Comment by seinfra** [comment]
Target : [5fec4f6a2b2a0b1cfcd3027143b6b64825e06860] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [5fec4f6a2b2a0b1cfcd3027143b6b64825e06860] - Code Rule Check OK.

**Pull request merged**
