### PR TITLE
Update HowtoInstallKconfigFrontend.md

### PR DESCRIPTION
**Pull request by ashanprasad**
Add steps to install nuttx package

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [ccd72cea0050c71a1fcc6756f4349e25adc4b57a] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [ccd72cea0050c71a1fcc6756f4349e25adc4b57a] - Code Rule Check (C++) OK.

**Comment by sunghan-chang** [comment]
@ashanprasad Thank you for contribution. But I don't know why this is needed.

**Comment by sunghan-chang** [comment]
@ashanprasad Here is no activity and we don't know the needs of this change. Let's clos this. Please reopen this when you think this is needed.

**Pull request closed without merging**
