### PR TITLE
travis: add imxrt1020/1050 board configurations

### PR DESCRIPTION
**Pull request by an4967**
- add imxrt1020/1050 board for build test.

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [f8f2e5df77d215e9cf3d730583203eba5aeb1523] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [f8f2e5df77d215e9cf3d730583203eba5aeb1523] - Code Rule Check OK.

**Comment by sunghan-chang** [comment]
When you use your PR description as a title, we can know what commit is clearly.
Let's use it.
```
travis: add imxrt1020/1050 board configurations
```

**Comment by an4967** [comment]
@sunghan-chang 
Thank you for your advice.  I updated new title.

**Comment by seinfra** [comment]
Target : [504b25faaaa7bc1a23ba911736054365fca603cb] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [504b25faaaa7bc1a23ba911736054365fca603cb] - Code Rule Check OK.

**Pull request merged**
