### PR TITLE
examples/wifi_manager_sample: fix typo

### PR DESCRIPTION
**Pull request by sunghan-chang**
infomation -> information

Signed-off-by: sunghan-chang <sh924.chang@samsung.com>

### CODE REVIEW

**Review by Taejun-Kwon — APPROVED** [review]

**Review by jeongchanKim — DISMISSED** [review]
LGTM

**Comment by jeongchanKim** [comment]
Please check the coding rule also. : line 188.

**Review by jeongchanKim — APPROVED** [review]
LGTM

**Review by manoharahk — APPROVED** [review]

**Review by thapav — APPROVED** [review]
LGTM

**Review by Taejun-Kwon — APPROVED** [review]

**Pull request merged**
