### PR TITLE
framework/wifi_manager: Security type and phy mode management

### PR DESCRIPTION
**Pull request by SeonghoByeon**
- Add enterprise security types into wifi_manager and wifi_utils
- Modify phy_mode to denote the supported standard version

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [e695dffdfeed8030b0c76ea08a263159b956f3ec] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [e695dffdfeed8030b0c76ea08a263159b956f3ec] - Code Rule Check OK.

**Comment by sunghan-chang** [comment]
@SeonghoByeon New modification, new commit makes dummy commit on history. When you get changes from another repo, and they should be synced each other, then you should use cherry pick instead of making new commit.

**Comment by SeonghoByeon** [comment]
@sunghan-chang Thanks for the comment. In this case, there are lots of commits involved in the current unsynchronization, so the process of merge after porting each cherry-pick (step by step) is very complicated. Here, I tried to modify the code to avoid conflict with another repo as possible as I can, so please let me know if conflict occurs. Sorry for the delayed work for synchronization.

**Pull request merged**
