### PR TITLE
WISH: iotjs: Sync iotjs upstream in Tizen:RT

### PR DESCRIPTION
**Pull request by rzr**
I tried to upstream this file, but it wasn't merged,
(this is making sense since it's only for downstream)

For the record:
https://github.com/Samsung/iotjs/pull/1452

Relocating it outside it will make the module easy to update,
buy just replacing iotjs subtree with upstream tree.

For easier cooperation (tracking changes, logs etc)
then it can be also replaced by submodule,
like other deps in Tizen:RT.

Change-Id: If4a7d71d862745173f38d009924f3e4ce98cb6d0
Signed-off-by: Philippe Coval <philippe.coval@osg.samsung.com>

### CODE REVIEW

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by sunghan-chang** [comment]
@rzr First of all, thank you for contribution. But I don't agree your changes.
1. We think that easy maintain for Samsung is not a top priority to user (outside developer). I think Kconfig file of iotjs should be in iotjs folder. That is logically right, easy to understand and easy to find. Isn't it?
2. Your team said, you will not set iotjs as submodule. I asked your team this when your team made a pull request to merge iotjs into TizenRT. But you wrote a reason, submodule. What is final opinion?

**Comment by rzr** [comment]
I still think that importing iotjs tree as it without touching it could be convenient 
(actually I have done using scripts for demo purposes).

So to sum up  it gives us only 3 options:

1/ Have this kconfig in top tree of iotjs:
https://github.com/Samsung/iotjs/pull/1452

2/ Have it outside iotjs's tree:
https://github.com/Samsung/TizenRT/pull/1277

The other option I have not yet tried, 
is put the file in iotjs's tizenrt subdir,
and then update path in TizenRT when sourcing kconfig.

Any opinion welcome, actually I don't have any preference.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by sunghan-chang** [comment]
@rzr I am so sorry for delay.
I can't agree this change. As you said, how about move it into iotjs's tizenrt subdir?

**Comment by rzr** [comment]
Ok 3d option was approved by iotjs
So now It can be adapted Tizen:RT's side when iotjs is updated as mentioned in:
https://github.com/Samsung/iotjs/pull/1529#event-1512596889
{
Note that Tizen:RT's os/Kconfig.runtime will need to be updated
from "external/iotjs/Kconfig.runtime" (downstream's location)
to "external/iotjs/config/tizenrt/Kconfig.runtime" (upstream's location)
from this patch.
}

Now, Tizen:RT's side, if it helps for testing purposes, 
I can try to sync/import iotjs periodically in a branch
until it's the right time to update.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by sunghan-chang** [comment]
@rzr
Thank you for contribution on both. Could you merge two commits through ```git rebase -i HEAD~2```?

**Comment by seinfra** [comment]
Code Rule Check OK.

**Pull request merged**
