### PR TITLE
os/board/rtl8730e: Sync to 8.3c SDK

### PR DESCRIPTION
**Pull request by yeetee179**

### CODE REVIEW

**Review by sunghan-chang — COMMENTED** [review]
Any release note we can check?

**Comment by yeetee179** [comment]
> 

WiFi specific:
	Bug fixes for WiFi stability
	Enable WiFi high throughput
	Adjust WiFi power by rate for Samsung

Others: Synchronise code for Peripheral, BLE, WiFi based on 8.3c SDK

**Comment by sunghan-chang** [comment]
@yeetee179 Could you leave them in the commit description? And one small question. This is the PR of 8.3c SDK. What does it mean `Synchronise code for Peripheral, BLE, WiFi based on 8.3c SDK`? If you release it some anywhere, are you able to leave a link for 8.3c SDK release note?

**Comment by yeetee179** [comment]
@sunghan-chang I have amended the commit message as requested.
The new code base is version 8.3c, however currently for TizenRT it is based on 8.2b.
So a sync is needed to update the relevant code changes.

For Peripheral section, it contains the following fixes:
- Serial related fixes, general minor fixes and renaming conventions.
For BLE, it contains the following fixes:
Fixes for GATT structure type and general fixes.

**Review by sunghan-chang — APPROVED** [review]

**Pull request merged**
