### PR TITLE
apps/example/testcase/ : removed unsupported Macro SO_REUSEPORT

### PR DESCRIPTION
**Pull request by manoj11588612**
Changes are as below:
itc_net_connect.c     -> 1. removed unsupported macro "SO_REUSEPORT"for setcockopt API

Signed-off-by: manoj <manoj.g2@samsung.com>

### CODE REVIEW

**Comment by manoj11588612** [comment]
@pillip8282 @sunghan-chang @samegautam @sangwon03

**Comment by seinfra** [comment]
Target : [fbd95fa4c1abf88de77ed4b6f00682a2bb1cb768] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [fbd95fa4c1abf88de77ed4b6f00682a2bb1cb768] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [fbd95fa4c1abf88de77ed4b6f00682a2bb1cb768] -

**Comment by sunghan-chang** [comment]
apps/example/testcase/ : removed unsupported Macro SO_REUSEPORT 
==>
testcase/network: remove unsupported macro SO_REUSEPORT

**Pull request merged**
