### PR TITLE
os/arch/arm/src/amebasmart/Kconfig: Turn on SPI1 smart by default

### PR DESCRIPTION
**Pull request by kaikaikaime**
Set SPI1 Smart Kconfig to default yes

### CODE REVIEW

**Review by sunghan-chang — COMMENTED** [review]
@kaikaikaime Sorry for miscommunication. What I asked is defconfig modification. Because CONFIG_AMEBASMART_SPI1 is not enabled in current defconfig, we can't use SPI1 now.

**Comment by Taejun-Kwon** [comment]
No we should use both of spi1 & spi0

**Comment by kaikaikaime** [comment]
Hi @sunghan-chang ,

I would like to confirm when you mention defconfig, do you meant only hello, or all the defconfig in smart?

Kai

**Comment by sunghan-chang** [comment]
@kaikaikaime all the defconfig in smart

**Pull request closed without merging**
