### PR TITLE
build/configs/imxrt1020, imxrt1050: Set proper LD scripts for build 

### PR DESCRIPTION
**Pull request by sangam-swami**
Set proper LD files for build in windows environment.

### CODE REVIEW

**Comment by sunghan-chang** [comment]
@sangam-swami @kishore-sn Could you confirm this PR does not make conflicts with #4354 ? Could you let me know that you want to merge now?

**Comment by sangam-swami** [comment]
> @sangam-swami @kishore-sn Could you confirm this PR does not make conflicts with #4354 ? Could you let me know that you want to merge now?

@sunghan-chang 
AUTOGEN_MEMORY_LDSCRIPT was removed in #4354, so I have reverted changes related to it. There will be no conflict with these PR's now.

**Comment by sunghan-chang** [comment]
@sangam-swami Let's merge this after #4354 .

**Comment by sunghan-chang** [comment]
@sangam-swami Could you resolve conflicts?

**Comment by sangam-swami** [comment]
> @sangam-swami Could you resolve conflicts?

@sunghan-chang resolved the conflicts

**Pull request merged**
