### PR TITLE
apps/examples/webserver_test: Fix keep-alive

### PR DESCRIPTION
**Pull request by hdotkashyap**
Fixed keep-alive to process all keep-alive responses by resetting read_finish

### CODE REVIEW

**Review by pillip8282 — DISMISSED** [review]
Could you describe issue scenario more in detail. I seems that read_finish is not updated after parse function. It’s easier to understand the PR if you describe the problem and how to reproduce the problem.

**Comment by hdotkashyap** [comment]
> Could you describe issue scenario more in detail. I seems that read_finish is not updated after parse function. It’s easier to understand the PR if you describe the problem and how to reproduce the problem.

Problem : In webserver_test, the variable **read_finish** becomes _True_ to signify parsing has finished. But when using webserver_test with **keep-alive** it becomes a problem as it does not parse the subsequent responses after the first keep-alive response since **read_finish** is already fixed to _True_.

How to reproduce : `webserver_test 1 GET http://127.0.0.1/ keep-alive=5`
This command will send 5 request in one keep-alive session but will parse only the first response.

 Fix : Inside the keep-alive for loop **read_finish** variable is reset to _False_ for every iteration.

**Comment by sunghan-chang** [comment]
@hdotkashyap Please check our [commit rules](https://github.com/Samsung/TizenRT/wiki/Documentations#commit-rules). Current commit is not acceptable.

**Comment by sunghan-chang** [comment]
> Problem : In webserver_test, the variable read_finish becomes True to signify parsing has finished. But when using webserver_test with keep-alive it becomes a problem as it does not parse the subsequent responses after the first keep-alive response since read_finish is already True.
>
> How to reproduce : webserver_test 1 GET http://127.0.0.1/ keep-alive=5
This command will send 5 GET requests in one keep-alive session but will parse only the first response and skip remaining 4 responses.
>
> Fix : Inside the keep-alive for loop read_finish variable is reset to False for every iteration.

Let's add above in commit descrition.

**Comment by hdotkashyap** [comment]
> > Problem : In webserver_test, the variable read_finish becomes True to signify parsing has finished. But when using webserver_test with keep-alive it becomes a problem as it does not parse the subsequent responses after the first keep-alive response since read_finish is already True.
> > How to reproduce : webserver_test 1 GET http://127.0.0.1/ keep-alive=5
> > This command will send 5 GET requests in one keep-alive session but will parse only the first response and skip remaining 4 responses.
> > Fix : Inside the keep-alive for loop read_finish variable is reset to False for every iteration.
> 
> Let's add above in commit descrition.

Done

**Review by pillip8282 — APPROVED** [review]
LGTM
Please check sunghan's comment. This commit violates commit rule of commit title.

**Comment by hdotkashyap** [comment]
> LGTM Please check sunghan's comment. This commit violates commit rule of commit title.

Done

**Review by thapav — APPROVED** [review]
May be title of commit could be something liek below:
apps/examples/webserver_test: Fix web server keep-alive test scenario.

**Comment by vibhor-m** [comment]
Code changes looks fine. Please change commit title as suggested by other dev.

**Comment by amitpurwar** [comment]
LGTM

**Comment by hdotkashyap** [comment]
> May be title of commit could be something liek below: apps/examples/webserver_test: Fix web server keep-alive test scenario.

Done

**Review by PritamV — COMMENTED** [review]
for (int i = 0; i < param->keep_alive_count; i++) 
Just to cross check, variable i should get started from 0 or 1.

**Comment by hdotkashyap** [comment]
> for (int i = 0; i < param->keep_alive_count; i++) Just to cross check, variable i should get started from 0 or 1.

default value for keep_alive_count is 1, so even if keep-alive is OFF loop needs to run 1 iteration..... for that i starts from 0

**Comment by lkasana** [comment]
Looks good to me

**Review by pillip8282 — APPROVED** [review]
LGTM

**Review by sangwon03 — APPROVED** [review]
LGTM

**Pull request merged**
