### PR TITLE
build/tools/amebasmart: Fix PM short press reset not working

### PR DESCRIPTION
**Pull request by ZhenBei-Sin**
Change Notes:
1. Refactor the KM4 sleep type logic with replace the condition check based on the AP ON or RUNNING.
2. Remove the pmu_set_sleep_type calls, as they could be causing the sleep type to be incorrectly set.

### CODE REVIEW

**Comment by ZhenBei-Sin** [comment]
Hi @sunghan-chang  & @ewoodev 

The discussion at the PR#6489 build/tools/amebasmart: Update pmc code for sleep type 
After investigation and testing by Dane, the short press reset is now working on product code.
You can get the updated test status from Dane.

Thank You.

**Review by jeongarmy — COMMENTED** [review]
LGTM

**Review by linuxias — COMMENTED** [review]
LGTM.

**Review by ewoodev — APPROVED** [review]

**Review by jeongarmy — APPROVED** [review]
lgtm

**Pull request merged**
