### PR TITLE
[Do Not Merge] build/configs/rtl8730e: Shift CA32 .text to XIP

### PR DESCRIPTION
**Pull request by ZhenBei-Sin**
Changes Note:
Free up 7M
CA32 ATF Secure image size reduced to 800KB
KM4 PSRAM allocated size 242KB

* This PR just use for debug the issue - Loadableapps 16M boot failed.

### CODE REVIEW

**Comment by ZhenBei-Sin** [comment]
Hang on Loadableapps Boot Log:
image

**Comment by ZhenBei-Sin** [comment]
chip.h 
image

image

# define AMEBASMART_DRAM_SIZE (7*1024*1024) /* Size of the PSRAM for BL33 (7mb) */
CA32_BL3_DRAM_NS (rwx) :                ORIGIN = 0x60300000, LENGTH = 0x60A00000 - 0x60300000           /* CA32 BL3 DRAM NS: 7MB */

**Comment by jwei5** [comment]
[data_abort_test_patch.zip](https://github.com/Samsung/TizenRT/files/13873321/data_abort_test_patch.zip)
Test patch for data abort fault

**Comment by jwei5** [comment]
[km4_242k_ipc_dev_log.zip](https://github.com/Samsung/TizenRT/files/13885685/km4_242k_ipc_dev_log.zip)
KM4 test image with some IPC logs enabled

**Comment by sunghan-chang** [comment]
@ZhenBei-Sin This looks duplicated with PR #6026 . If yes, let's close this.

**Pull request closed without merging**
