### PR TITLE
Adding Cy4390x board libraries, config, example code

### PR DESCRIPTION
**Pull request by CypressHJ**

### CODE REVIEW

**Comment by seinfra** [comment]
Code Rule Check Result:
apps/examples/wifi_manager_sample/wm_test.c:349: ERROR: [SPC_M_KWD] space required before the open brace '{'
apps/examples/wifi_manager_sample/wm_test.c:349: ERROR: [SPC_M_KWD] space required before the open parenthesis '('

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by sunghan-chang** [comment]
@CypressHJ Thank you for contribution.
1. Please don't make additional commits to fix first commit of pull request.
When you find a problem on your commit which uploaded into PR, you should fix it inside itself using ```git commit --amend``` or ```git rebase xxxx```
2. As I mentioned before in mail, please don't mix differnt kinds of changes into one commit.
Please split adding bsp, adding example and adding configs.

**Comment by sunghan-chang** [comment]
Here is our commit rules. Please find it here.
https://github.com/Samsung/TizenRT/wiki/Documentations#commit-rules

**Comment by CypressHJ** [comment]
@sunghan-chang   thanks for your review. 

For #1,  Yes. understood the rule.  
For #2,  This is one package.  the libaries and config and example app should be needed for Cy4390x board compilation.  If one of them is missed, compile doesn't complete.  I think this commit is not different kind of changes.

BR, HJ Lee.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by sunghan-chang** [comment]
@CypressHJ Thank you for reply.
I absolutely agree that they are a package to support a board.
But it should be 3 sub-commits. You don't need to make it single commit.
1. Add core (in your case, BSP)
2. Add examples to test added core
3. Add configs to build added core and example
I don't agree application, BSP and build configuration are same topic.

And someone can interest only core side, another can do only example side.
But if they are mixed into a commit, it makes him(or her) difficult to check by commit.

After merged all of module, when you need to fix something on core, you should fix core and example together. That makes sense. But not adding case.

@juitem @sangwon03 Could you share your opinion on splitting commit?

**Comment by CypressHJ** [comment]
@sunghan-chang  OK, Understood your guidance. 

This package is consist of 3 part what you said. and, I will seperate the pakage as your guidance. but, To more clear the purpose of libaries, this package will be seperated 4 part as below. 
If you have any concern or additional guidance, let me know. after my rework is completed, this P.R will be closed, then, I'm going to create a new one. thanks. 

1. Chip and board BSP Libarary.
     -  os/arch/arm/include/bcm4390x
     -  os/arch/arm/src/bcm4390x/
     -  os/arch/arm/src/cy4390x/

2.  Network and external device Libarary. 
     -  external/WICED/

3.  Build configuration of the CY4390x  board. 
     - build/configs/cy4390x/ 
     - os/net/lwip/src/api/sockets.c
     - os/arch/arm/src/armv7-r/Kconfig

4.  Example application of the CY4390x board. 
     - apps/examples/cy4390x_demo 

BR, HJ Lee.

**Pull request closed without merging**
