### PR TITLE
apps/utils/fs : remove mkrd and mksmartfs commands

### PR DESCRIPTION
**Pull request by KimDongEon**
remove commands that are not currently in use

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [b140bb12f66ad6345e871d71099d9f222d357f60] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [b140bb12f66ad6345e871d71099d9f222d357f60] - Code Rule Check (C++) OK.

**Comment by sunghan-chang** [comment]
@KimDongEon Could you let me know why do you think those are not used?

**Comment by KimDongEon** [comment]
@sunghan-chang 
mkrd -> I think mkrd is not used after tmpfs is introduced.
mksmartfs -> mksmartfs is not used by fscmd because it is used for mounting at boot time.

I have consulted with TaeJun-Kwon.

**Comment by seinfra** [comment]
Target : [999de89a354739ff0c96dda2bf513033cdc84a2a] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [999de89a354739ff0c96dda2bf513033cdc84a2a] - Code Rule Check OK.

**Pull request merged**
