### PR TITLE
build/tools/amebasmart/image_tool: Unblock download for 16M only board

### PR DESCRIPTION
**Pull request by jiangxiaoyunjoy**
When implementing the package type display feature, only Type1(32+64MB) and Type2(32+64MB) can proceed download if passing the flash size check. This version of tool add Type0(16MB inetrnal flash), and won't pause the download.

download log in previous version:
Internal flash size: 16 MBerror:  + no matched external flash!

Check flash size         ......    Fail

download log in current version:
Internal flash size: 16 MB + no matched external flash! --> Package 0:internal only.
Check flash size         ......    OK

### CODE REVIEW

**Comment by sunghan-chang** [comment]
@Tirtha-Samsung Could you check this?

**Comment by sunghan-chang** [comment]
@jiangxiaoyunjoy Does this PR include 16MB checking only? I heard this includes a fix of abnormal erase operation for external in Linux. But that was resolved in PR #6353 in Windows. Please write details in the description. I can't get what is fixed in the PR.. That's why I left several comments on PR 6353.

**Comment by jiangxiaoyunjoy** [comment]
> @jiangxiaoyunjoy Does this PR include 16MB checking only? I heard this includes a fix of abnormal erase operation for external in Linux. But that was resolved in PR #6353 in Windows. Please write details in the description. I can't get what is fixed in the PR.. That's why I left several comments on PR 6353.

Hi @sunghan-chang ,
3 issues need to be fixed with the 8730e download tool recently.
1. Issue : Resource download problem
Root cause : the external flash is erased with the wrong partition in the previous version, as the offset conversion for the external flash was not handled properly, this will cause image download wrongly for DDR package.
Reproduce flow: The current TizenRT cannot reproduce the issue, please proceed to Eric to know more details. 
Solution : modify the bugs at offset in the flashloader
Changes: build/tools/amebasmart/image_tool/floader_rtl8730e.bin

2. Issue : Not able to download with 16M only board
Root cause : When implementing the package type display feature, only Type1(32+64MB) and Type2(32+64MB) can proceed to download if passing the flash size check.
Reproduce flow: Run the download in the current TizenRT, and the download logs are changed:
download log in previous version:
Internal flash size: 16 MBerror: + no matched external flash!
Check flash size ...... Fail
download log in current version:
Internal flash size: 16 MB + no matched external flash! --> Package 0:internal only.
Check flash size ...... OK cannot reproduce the issue, please proceed to Eric to know more details. 
Solution : add Type0(16MB inetrnal flash), and won't pause the download if Type0 detected.
Changes: build/tools/amebasmart/image_tool/upload_image_tool_linux

3. Issue : CRC error when downloading to external flash
Root cause : the CRC calculation in the external flash is wrong when running some corner cases, in the previous version, CRC error will be printed if skip ext_data image and download resource image.
Reproduce flow: 
image
Solution : fix the CRC calculation formula in the flashloader
Changes: build/tools/amebasmart/image_tool/floader_rtl8730e.bin
Remarks: this issue is reproduced on Windows ImageTool, Linux version cannot reproduce it as it didn't hit the corner case, but better to sync to the same tool version as Windows

Please have a check on the notes above, if there is no problem, let me combine them and create a new PR, which will all 3 fixes.

Thank you~

**Comment by ZhenBei-Sin** [comment]
Hi @sunghan-chang 

Please review the commit message below.
_________________________________________________________________________________________________
build/tools/amebasmart/image_tool: Add Support for Download [Package0] 16MB Flash

Available package
[Package0] 16MB Flash + 8MB PSRAM
[Package1] 16MB Flash + 8MB PSRAM + 32MB Ext-Flash
[Package2] 32MB Flash + 64MB DDR2 + 64MB Ext-Flash

**Issue**: Fail to download the image to Package0 via Linux Download script
[Error Log]
Internal flash size: 16 MB	error:  + no matched external flash!
Check flash size	......	Fail

**Solution**: Remove the blocking download for [Package0]
[Success Log]
Internal flash size: 16 MB + no matched external flash! --> Package 0:internal only.
Check flash size	......	OK
_________________________________________________________________________________________________

######
This issue can be easily reproduced using the HW: [Package0] with 16MB Flash + 8MB PSRAM by performing a download via the Linux Download Script.
Using this PR's upload_image_tool_linux.exe allows the download to be performed successfully.
######

**Comment by sunghan-chang** [comment]
@jiangxiaoyunjoy If we merge the PR #6353 , no more issue1 with Windows and Linux tools both?

**Comment by sunghan-chang** [comment]
> Hi @sunghan-chang
> 
> Please review the commit message below.
> 
> build/tools/amebasmart/image_tool: Add Support for Download [Package0] 16MB Flash + 8MB PSRAM
> 
> Available package [Package0] 16MB Flash + 8MB PSRAM [Package1] 16MB Flash + 8MB PSRAM + 32MB Ext-Flash [Package2] 32MB Flash + 64MB DDR2 + 64MB Ext-Flash
> 
> **Issue**: Fail to download the image to Package0 via Linux Download script [Error Log] Internal flash size: 16 MB error: + no matched external flash! Check flash size ...... Fail
> 
> **Solution**: Remove the blocking download for [Package0] [Success Log] Internal flash size: 16 MB + no matched external flash! --> Package 0:internal only. Check flash size ...... OK
> 
> This issue can be easily reproduced using the HW: [Package0] with 16MB Flash + 8MB PSRAM by performing a download via the Linux Download Script. Using this PR's upload_image_tool_linux.exe allows the download to be performed successfully.

Description above is for this PR? Why is it failed with package 0 before? Because previous tool checks external flash always?

**Comment by ZhenBei-Sin** [comment]
> > Hi @sunghan-chang
> > Please review the commit message below.
> > build/tools/amebasmart/image_tool: Add Support for Download [Package0] 16MB Flash + 8MB PSRAM
> > Available package [Package0] 16MB Flash + 8MB PSRAM [Package1] 16MB Flash + 8MB PSRAM + 32MB Ext-Flash [Package2] 32MB Flash + 64MB DDR2 + 64MB Ext-Flash
> > **Issue**: Fail to download the image to Package0 via Linux Download script [Error Log] Internal flash size: 16 MB error: + no matched external flash! Check flash size ...... Fail
> > **Solution**: Remove the blocking download for [Package0] [Success Log] Internal flash size: 16 MB + no matched external flash! --> Package 0:internal only. Check flash size ...... OK
> > This issue can be easily reproduced using the HW: [Package0] with 16MB Flash + 8MB PSRAM by performing a download via the Linux Download Script. Using this PR's upload_image_tool_linux.exe allows the download to be performed successfully.
> 
> Description above is for this PR? Why is it failed with package 0 before? Because previous tool checks external flash always?

Yes, my description only for this PR. 
The issues failed download for Package 0 started with the introduction of the DDR package. 
It is due to the lack of consideration for the current available packages, especially Package 0, led to the tool continuously checking for the presence of the external flash.

**Comment by sunghan-chang** [comment]
@ZhenBei-Sin Could you write this in the description?

**Comment by ZhenBei-Sin** [comment]
Hi @sunghan-chang 
Please review the latest description. If this description is acceptable and clear, we will update the PR commit message accordingly.

_________________________________________________________________________________________________________________
build/tools/amebasmart/image_tool: Add Support for Download [Package0] 16MB Flash + 8MB PSRAM

Available package
[Package0] 16MB Flash + 8MB PSRAM
[Package1] 16MB Flash + 8MB PSRAM + 32MB Ext-Flash
[Package2] 32MB Flash + 64MB DDR2 + 64MB Ext-Flash

**Issue**: Fail to download the image to Package0 via Linux Download script
[Error Log]
Internal flash size: 16 MB error: + no matched external flash!
Check flash size ...... Fail

**Root Cause**: The lack of consideration for the current available packages, especially Package 0, led to the tool continuously checking for the presence of external flash.

**Solution**: Remove the check for external flash for [Package0] and allow the download without blocking.
[Success Log]
Internal flash size: 16 MB + no matched external flash! --> Package 0:internal only.
Check flash size ...... OK
_________________________________________________________________________________________________________________

**Comment by jiangxiaoyunjoy** [comment]
> @jiangxiaoyunjoy If we merge the PR #6353 , no more issue1 with Windows and Linux tools both?

Hi @sunghan-chang
Yes, if we merge the PR #6353 , no more issue1 with Windows and Linux tools.
Would you like me to add the fix of issue 3 to the PR #6353? Both issues need to update the same file(floader_rtl8730e.bin).

Thank you~

**Comment by sunghan-chang** [comment]
> > @jiangxiaoyunjoy If we merge the PR #6353 , no more issue1 with Windows and Linux tools both?
> 
> Hi @sunghan-chang Yes, if we merge the PR #6353 , no more issue1 with Windows and Linux tools. Would you like me to add the fix of issue 3 to the PR #6353? Both issues need to update the same file(floader_rtl8730e.bin).
> 
> Thank you~

Anything is ok. I just want to leave exact description in the commit.

**Comment by ZhenBei-Sin** [comment]
Hi @sunghan-chang ,

Commit message was updated. 
This PR fixes was independent and not affected by the other two issues.
May proceed to merge this PR upload_image_tool_linux.exe

JiangYun will submit another new PR fixes for the other two issues.
Issue 1: Resource download problem 
Issue 3: CRC error when downloading to external flash
The changes on floader_rtl8730e.bin.

Thank You :)

**Review by jylee9613 — APPROVED** [review]

**Review by jeongarmy — APPROVED** [review]
LGTM

**Pull request merged**
