### PR TITLE
fixed issues found while building on windows

### PR DESCRIPTION
**Pull request by bhupathiranjith**
fixed issues found while building on windows

### CODE REVIEW

**Comment by seinfra** [comment]
Code Rule Check Result:
os/tools/configure.c:423: ERROR: [SPC_M_OPR] space required after that ',' (ctx:VxV)
os/tools/configure.c:423: ERROR: [SPC_M_OPR] space required after that ',' (ctx:VxV)
os/tools/configure.c:431: ERROR: [SPC_M_OPR] space required after that ',' (ctx:VxV)

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by sunghan-chang** [comment]
@bhupathiranjith
1. Could you merge your two commits? Because your new changes make violations.
2. Could you fill details in commit description?
3. Don't use past tense at commit title.

**Comment by seinfra** [comment]
Target : [276316941e39465927ea728470fc10a41c61a436] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [276316941e39465927ea728470fc10a41c61a436] -

**Comment by seinfra** [comment]
Target : [276316941e39465927ea728470fc10a41c61a436] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [276316941e39465927ea728470fc10a41c61a436] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [276316941e39465927ea728470fc10a41c61a436] - Code Rule Check (C++) OK.

**Pull request merged**
