### PR TITLE
config/imxrt1020-evk, imxrt1050-evk: Add cxxtest config in flat build

### PR DESCRIPTION
**Pull request by sangam-swami**
Add cxxtest config for checking c++ test use cases in flat build.

Signed-off-by: Sangamanatha <sangam.swami@samsung.com>

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [054f9b6d371e01159d493d13b2b6287474174d75] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [054f9b6d371e01159d493d13b2b6287474174d75] - Code Rule Check OK.

**Comment by sunghan-chang** [comment]
@sangam-swami I don't think both helloxx and cxxtest are necessary. Let's select one.

**Comment by sangam-swami** [comment]
> @sangam-swami I don't think both helloxx and cxxtest are necessary. Let's select one.

@sunghan-chang how about merging cxxtest to helloxx config ? because cxxtest has many test cases important for c++ verification

**Comment by sunghan-chang** [comment]
@sangam-swami In my opinion, we can put c++ tcs in tc defconfig and keep helloxx only,

**Comment by sunghan-chang** [comment]
@sangam-swami Could you update this?

**Comment by sangam-swami** [comment]
> @sangam-swami Could you update this?

@sunghan-chang I will add cxxtest cases in tc config for cpp when enabled.
I keep keep this patch for hold till then, or I can drop this PR

**Comment by sunghan-chang** [comment]
@sangam-swami Whatever you want is ok to me. Just to know your plan, I left a comment.

**Comment by sunghan-chang** [comment]
> @sunghan-chang I will add cxxtest cases in tc config for cpp when enabled.
> I keep keep this patch for hold till then, or I can drop this PR

Could you let me know the ETA?

**Comment by sunghan-chang** [comment]
@sangam-swami Let's close this now.

**Pull request closed without merging**
