### PR TITLE
build/tools/amebasmart/gnu_utility: fix broken log issue

### PR DESCRIPTION
**Pull request by zhongnuo-tang**
1. log might be broken if there is a switch in clock during sleep and wakeup flow
2. remove the switching of clock during pre-post sleep for LOGUART bps 115200.
3. if LOGUART bps 115200 is used, clock will be switch to OSC during boot up, and not during pre-post sleep.

### CODE REVIEW

**Review by sunghan-chang — COMMENTED** [review]
Let's keep 644 for the files

**Review by sunghan-chang — COMMENTED** [review]
It looks this misses https://github.com/Samsung/TizenRT/commit/1ef39dc77ffa9f0c270ee426b93f1616ad10646c. Could you check this was made based on the latest?
@jwei5 Could you check it together?

**Comment by zhongnuo-tang** [comment]
> It looks this misses [1ef39dc](https://github.com/Samsung/TizenRT/commit/1ef39dc77ffa9f0c270ee426b93f1616ad10646c). Could you check this was made based on the latest? @jwei5 Could you check it together?

Sorry, it didnt include the latest, let me update again

**Comment by sunghan-chang** [comment]
> Let's keep 644 for the files

@zhongnuo-tang This is not applied yet for all.

And could you leave what log is broken? and how did you verify your PR? and test result?

**Review by ewoodev — COMMENTED** [review]
Please rebase this PR

**Comment by zhongnuo-tang** [comment]
> > Let's keep 644 for the files
> 
> @zhongnuo-tang This is not applied yet for all.
> 
> And could you leave what log is broken? and how did you verify your PR? and test result?

Hi @sunghan-chang 
Test results as follow

before this PR: log is broken during sleep-wakeup flow if ctrl v is pressed down for a long time
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890������23456789012
TASH: length of input character is too long, maximum length is 128
TASH>>34CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
12345678901234561234CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890
TASH: length of input character is too long, maximum length is 128
TASH>>123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123���34CA32PG-KM4PG-Wakeup : UART LO

After this PR: broken log is fixed, no broken log observed
TASH: length of input character is too long, maximum length is 128
TASH>>CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456
TASH: length of input character is too long, maximum length is 128
TASH>>CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456
TASH: length of input character is too long, maximum length is 128
TASH>>CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456
TASH: length of input character is too long, maximum length is 128
TASH>>CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456
TASH: length of input character is too long, maximum length is 128
TASH>>CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456
TASH: length of input character is too long, maximum length is 128
TASH>>CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456
TASH: length of input character is too long, maximum length is 128
TASH>>CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-Wakeup : UART LOG
1234567890123456CA32PG-KM4PG-

**Pull request merged**
