### PR TITLE
system/utils: Refactor implementation of 'echo'

### PR DESCRIPTION
**Pull request by lokeshbv**
This patch fixes the wrong logic of writing into a file using 'echo' command.

Signed-off-by: Lokesh B V <lokesh.bv@partner.samsung.com>

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [8ba74ccc4e1e96ee3e43ae7592e2800eeab4ee7a] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [8ba74ccc4e1e96ee3e43ae7592e2800eeab4ee7a] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [0c3417beb7cc646b182f53e24076b58a08d64334] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [0c3417beb7cc646b182f53e24076b58a08d64334] - Code Rule Check Result:
apps/system/utils/fscmd.c:217: ERROR: [SPC_M_SEP] space prohibited before that close parenthesis ')'
apps/system/utils/fscmd.c:236: ERROR: [SPC_M_KWD] space required before the open parenthesis '('

**Comment by sunghan-chang** [comment]
@lokeshbv Please check CRC results.

**Comment by seinfra** [comment]
Target : [55692a07849c8ba5b008aaf49f86e6f6383c3b3a] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [55692a07849c8ba5b008aaf49f86e6f6383c3b3a] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [0b924875d8b9aeeb0c60889a8e76d43eae280afb] - Code Rule Check (C++) OK.

**Pull request merged**
