### PR TITLE
build/configs/rtl8730e: Fix flash partition mismatch issue caused by PR#6220

### PR DESCRIPTION
**Pull request by edwakuwaku**
- The partition size is swapped between app1 and common, but the part name is not updated, which is causing bootup failure.

### CODE REVIEW

**Review by sunghan-chang — COMMENTED** [review]
How about changing the title to `fix commit xx` or `fixup! <the commit title which causes the problem`?

**Comment by Tirtha-Samsung** [comment]
with this commit, public loadable_ext is booting well
```
binary_manager_load_binary: Load success! [Name: app1] ersionSystem Information:
 [Text start : 0x0e6ac030] [Compressed Binary]
                Platform: 3.1   Binary: 200204
        Commit Hash: 1634949
        Build User: ot@=
        Build Time: 2024-07-10 10:24:46 IST
        System Time: 10ul 2024, 00:00:02 [s] UTC Hardware RTC Support
TASH>>This is WIFI App

Select Test Scenario.
        -Press X or x :erminate Tests.
Invalid Scenario.

Select Test Scenario.
        -Press X or x : Terminate Tests.

TASH>>Test will be finished.

TASH>>
TASH>>help
         TASH command list 
         --------------------
cat            cd               clear            date             
df             dhcpd            echo             exit             
format         free             heapinfo         hello            
hloxx          help             history          ifconfig         
ifdown           ifup             lcd_test                        
mem_leak         mkdir            mount          mv               
net_stats        netdb            netmon           ping             
ping6            prodcfig       ps               pwd              
reboot         rm               rmdir            sleep            
umount           uptime           
TASH>>hello
TASH>>Hello, World!!

TASH>>
```

**Comment by edwakuwaku** [comment]
> How about changing the title to `fix commit xx` or `fixup! <the commit title which causes the problem`?

Sure, changed accordingly~

**Review by jeongarmy — APPROVED** [review]
lgtm

**Pull request merged**
