### PR TITLE
build/tools/amebasmart: Revise Secure Storage address

### PR DESCRIPTION
**Pull request by ZhenBei-Sin**
Changes Note:
The reserved of the ss was split equally to the end of Slot A and B of the SS address (28KB)
Update SE img with revised Secure Storage address
Update Secure Storage Example

### CODE REVIEW

**Review by sunghan-chang — COMMENTED** [review]
@ZhenBei-Sin We need this only for amebasmart, not for amebad. But it looks it works for both. Could you check it?
@jylee9613 Please check this with him.

**Comment by sunghan-chang** [comment]
@ZhenBei-Sin @jylee9613 told me this. You can ignore my previous comment.

**Review by jylee9613 — APPROVED** [review]
I confimed it works well in signing/non-signing board.

**Review by jeongarmy — APPROVED** [review]
LGTM

**Pull request merged**
