### PR TITLE
build/configs/artik053/tc: enable ITC testcase options

### PR DESCRIPTION
**Pull request by samegautam**
Descrptions : enable ITC testcase options for Arastorage and SystemI/O module

Signed-off-by: Sameer Gautam <sameer.g1@samsung.com>

### CODE REVIEW

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by sunghan-chang** [comment]
@samegautam @yc207-lee Third line is for description. That is a git rule so that you had better remove "Description:".
And this is not enough to run itcs automatically. Even if we merge this, those should be run by TASH manually. Do you want this?

**Comment by samegautam** [comment]
@sunghan-chang : Please review changes
1. "Description:" keyword has been removed
2. To enable option of  ITC testcase for arastorage module and SystemI/O module,  ITC testcase command "arastorage_itc / sysio_itc" would be execute on TASH manually.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by pradeepns85** [comment]
Can you please add this information in the actual commit message ? as of now you have mentioned that info only in this page.
To enable option of ITC testcase for arastorage module and SystemI/O module, ITC testcase command "arastorage_itc / sysio_itc" would be execute on TASH manually.

**Comment by samegautam** [comment]
@pradeepns85  : Please review updated commit message.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Pull request merged**
