### PR TITLE
IMXRT1020_EVK: Defconfig and download script changes

### PR DESCRIPTION
**Pull request by btheosam**
loadable_elf_apps/defconfig: Rename 'imxrt' partition name to 'userfs'
tc_protected/defconfig: Rename 'imxrt' partition name to 'userfs'
wifi_loadable/defconfig: Rename 'imxrt' partition name to 'userfs'
imxrt1020-evk_download.sh: Changes for confirmation of 'userfs' partition erase

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [0c248f8382b658abd9c0eceb3f739d5366c88241] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [0c248f8382b658abd9c0eceb3f739d5366c88241] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [8340a9bf8b070f65313c275617f006a53c71f551] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [8340a9bf8b070f65313c275617f006a53c71f551] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [a66b610488e819404579de52a1067e8dfc8f2155] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [a66b610488e819404579de52a1067e8dfc8f2155] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [bfe795d6879d3d427afb788046858c67ba4e49e1] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [bfe795d6879d3d427afb788046858c67ba4e49e1] - Code Rule Check (C++) OK.

**Comment by btheosam** [comment]
DEv tree got corrupted, hence cant work on top.

**Pull request closed without merging**
