### PR TITLE
apps/examples/smart/Makefile : fix a typo error.

### PR DESCRIPTION
**Pull request by BONGJJUICE**
line 63   sytem -> system

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [76b233fd45e2466ee527721afe55250dabcdb5a7] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [76b233fd45e2466ee527721afe55250dabcdb5a7] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [3716259b2cc264913cf05ff9166261fcf901397c] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [3716259b2cc264913cf05ff9166261fcf901397c] - Code Rule Check (C++) OK.

**Comment by davidfather** [comment]
Would you please re-commit this PR on 'typo_codingrule' branch instead?

**Pull request closed without merging**
