### PR TITLE
apps/st_things/blink : modify permission from 755 to 644.

### PR DESCRIPTION
**Pull request by YiHyunJin**
Due to issue Security, the authority should be 644.

### CODE REVIEW

**Comment by juitem** [comment]
would you please change the title?
"modify permission from 755 to 644"

**Comment by seinfra** [comment]
Target : [5ec62fb740682913378b12e6325c44ada6028580] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [5ec62fb740682913378b12e6325c44ada6028580] - Code Rule Check OK.

**Comment by YiHyunJin** [comment]
@juitem yes. i fixed

**Pull request merged**
