### PR TITLE
 media: Remove useless code in DataSource 

### PR DESCRIPTION
**Pull request by junmin-kim**

### CODE REVIEW

**Comment by junmin-kim** [comment]
@jsdosa Would you review this PR?

**Comment by seinfra** [comment]
Target : [73c3961f02c36aa2133e90f65cfb97891392b6e5] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [73c3961f02c36aa2133e90f65cfb97891392b6e5] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [0a92c77524ebe7a50e39e1b4052da2b292ecab30] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [0a92c77524ebe7a50e39e1b4052da2b292ecab30] - Code Rule Check (C++) OK.

**Pull request closed without merging**
