### PR TITLE
build/tools/amebad: Reduce km0 image size

### PR DESCRIPTION
**Pull request by jwei5**
- Reduce size of km0 image from commit c4b1ae4

### CODE REVIEW

**Comment by sunghan-chang** [comment]
@jwei5 28KB is reduced? Could you write reduced size in the `COMMIT` description?
And by this PR, what can we do? can we reduce the flash partition for bootloader?

**Comment by Dane-Kang** [comment]
@hk-gwak Please help to sync this issue with Mr.chang

**Comment by jwei5** [comment]
Hi @sunghan-chang ,sorry for the confusion, updated commit message to explain more about this PR

**Comment by hk-gwak** [comment]
@sunghan-chang  Currently binary size is overflowed by commit c4b1ae4. So I requested to reduce the binary size of commit c4b1ae4, the result is this commit.

**Review by hk-gwak — APPROVED** [review]
Confirmed reduced binary size. LGTM

**Pull request merged**
