### PR TITLE
framework/st_things: Remove unused "Stop SoftAP from Cloud" feature.

### PR DESCRIPTION
**Pull request by SenthilKumarGS**
Stop SoftAP request from ST Cloud (Through POST request) is neither used nor fully implemented.
So I am removing the code related to it.

Signed-off-by: Senthil Kumar G S <senthil.gs@samsung.com>

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [ebcf51514cbe7eb83e998d3bb5395e2da97e7490] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [ebcf51514cbe7eb83e998d3bb5395e2da97e7490] - Code Rule Check OK.

**Comment by SenthilKumarGS** [comment]
Hi Abhishek,

please confirm with stakeholders (@Hyunjun85, @juitem ) that its okay to remove this.
- Sure. There is an issue created to track this (https://github.com/Samsung/TizenRT/issues/2520).

is it possible to run static analysis tool / check compiler warnings to make sure no left over unused symbols exist ?
- Yes. That's possible. Currently doing the cleanup feature & sub-module wise...

**Comment by JeongJunSik** [comment]
please change the commit title ("removed" to "remove")
We do not use the past.

**Comment by SenthilKumarGS** [comment]
> please change the commit title ("removed" to "remove")
> We do not use the past.

Okay. I've changed the title.

**Comment by seinfra** [comment]
Target : [1c16e235d04bc9dc91b56a8cd0ec4e5c829c28dc] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [1c16e235d04bc9dc91b56a8cd0ec4e5c829c28dc] - Code Rule Check (C++) OK.

**Pull request merged**
