### PR TITLE
support flat build on imxrt10x0-evk loadable configurations

### PR DESCRIPTION
**Pull request by sunghan-chang**

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [1601d78b4f70f4e6a5f3145c979ed43c04ebef33] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [1601d78b4f70f4e6a5f3145c979ed43c04ebef33] - Code Rule Check OK.

**Comment by sunghan-chang** [comment]
@kishore-sn Could you review and merge this?

**Comment by seinfra** [comment]
Target : [853bf756b7a758a3c9d7b15d5fb363085a317b1a] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [853bf756b7a758a3c9d7b15d5fb363085a317b1a] - Code Rule Check OK.

**Pull request merged**
