### PR TITLE
tools/ramdump: Add callstack log parsing feature

### PR DESCRIPTION
**Pull request by junmin-kim**
This scripts catch addr from "[<addr>]" and run addr2line

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [74b862e52fab8e7c642d82ee225d09f0634a4f15] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [74b862e52fab8e7c642d82ee225d09f0634a4f15] - Code Rule Check OK.

**Comment by jsdosa** [comment]
very nice.
could you update the Guide~?

**Comment by seinfra** [comment]
Target : [1eb13c073e5ebfc203adefdb19a46e833324f654] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [1eb13c073e5ebfc203adefdb19a46e833324f654] - Code Rule Check OK.

**Pull request merged**
