### PR TITLE
framework/ble_manager: fix ble_manager bug

### PR DESCRIPTION
**Pull request by an4967**
- fix ble_manager bug
- fix build error

### CODE REVIEW

**Comment by thapav** [comment]
Kindly separate out the bug & build error into different commits

**Review by jeongchanKim — COMMENTED** [review]
Could you leave the build error logs in commit msg?

**Comment by an4967** [comment]
@jeongchanKim 
```
CC:  component/common/bluetooth/realtek/sdk/example/ble_central/ble_tizenrt_central_app_task.c
component/common/bluetooth/realtek/sdk/example/ble_central/ble_tizenrt_central_app_task.c: In function 'ble_tizenrt_central_app_task_deinit':
component/common/bluetooth/realtek/sdk/example/ble_central/ble_tizenrt_central_app_task.c:181:9: error: 'ble_tizenrt_write_sem' undeclared (first use in this function)
     if (ble_tizenrt_write_sem) {
         ^~~~~~~~~~~~~~~~~~~~~
component/common/bluetooth/realtek/sdk/example/ble_central/ble_tizenrt_central_app_task.c:181:9: note: each undeclared identifier is reported only once for each function it appears in
component/common/bluetooth/realtek/sdk/example/ble_central/ble_tizenrt_central_app_task.c:184:9: error: 'ble_tizenrt_write_no_rsp_sem' undeclared (first use in this function)
     if (ble_tizenrt_write_no_rsp_sem) {
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Review by pillip8282 — APPROVED** [review]
lgtm

**Pull request merged**
