### PR TITLE
os/binfmt: Change logging type for information msgs

### PR DESCRIPTION
**Pull request by kishore-sn**
Too many logs coming when berr logging type is enabled. So, change
unwanted information msgs from berr to binfo type.

Signed-off-by: Kishore S N <kishore.sn@samsung.com>

### CODE REVIEW

**Review by jeongchanKim — APPROVED** [review]
LGTM

**Review by sunghan-chang — APPROVED** [review]

**Comment by sunghan-chang** [comment]
I agree this PR. But I want to suggest few things for dump_module.
1. Let's merge printing loading infos into dump_module because of dupplication
   https://github.com/Samsung/TizenRT/blob/master/os/binfmt/binfmt_loadbinary.c#L224
2. Let's rename the function name because the function operation is printing
3. How about making as below?
```c
void dump_module(const struct binary_s *bin)
{
    elf_save_bin_section_addr(bin);
    print_loading_info(bin);  <--- need to change for proper name
}

**Comment by sunghan-chang** [comment]
Because my comment is not for this PR, let's merge this now.

**Comment by kishore-sn** [comment]
I could not reply yesterday as i was busy with the other issues. I will take up your suggestion when we perform refractoring of the loader code.

**Pull request merged**
