### PR TITLE
os/board/rtl8721csm: Fix build error for whitelist duplicate variable issue

### PR DESCRIPTION
**Pull request by ziyik**

### CODE REVIEW

**Review by jeongchanKim — COMMENTED** [review]
Could you leave the build error log in the commit msg?

**Comment by an4967** [comment]
@jeongchanKim 
In loadable build, an error occured like below.
```
LD: tinyara
/root/product/.tizenrt/os/arch/arm/src/board/libboard.a(ble_tizenrt_scatternet_app.o):(.bss.modify_whitelist_code+0x0): multiple definition of `modify_whitelist_code'
/root/product/.tizenrt/os/arch/arm/src/board/libboard.a(ble_tizenrt_client.o):(.data.modify_whitelist_code+0x0): first defined here
Makefile:203: recipe for target '../build/output/bin/tinyara.axf' failed
make[1]: Leaving directory '/root/product/.tizenrt/os/arch/arm/src'
make[1]: *** [../build/output/bin/tinyara.axf] Error 1
make: *** [pass2] Error 2
Makefile.unix:479: recipe for target 'pass2' failed
```

**Review by an4967 — APPROVED** [review]
LGTM

**Comment by jeongchanKim** [comment]
> @jeongchanKim In loadable build, an error occured like below.
> 
> ```
> LD: tinyara
> /root/product/.tizenrt/os/arch/arm/src/board/libboard.a(ble_tizenrt_scatternet_app.o):(.bss.modify_whitelist_code+0x0): multiple definition of `modify_whitelist_code'
> /root/product/.tizenrt/os/arch/arm/src/board/libboard.a(ble_tizenrt_client.o):(.data.modify_whitelist_code+0x0): first defined here
> Makefile:203: recipe for target '../build/output/bin/tinyara.axf' failed
> make[1]: Leaving directory '/root/product/.tizenrt/os/arch/arm/src'
> make[1]: *** [../build/output/bin/tinyara.axf] Error 1
> make: *** [pass2] Error 2
> Makefile.unix:479: recipe for target 'pass2' failed
> ```

Thanks. Could you add this into the commit msg also?

**Review by davidfather — APPROVED** [review]
Looks good to me.

**Comment by ziyik** [comment]
> > @jeongchanKim In loadable build, an error occured like below.
> > ```
> > LD: tinyara
> > /root/product/.tizenrt/os/arch/arm/src/board/libboard.a(ble_tizenrt_scatternet_app.o):(.bss.modify_whitelist_code+0x0): multiple definition of `modify_whitelist_code'
> > /root/product/.tizenrt/os/arch/arm/src/board/libboard.a(ble_tizenrt_client.o):(.data.modify_whitelist_code+0x0): first defined here
> > Makefile:203: recipe for target '../build/output/bin/tinyara.axf' failed
> > make[1]: Leaving directory '/root/product/.tizenrt/os/arch/arm/src'
> > make[1]: *** [../build/output/bin/tinyara.axf] Error 1
> > make: *** [pass2] Error 2
> > Makefile.unix:479: recipe for target 'pass2' failed
> > ```
> 
> Thanks. Could you add this into the commit msg also?

Done added the build error log in commit message

**Review by an4967 — APPROVED** [review]
LGTM

**Pull request merged**
