### PR TITLE
build/tools/amebalite/gnu_utility: Fix UDP issue during Easy Setup

### PR DESCRIPTION
**Pull request by jwei5**
* Update KR4 image to fix UDP issue during Easy Setup

### CODE REVIEW

**Review by sunghan-chang — COMMENTED** [review]
Could you revert a file permission to 644?

**Comment by sunghan-chang** [comment]
@jwei5 Could you let us know the reason and the solution of the issue?

**Comment by jwei5** [comment]
@sunghan-chang The issue is due to our driver not resetting the baseband after setting channel. This causes the RX to hang, resulting in this issue. We have fixed this by resetting the baseband after setting channel.

**Review by sunghan-chang — APPROVED** [review]

**Comment by sunghan-chang** [comment]
@j11591 Could you review and merge this?
```
The issue is due to our driver not resetting the baseband after setting channel(when starting SoftAP). This causes the RX to hang, resulting in this issue. We have fixed this by resetting the baseband after setting channel.
```

**Review by j11591 — APPROVED** [review]
LGTM

**Pull request merged**
