### PR TITLE
ta_tc/media: Add FileInputDataSource positive utc

### PR DESCRIPTION
**Pull request by junmin-kim**
Below utc are included:
utc_media_FileInputDataSource_getChannels_p(),
utc_media_FileInputDataSource_getSampleRate_p(),
utc_media_FileInputDataSource_getPcmFormat_p(),
utc_media_FileInputDataSource_setChannels_p(),
utc_media_FileInputDataSource_setSampleRate_p(),
utc_media_FileInputDataSource_setPcmFormat_p(),
utc_media_FileInputDataSource_open_p(),
utc_media_FileInputDataSource_close_p(),
utc_media_FileInputDataSource_isPrepare_p(),
utc_media_FileInputDataSource_read_p(),
utc_media_FileInputDataSource_readAt_p(),

### CODE REVIEW

**Comment by junmin-kim** [comment]
I'll fix After https://github.com/Samsung/TizenRT/pull/1680 merged

**Comment by seinfra** [comment]
Target : [9b9f794104a15a6962c0f2bff03561a71223323c] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [9b9f794104a15a6962c0f2bff03561a71223323c] - Code Rule Check (C++) OK.

**Comment by junmin-kim** [comment]
@Taejun-Kwon Please review this PR

**Comment by seinfra** [comment]
Target : [878e0a81532d796c8637951d442ee21b9b88226a] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [878e0a81532d796c8637951d442ee21b9b88226a] - Code Rule Check OK.

**Pull request merged**
