### PR TITLE
apps/st_things : Fix the example in sample_light.

### PR DESCRIPTION
**Pull request by YiHyunJin**
Add the necessary parts when sample_light works.

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [e7901113d915f03cb1fa9a8375daf4d82cd240c9] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [e7901113d915f03cb1fa9a8375daf4d82cd240c9] - Code Rule Check OK.

**Comment by davidfather** [comment]
What kinds of nessary parts do you add?

**Comment by seinfra** [comment]
Target : [241234343e8f0c4fb930df7954223d8a8c882f7b] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [241234343e8f0c4fb930df7954223d8a8c882f7b] - Code Rule Check (C++) OK.

**Pull request merged**
