### PR TITLE
Bugfix 1050

### PR DESCRIPTION
**Pull request by btheosam**

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [5446a6a626715a41ddd7665400da735746f9d8ad] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [5446a6a626715a41ddd7665400da735746f9d8ad] - Code Rule Check OK.

**Comment by sunghan-chang** [comment]
@btheosam It is difficult to know where you modify from title.
```
configs/imxrt1050-evk/nxp_demo: pass the parameters on? at? with? download command
configs/imxrt1050-evk/nxp_demo: use userfs instead of imxrt for file system partition name
```

**Comment by btheosam** [comment]
This PR has to wait for other dependent changes. Hence deferred.

**Pull request closed without merging**
