### PR TITLE
external/stdk: update stdk HEAD to version 1.1.0 with migrated tizenrt-wrapper

### PR DESCRIPTION
**Pull request by bimanpaulsamsung**
1. Remove unused SSL fix patch
2. Move stdk HEAD to version 1.1.0
3. Define flag for openssl TizenRT support
4. Update Readme instruction

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [b39294cee241782885c6d1ba5055db19041918ea] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [b39294cee241782885c6d1ba5055db19041918ea] - Code Rule Check (C++) OK.

**Comment by dr-venkman** [comment]
Looks good to me.

**Comment by sunghan-chang** [comment]
@bimanpaulsamsung This has the same title with 4ec43f776f7e71234bc60748f64b35c731903f8c. Could you let us know the difference between them and show it in title?

**Comment by bimanpaulsamsung** [comment]
Patch with the same title(4ec43f7) as mentioned above had tizen-wrapper folder maintained in external/stdk folder of TizenRT.

Now, tizen-wrapper has been migrated to st-device-sdk-c repository.
This patch addresses the changes required for STDK Ver 1.1.0 with migrated changes.

**Background:**
There has been some file restructuring and API changes in STDK. With commit 6c09e44cc6a0e4cc7dd42bbfb4bf98076d87f99d, the folder tizen-wrapper has been moved to  st-device-sdk-c(https://github.com/SmartThingsCommunity/st-device-sdk-c). These changes has been done on top of STDK Ver 1.0.10.

Now onwards, all the changes related tizenrt-wrapper for STDK should be contributed to  st-device-sdk-c so that dual maintenance can be avoided in case of STDK changes.

This pull request updates the HEAD to STDK Ver 1.1.0 with migrated tizenrt-wrapper.

**Comment by sunghan-chang** [comment]
@bimanpaulsamsung Could you change the commit title? Because user uses the commit history instead of PR closed.

**Comment by seinfra** [comment]
Target : [94fbea68bc675365fe548da47d0d3963c4f2d1aa] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [94fbea68bc675365fe548da47d0d3963c4f2d1aa] - Code Rule Check OK.

**Comment by bimanpaulsamsung** [comment]
@sunghan-chang Title has been modified. Kindly review again.

**Pull request merged**
