### PR TITLE
Remove unnecessary compilation options, NXFLATs and files

### PR DESCRIPTION
**Pull request by sunghan-chang**
Makefile: remove NXFLAT compilation options 
configs/esp*/scripts: remove unnecessary Make.defs

### CODE REVIEW

**Comment by sunghan-chang** [comment]
@xiarihf I removed `NXFLAT` options and Make.defs from `build/configs/esp*/scripts` folder. If there is any usages of it, please let me know.

**Comment by seinfra** [comment]
Target : [9658df3adf259c7728015283696004e675df775d] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [9658df3adf259c7728015283696004e675df775d] - Code Rule Check (C++) OK.

**Comment by xiarihf** [comment]
@sunghan-chang 

Esp32 would not use it. We keep it because we see other part will use it.
Thanks for informing us.

**Comment by sunghan-chang** [comment]
@xiarihf 
> We keep it because we see other part will use it.

Could you let me know more details? What part? for what? And do you mean `NXFLAT`? or `Make.defs` in scripts folder?

**Comment by sunghan-chang** [comment]
@xiarihf Is it used to make a linker script output file?

**Comment by xiarihf** [comment]
> @xiarihf
> 
> > We keep it because we see other part will use it.
> 
> Could you let me know more details? What part? for what? And do you mean `NXFLAT`? or `Make.defs` in scripts folder?

I see you remove the places.
I have checked it, you can remove it in ESP32.

**Pull request merged**
