### PR TITLE
setjmp/setjmp-longjmp-test.c: add missing variables in function

### PR DESCRIPTION
**Pull request by hoon-e**
setjmp/setjmp_longjmp_test.c: add missing variables in function

add missing variables in function at line 144, 158.

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [712438a8e0492cc2af20f63769952623d506239c] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [712438a8e0492cc2af20f63769952623d506239c] - Code Rule Check OK.

**Comment by hoon-e** [comment]
Thank you!

**Comment by sunghan-chang** [comment]
@hoon-e I am so sorry for late reply. As you can see, here are many unnecessary commits. Could you rebase yours?

**Pull request merged**
