### PR TITLE
imxrt1050-evk/nxp_demo : update defconfig to fix build break

### PR DESCRIPTION
**Pull request by manoharahk**
imxrt1050-evk/nxp_demo configuration fails to build.
This patch updates configuration using make menuconfig.

Signed-off-by: Manohara HK <manohara.hk@samsung.com>

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [5c3cf4b478e8af587f08e465f14962fa83879fc5] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [5c3cf4b478e8af587f08e465f14962fa83879fc5] - Code Rule Check OK.

**Comment by sunghan-chang** [comment]
@manoharahk I checked and approved. But to avoid conflicts with #2741 , let's merge this after merging that.

**Comment by manoharahk** [comment]
After merging #2741 , #2739 might get conflict and may not be required also.

**Comment by sunghan-chang** [comment]
@manoharahk There is no build break now. Let's close this.

**Pull request closed without merging**
