### PR TITLE
examples/elf and mpu: remove dependency between them and tidyup

### PR DESCRIPTION
**Pull request by sunghan-chang**
1. examples/mpu: support a test of application access and tidyup 
2. configs/imxrt1050-evk/loadable_elf_apps: enable the mpu test example
3. examples/elf: modify names of built output file in .gitignore 
4. examples/elf: remove duplicated mpu test

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [a5589cece02641e424e390b37979d291687582fc] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [a5589cece02641e424e390b37979d291687582fc] - Code Rule Check (C++) OK.

**Comment by sunghan-chang** [comment]
@kishore-sn Could you merge this?

**Comment by seinfra** [comment]
Target : [1a21052a9644503445e31cd77c96ef6e50ae155f] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [1a21052a9644503445e31cd77c96ef6e50ae155f] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [cf24d05499b7e1fd8c46f09dec406fabab1280b3] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [cf24d05499b7e1fd8c46f09dec406fabab1280b3] - Code Rule Check (C++) OK.

**Comment by sunghan-chang** [comment]
@kishore-sn I removed the dependency between elf and mpu examples.
1. moving mpu test from wifiapp to mpu example
2. add prebuilt binaries to make it possible without elf enabled

**Pull request merged**
