### PR TITLE
os/drivers/wireless: Update RTK Wi-Fi driver library 

### PR DESCRIPTION
**Pull request by SeonghoByeon**
- Modify and apply LwIP initialization logic

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [545469ce0d90a5343ede03abc4744476fa8864db] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [545469ce0d90a5343ede03abc4744476fa8864db] - Code Rule Check OK.

**Comment by sunghan-chang** [comment]
@SeonghoByeon Why do you need 1st commit?

**Comment by SeonghoByeon** [comment]
> @SeonghoByeon Why do you need 1st commit?

There is a conflict in the librtl.a, when I just put in through the second commit.

Thanks for the comment.

**Comment by seinfra** [comment]
Target : [72dda0b8f464413c5de44954457c0dc3074f166c] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [72dda0b8f464413c5de44954457c0dc3074f166c] - Code Rule Check (C++) OK.

**Pull request merged**
