### PR TITLE
tests: systemio: fix makefile

### PR DESCRIPTION
**Pull request by ChinaTizenRT**
make systemio subtests: uart, i2c, spi, gpio, and pwm test independent.

Signed-off-by: tianfu.huang <tianfu.huang@samsung.com>

### CODE REVIEW

**Comment by sunghan-chang** [comment]
@ChinaTizenRT Thank you for contribution.
Could you write a commit title like below?
```
testcase/systemio: make systemio sub-tests independent

make systemio subtests: uart, i2c, spi, gpio, and pwm test independent.

Signed-off-by: tianfu.huang tianfu.huang@samsung.com
```

That is better to understand what you modify.

**Comment by seinfra** [comment]
Target : [b43c03245d8bde40967ed444347d4b2188fa047e] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [b43c03245d8bde40967ed444347d4b2188fa047e] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [2822c6897c0d14227eb300c9304fe01560d203c3] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [2822c6897c0d14227eb300c9304fe01560d203c3] - Code Rule Check OK.

**Comment by sunghan-chang** [comment]
@ChinaTizenRT By our [commit rule](https://github.com/Samsung/TizenRT/wiki/Documentations#commit-rules), we don't allow ```Merge branch 'master' of https://github.com/ChinaTizenRT/TizenRT```. You just remove or rebase it instead of merge.

**Comment by sunghan-chang** [comment]
You can remove it by ```git reset --hard HEAD^```.

**Comment by sunghan-chang** [comment]
If you meet conflict after executing above, let's do ```git rebase upstream/master```

**Comment by ChinaTizenRT** [comment]
closed this and make new PR  #2144.

**Pull request closed without merging**
