### PR TITLE
armv7-r: delete unused function, board_boot_result

### PR DESCRIPTION
**Pull request by JunhwanPark**
Delete unnecessary function calls.

Change-Id: I699a2b2809c9f4d6d87dba19d28f1a7083384d50
Signed-off-by: Junhwan Park <junhwan.park@samsung.com>

### CODE REVIEW

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by JunhwanPark** [comment]
The 'board_boot_result' function does not exist. If you enable 'CONFIG_BOOT_RESULT' in menuconfig, you will get a build error.

**Comment by sunghan-chang** [comment]
Could you write what you delete in commit title?
```
armv7-r: delete unused function, board_boot_result
```

**Comment by JunhwanPark** [comment]
OK. I will.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Pull request merged**
