### PR TITLE
typo errors

### PR DESCRIPTION
**Pull request by chaewon6**
line 190,192 : continuosely -> continuously

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [74d694a0cb9f3f1d43d23770189d643c921225bb] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [74d694a0cb9f3f1d43d23770189d643c921225bb] - Code Rule Check (C++) OK.

**Comment by sunghan-chang** [comment]
@chaewon6 Thank you for contribution. But both are wrong. `continuously` is correct, second `u` is missed. Could you change it again?
Additionally we have coding rules and we have to follow it to push our commit.
Let's use below for commit title and commit description.
```
examples/nettest: fix typo, continuously

continously -> continuously
```

**Comment by seinfra** [comment]
Target : [dabdc331c96c787fdabf812640df2fb5a1214c5c] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [dabdc331c96c787fdabf812640df2fb5a1214c5c] - Code Rule Check (C++) OK.

**Comment by chaewon6** [comment]
> line 190,192 : continuosely -> continuously

**Pull request closed without merging**
