### PR TITLE
os/board/rtl8721csm: update bt_normal_patch.c to fix delay issue

### PR DESCRIPTION
**Pull request by jiangxiaoyunjoy**

### CODE REVIEW

**Review by sunghan-chang — COMMENTED** [review]
Please keep 644 for file permission.

**Review by ydlee-sec — APPROVED** [review]
LGTM~

**Comment by sunghan-chang** [comment]
@ydlee-sec @jiangxiaoyunjoy .c file should be 644, not 755. Please revert it.

**Comment by ziyik** [comment]
> 

Should we raise a new PR to revert it?

**Comment by sunghan-chang** [comment]
@ziyik Yes, because this was merged already.

**Pull request merged**
