### PR TITLE
[TEMP] build/configs/rtl8730e: Add loadable configs for audio, lcd, pm & smp 

### PR DESCRIPTION
**Pull request by gSahitya-samsung**
This commit adds the lodable, loadable_audio, loadable_audio_lcd, loadable_lcd, loadable_pm and loadable_smp configuration for easy sync and testing.

### CODE REVIEW

**Comment by gSahitya-samsung** [comment]
To resolve build error in loadable_apps, please merge PR https://github.com/Samsung/TizenRT/pull/6294

**Comment by neel-samsung** [comment]
> This commit add separate loadable_apps_smp configration for PM + SMP Testing. It also disable SMP in loadable_apps by default for easy and proper sync.

So, there is ```loadable_ext``` defconfig, and it has pm + smp enabled by default. Don't you need to disable SMP there also? As we will have seperate config for smp now.

**Comment by sunghan-chang** [comment]
@r-prabu @kishore-sn We cleaned up the defconfigs few days ago. What's your plan for this? Is this necessary again?

**Comment by ewoodev** [comment]
> @r-prabu @kishore-sn We cleaned up the defconfigs few days ago. What's your plan for this? Is this necessary again?

Hello @sunghan-chang 

It is for sync  testing checking issue realtek and me about PM.
As our discussion, we will change defconfig name as below.

loadable
loadable_pm
loadable_smp
loadable_lcd
loadable_audio
loadable_audio_lcd

**Comment by sunghan-chang** [comment]
> > @r-prabu @kishore-sn We cleaned up the defconfigs few days ago. What's your plan for this? Is this necessary again?
> 
> Hello @sunghan-chang
> 
> It is for sync testing checking issue realtek and me about PM. As our discussion, we will change defconfig name as below.
> 
> loadable loadable_pm loadable_smp loadable_lcd loadable_audio loadable_audio_lcd

Do you mean this is a temporary PR? If yes, please mark some flag in the PR title.

**Comment by kishore-sn** [comment]
> mark some flag in the PR tit

Sorry, I dont understand. We dont support audio or lcd in public code. So how can we have these configs?

**Comment by sunghan-chang** [comment]
@gSahitya-samsung @r-prabu Could you let me know status of this? 
```
What Eunwoo said is that let's keep defconfigs as same as possible with same names.
```
When can we sync all defconfigs between public and internal?

**Comment by gSahitya-samsung** [comment]
> @gSahitya-samsung @r-prabu Could you let me know status of this?
> 
> ```
> What Eunwoo said is that let's keep defconfigs as same as possible with same names.
> ```
> 
> When can we sync all defconfigs between public and internal?

Currently we kept it on hold, because of other PM Tasks.

**Pull request closed without merging**
