### PR TITLE
iotjs: Add startup script for iotjs

### PR DESCRIPTION
**Pull request by rzr**
It has been tested on ARTIK055s's nettest image,
along a WPA2+AES AP.

Change-Id: I633ea759cacaab632b56a24ba7cb7e7b5debb5fb
Signed-off-by: Philippe Coval <p.coval@samsung.com>

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [e9e45004d24f0230d919abd2f1901ff48ca9efdf] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [e9e45004d24f0230d919abd2f1901ff48ca9efdf] - Code Rule Check Result:
apps/examples/startup/startup_main.c:57: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:57: ERROR: [SPC_M_OPR] space required after that ',' (ctx:VxV)
apps/examples/startup/startup_main.c:58: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:63: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:63: ERROR: [SPC_M_OPR] space required after that ',' (ctx:VxV)
apps/examples/startup/startup_main.c:64: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:65: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:66: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:70: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:71: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:72: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:73: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:74: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:79: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:79: ERROR: [SPC_M_OPR] space required after that ',' (ctx:VxV)
apps/examples/startup/startup_main.c:80: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:81: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:82: ERROR: [IDT_M_TAB] code indent should use tabs where possible
apps/examples/startup/startup_main.c:82: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:83: ERROR: [IDT_M_TAB] code indent should use tabs where possible
apps/examples/startup/startup_main.c:83: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:84: ERROR: [IDT_M_TAB] code indent should use tabs where possible
apps/examples/startup/startup_main.c:84: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:86: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:86: ERROR: [SPC_M_KWD] space required before the open parenthesis '('
apps/examples/startup/startup_main.c:87: ERROR: [IDT_M_TAB] code indent should use tabs where possible
apps/examples/startup/startup_main.c:87: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:88: ERROR: [IDT_M_TAB] code indent should use tabs where possible
apps/examples/startup/startup_main.c:88: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:89: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:91: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:92: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:94: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:95: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:96: ERROR: [IDT_M_TAB] code indent should use tabs where possible
apps/examples/startup/startup_main.c:96: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:97: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:98: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:99: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:100: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:101: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:102: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:103: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:104: ERROR: [IDT_M_TAB] code indent should use tabs where possible
apps/examples/startup/startup_main.c:104: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:105: ERROR: [IDT_M_TAB] code indent should use tabs where possible
apps/examples/startup/startup_main.c:105: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:106: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:107: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:108: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:109: ERROR: [IDT_M_TAB] code indent should use tabs where possible
apps/examples/startup/startup_main.c:109: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:110: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:120: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:121: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:122: ERROR: [IDT_M_TAB] code indent should use tabs where possible
apps/examples/startup/startup_main.c:122: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:123: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:126: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:128: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:130: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:130: ERROR: [SPC_M_KWD] space required before the open parenthesis '('
apps/examples/startup/startup_main.c:131: ERROR: [IDT_M_TAB] code indent should use tabs where possible
apps/examples/startup/startup_main.c:131: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:132: ERROR: [IDT_M_TAB] code indent should use tabs where possible
apps/examples/startup/startup_main.c:132: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:133: ERROR: [IDT_M_TAB] code indent should use tabs where possible
apps/examples/startup/startup_main.c:133: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:134: ERROR: [IDT_M_TAB] code indent should use tabs where possible
apps/examples/startup/startup_main.c:134: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:135: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/startup/startup_main.c:136: ERROR: [IDT_M_TAB] please, no spaces at the start of a line

**Comment by seinfra** [comment]
Target : [5827e17356e53aa45f09324ed9890cbfe40d954d] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [5827e17356e53aa45f09324ed9890cbfe40d954d] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [cfa075b9054dfe0a99828eccfeb868e715a01760] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [cfa075b9054dfe0a99828eccfeb868e715a01760] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [1110fa22927a0f93dfa9440c3291cbafc6c88c5d] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [1110fa22927a0f93dfa9440c3291cbafc6c88c5d] - Code Rule Check OK.

**Comment by sunghan-chang** [comment]
@rzr I am sorry for delay review. Could you let me know the purpose of this new example? startup is too common name so that I can't know what you want to say.

**Comment by rzr** [comment]
hi @sunghan-chang 

Purpose is very simple, I made this to execute an iotjs main program or service, once wifi is configured.

No problem to rename from startup , I was uninspired to find something more relevant, maybe startupiotjs ? or iotjslauncher ?, my hears are wide open.

For more about the context, I used this for creating WebOfThings devices built on Tizen:RT, 
see it in action at end of this video, until I explain more about this.

https://vimeo.com/279677314#web-of-things-agriculture-20180712rzr

**Comment by sunghan-chang** [comment]
@rzr Thank you for reply. iotjs_startup is better. Easily understandable name to know what it is is important.

**Comment by rzr** [comment]
Actually I had in mind to make something more generic to support alternate runtimes but this can be done later, I am ok with iotjs_startup, updated patch to come.

**Pull request merged**
