### PR TITLE
build/tools/amebad: Add km0_appliccation asm and map

### PR DESCRIPTION
**Pull request by ziyik**
- Added asm and map of km0_appliccation for reference

### CODE REVIEW

**Review by jeongchanKim — APPROVED** [review]
LGTM

**Comment by sunghan-chang** [comment]
@ziyik Could you let me know why this is necessary? To debug km0 bootloader?

**Comment by sunghan-chang** [comment]
@ziyik They should be synced with km0 bin file. Right?

**Comment by ziyik** [comment]
> @ziyik Could you let me know why this is necessary? To debug km0 bootloader?

This is nor for Bootloader, it is for km0_image2_all.bin.
Yes for debug purpose, in case hardfault location is in km0_image2_all.bin we can locate the hardfault location.

**Comment by ziyik** [comment]
> @ziyik They should be synced with km0 bin file. Right?

Yes, it is sync with km0_image2_all.bin, I use the same version as km0_image2_all.bin.
In my local I generate km0_image2_all.bin again to ensure it is same as current version, and used it asm and map.

**Review by sunghan-chang — APPROVED** [review]

**Pull request merged**
