### PR TITLE
external/openssl: add openssl library

### PR DESCRIPTION
**Pull request by SRCN-LiQin**
Add openssl library for stdk porting on tizenrt

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [5e95abdb59e5af7776b7de2d37c0f37c29dd4460] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [5e95abdb59e5af7776b7de2d37c0f37c29dd4460] - Code Rule Check OK.

**Comment by SRCN-LiQin** [comment]
> Please verify the dependency on mbedtls in Kconfig.

yes there is dependency on NET_SECURITY_TLS for openssl

**Comment by SeonghoByeon** [comment]
> > Please verify the dependency on mbedtls in Kconfig.
> 
> yes there is dependency on NET_SECURITY_TLS for openssl

Got it. Done.

**Comment by SRCN-LiQin** [comment]
> Here is a simple question. Why do you port both openssl based on mbedtls and sodium simultaneously?
> 
> Actually I found both sodium and openssl libs are used simultaneously depending on layer. Is it necessary?

As you known , the openssl here is a wrapper base on mbedtls for light implementation, and sodium is added to support ED25519 which is adopted by STDK, but this concrete variation of EdDSA  is not supported in mbedtls

**Pull request merged**
