### PR TITLE
testcase/wifi_manager, task_manager: change testcase function names t…

### PR DESCRIPTION
**Pull request by sunghan-chang**
…o remove '_' inside module name

The testcase naming rule is splitting topics by '_'. But wifi_manager and task_manager
have '_' inside module name. It causes wrong result of testcase parsing made by test verification lab.
Let's use "taskmanager" and "wifimanager".

Signed-off-by: sunghan-chang <sh924.chang@samsung.com>

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [0addab46dfb2df3948a2222853ab1b96e29b655c] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [0addab46dfb2df3948a2222853ab1b96e29b655c] - Code Rule Check OK.

**Comment by SeonghoByeon** [comment]
Hello @sunghan-chang,
What about unifying both **utc_wifi_manager_main** and **wifi_manager_utc** functions to **utc_wifimanager_main** and **wifimanager_utc** in utc_wifi_manager_main.c? (Also **utc_task_manager_main** in utc_task_manager_main.c) The TASH command also might be more natural with _wifimanager_utc_ than 'wifi_manager_utc' in this case. Please let me know your opinion.

**Comment by seinfra** [comment]
Target : [00fbdddc416450f8efffbef1d2d8e6ce0a903724] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [00fbdddc416450f8efffbef1d2d8e6ce0a903724] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [611636a54fd1f263b25e8c6e096c3478150cf6ae] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [611636a54fd1f263b25e8c6e096c3478150cf6ae] - Code Rule Check (C++) OK.

**Pull request merged**
