### PR TITLE
app/task_manager_sample : Fix typos in log

### PR DESCRIPTION
**Pull request by JeongJunSik**
- Fix typos in log (successfully)

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [7d8256b84b616798e4b1f79bbd9650cfdfc45921] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [7d8256b84b616798e4b1f79bbd9650cfdfc45921] - Code Rule Check (C++) OK.

**Comment by sunghan-chang** [comment]
As I noticed before, please push fixing typo & coding rule violations into `typo_codingrule` branch, not master.

**Comment by JeongJunSik** [comment]
Sorry for missing that information. 
I will make pull request again.

**Pull request closed without merging**
