### PR TITLE
lib/libxx/libxx_new.cxx : apply a coding style

### PR DESCRIPTION
**Pull request by NohYunah**
[M15] The open brace last on the line. The closing brace is empty on a line of its own.
line98 : open brace line miss
line107 : open brace line miss

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [d7dac4e0931bf216265405ed4d425db6f148da93] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [138fac520a54ad9fe529a13f5c0cf27828e41468] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [138fac520a54ad9fe529a13f5c0cf27828e41468] - Code Rule Check (C++) OK.

**Comment by davidfather** [comment]
Would you please re-commit this PR on 'typo_codingrule' branch instead?
In addition, before making your PRs, you need to prepare your own forked repo.
Please, refer to our contribution rules.

**Pull request closed without merging**
