### PR TITLE
 iotjs: Fix (re)connected status in callback

### PR DESCRIPTION
**Pull request by rzr**
This will improve connectivity reliability.

Change-Id: Ie4a5bcb397fb7959f2c5954d7a7569052ccc39fb
Signed-off-by: Philippe Coval <p.coval@samsung.com>

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [1a40a24c77a5b88fa4198ac14c51761ee8e9d034] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [1a40a24c77a5b88fa4198ac14c51761ee8e9d034] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [d0d05384ac22828c86b58864d5cd15ec5cd3d728] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [d0d05384ac22828c86b58864d5cd15ec5cd3d728] - Code Rule Check (C++) OK.

**Comment by rzr** [comment]
This change have been updated to fix a bug in master, please review and merge

**Comment by rzr** [comment]
This change is desired, should I open a new PR to prevent the ambiguity of the original change ?

**Comment by rzr** [comment]
Thanks

**Pull request merged**
