### PR TITLE
os/board/rtl/8720e: add FTL write protection disable/enable

### PR DESCRIPTION
**Pull request by yeetee179**
- Added ftl write protection disable/enable to flash erase and write when flash is protected.

### CODE REVIEW

**Comment by sunghan-chang** [comment]
@yeetee179 Is this a write protection for ftl partition only? As far as I know, first 512KB (including bl, ss and so on) is the region of write protection. Could you let me know exact area for write protection?

**Comment by yeetee179** [comment]
> 

Yes the flash protection is for the first 512Kb.

**Comment by sunghan-chang** [comment]
@yeetee179 So, this pr is necessary to disable write protection to write something in ftl partition which is protected?

**Comment by yeetee179** [comment]
@sunghan-chang Yes, the disabling of the flash protection for ftl is temporary. Meaning when erasing or writing is done to the FTL, it will disable its flash protection first, then write/erase it, followed by enabling the flash protection again. This procedure is done every write/erasure cycle.

**Review by sunghan-chang — APPROVED** [review]

**Pull request merged**
