### PR TITLE
catch correct typo

### PR DESCRIPTION
**Pull request by RuffaloLavoisier**
corrected the typo about `different`.

### CODE REVIEW

**Review by sangam-swami — DISMISSED** [review]
looks fine

**Review by jeongchanKim — COMMENTED** [review]
I think we can merge the changes as two commits, related to apps/external.

**Comment by RuffaloLavoisier** [comment]
> I think we can merge the changes as two commits, related to apps/external.

@jeongchanKim 
So should change the name of the commit? Or should reduce the number of commits?

**Comment by jeongchanKim** [comment]
> > I think we can merge the changes as two commits, related to apps/external.
> 
> @jeongchanKim So should change the name of the commit? Or should reduce the number of commits?

I think, the name of first commit can be external/protobuf, the second can be apps/examples/tc are enough.

**Comment by RuffaloLavoisier** [comment]
> I think, the name of first commit can be external/protobuf, the second can be apps/examples/tc are enough.
@jeongchanKim 
Sure - I understand. I'll reflect it.

**Comment by RuffaloLavoisier** [comment]
@jeongchanKim 
I would appreciate it if you could check if it's.

**Review by jeongchanKim — APPROVED** [review]
Looks good to me. Thanks.

**Review by sunghan-chang — APPROVED** [review]

**Review by 29TB — APPROVED** [review]
Simply word changes, LGTM, but god different doesn't seem like it's a word

**Pull request merged**
