### PR TITLE
build/tools/amebad/bootloader/: Recovery feature for boot param bootloader

### PR DESCRIPTION
**Pull request by fengyunlai**
Recovery feature for boot param bootloader.

### CODE REVIEW

**Comment by sunghan-chang** [comment]
@jeongarmy Could you verify bootloader functionalities for otn and hotfix?

**Comment by jeongarmy** [comment]
@fengyunlai Could you add some descriptions of sequences or something in a commit message?

**Comment by fengyunlai** [comment]
Yes, the commit log is updated.

**Comment by jeongarmy** [comment]
@fengyunlai Sorry for late feedback. I have verified that basic scenarios I said.
But I found one problem when both invalid BPs have valid kernel address.
Please refer the the following.

1. Flash binaries
- Binary with higher version "210210" in 0x8082000 -> the latest binary
- Binary with version "210204" in 0x8242000

2. Flash Invalid both BPs (I broken CRC values)
 - BP 1 has kernel addresses 0xffffffff, 0x8242000
 - BP 2 has kernel addresses 0x8082000, 0x8402000

3. Board booting -> Boot loader always use OTA2(jump 0x8242000)
 => Boot loader should boot binary with higher version by checking versions.

**Comment by jeongarmy** [comment]
@fengyunlai This change is not related to build test in CI but could you rebase master and push again for CI running?

**Comment by jeongarmy** [comment]
@fengyunlai I verified exceptional case I mentioned is fixed.

**Comment by sunghan-chang** [comment]
@fengyunlai Could you rebase this PR to latest?

**Comment by sunghan-chang** [comment]
@fengyunlai Could you check the rebase?

**Review by sunghan-chang — APPROVED** [review]

**Comment by fengyunlai** [comment]
> @fengyunlai Could you check the rebase?

Hi Mr Chang, I just rebased the PR.

**Comment by sunghan-chang** [comment]
@fengyunlai Thank you. Once build test is done. I will merge.

**Review by sunghan-chang — APPROVED** [review]

**Pull request merged**
