### PR TITLE
Update external/Makefile to remove object files.

### PR DESCRIPTION
**Pull request by heejin-kim**

### CODE REVIEW

**Comment by heejin-kim** [comment]
This commit is for resolving the issue no.186.
Please review @lssgood @sunghan-chang

**Comment by JunhwanPark** [comment]
Hi @heejin-kim 
I have a question.
I think that the object files are created in the following location.
`Iotivity_1.2-rel/extlibs/libcoap/SConscript`
If you cleaned normally with the `scons -c` command, the objects should be deleted. You better check `clean_iotivity.sh`.
I am checking it now, too.

**Comment by heejin-kim** [comment]
@JunhwanPark  Thanks to review that.
I understand what you mean.
I knew those methods and tried to update clean_iotivity.sh, Sconscript and Makefile to remove object file in libcoap. However, I did not find right ways to remove that. Honestly, there are no changes in Iotivity codes between DA commercialization code and this(opensource code). So I committed the code to forcibly remove object files.
If you find a way to fix that code, please let me know. I will update :)

**Comment by JunhwanPark** [comment]
I'm not used to 'scons'. :(

#### NOW
* libcoap build path :  `iotivity_1.2-rel/extlibs/libcoap`
* libcoap files path : `iotivity_1.2-rel/resource/csdk/connectivity/lib/libcoap-4.1.1`

Does the `libcoap-4.1.1` build have to be done in `extlibs/libcoap/SConscript`? It seems that `scons -c` will only delete `libcoap.a`. Is not `scons` doing a `clean` operation on the path where the `SConscript` file is located? Or should not you specify an additional path?
If my guess is correct, why do not you build the `libcoap-4.1.1` build in that path?

I'll be honest with you.
Since TizenRT uses the Makefile, I also wanted to use Makefile for iotivity. I had difficulty debugging iotivity with os code. Maybe I do not know scons well.

**Comment by heejin-kim** [comment]
Of course, I don't know about Sconscript, scons and other IoTivity things. In other code(for DA commercialization) those files(remained object files) removed well when I typed a command 'make distclean'. But in this code, it is not working well. I don't know what makes this differences. (iotivity code and Makefile in the external folder are exactly same)
Mr.Jang advised that try to revise Makefile.in in resource/csdk/connectivity/lib/libcoap-4.1.1. However, it is yet to be solved.

I don't have experience debugging iotivity. I'm sorry it didn't work out for you, I will ask that other colleagues.

**Comment by JunhwanPark** [comment]
Hi @heejin-kim 
It has been a long time since this patch was uploaded.
Is this the best way? Unusually, I do `make clean`, object files are not deleted and their size is reduced. If this is the best way, you can proceed with this.

**Pull request merged**
