### PR TITLE
Add bootprep script

### PR DESCRIPTION
**Pull request by btheosam**
Bootprep script generates partition table binary and
stores into flash. It is a standlone script now.

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [e03f66a8f9800fc344761ac56198f37e3e4b5fce] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [e03f66a8f9800fc344761ac56198f37e3e4b5fce] - Code Rule Check OK.

**Comment by btheosam** [comment]
Commit is postponed.

**Comment by btheosam** [comment]
This is closed due to the following.

a. Chang's comment to NOT have type and subtype fileds.
b. Another comment is NOT to have a script in public repo which is NOT used untill the full feataure is implemented

**Pull request closed without merging**
