### PR TITLE
build/configs: update memory layout and defconfig for esp32 boards

### PR DESCRIPTION
**Pull request by zhouxinhe**
There are 2 SoC reserved memory regions in internal ram:
 - [0x3ffe0000, 0x3ffe0440) - Reserve ROM PRO data region
 - [0x3ffe3f20, 0x3ffe4350) - Reserve ROM APP data region

Therefore, the heap memory is split into 3 regions:
 - [_sheap,     0x3ffe0000), size: 0x3ffe0000 - _sheap
 - [0x3ffe0440, 0x3ffe3f20), size: 15072
 - [0x3ffe4350, 0x40000000), size: 113840

dram0_0_seg range is [0x3ffb0000, 0x3ffe0000), the heap
ends at top of dram0_0_seg,  that is _eheap = 0x3ffe0000.
1st region is managed when heap initializing, and other regions
should be configured in defconfig explicitly.

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [140e9a1605d3a9caa72e8b066144b8695ecf62ed] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [140e9a1605d3a9caa72e8b066144b8695ecf62ed] - Code Rule Check OK.

**Comment by ChinaTizenRT** [comment]
it looks okay.  reserve memory is not permited to allocate by "malloc", 
otherwise write the memory will leads to unexpected issue.

**Comment by ChinaTizenRT** [comment]
and please check "ROM APP data region is need to be reserved
as currently "APP" core is not used in TizenRT, just "PRO" core runs.

**Comment by zhouxinhe** [comment]
> and please check whether "ROM APP data region" is need to be reserved or not.
> as currently ESP32's "APP" core is not used in TizenRT, just "PRO" core runs.

This region takes only 430 bytes, so I also remove it for consistence no matter "APP" core is used or not.

**Comment by zhouxinhe** [comment]
@sunghan-chang Could you please help to review?

**Pull request merged**
