### PR TITLE
Modify initialization of variables

### PR DESCRIPTION
**Pull request by JeonginKim**
Variable initialization modified

Signed-off-by: JeonginKim <ji1.kim@samsung.com>

### CODE REVIEW

**Comment by sunghan-chang** [comment]
I don't know why this is needed.

**Comment by JeonginKim** [comment]
Why Initialization is required.
1. Pointer variable initialization is the basic grammar in c language.
2. This code is detected by a static analysis tool(ex : prevent).
3. This code does not affect the system at this time, but a bug can occur when someone modifies the function.

**Comment by JeonginKim** [comment]
Why Initialization is required.

4. At compile time, the local pointer variable is not initialized and causes a warning.

5. The whole system  may be down.(see the below code)

int *a;
*a = 100;
printf("%d", *a);

Compilation succeeds but runtime error occurs.
A variable is a garbage value because it is not initialized.
If the value of the A variable equals the system's critical memory address, the whole system goes down.

int *a = NULL;
*a = 100;
printf("%d", *a);

Also, compilation succeeds, but a runtime error occurs.
But, since the A variable has been initialized, only this program is terminated. The whole system is unaffected.

So we need to initialize the local pointer variable.

**Comment by sunghan-chang** [comment]
@JeonginKim I don't agree yours.
1,2,4 => no
3 => When we modify them, we can concern
5 => Your example is right. But not for this file. Your example is not matched with this change.

**Comment by JeonginKim** [comment]
You are right. Currently, we do not need to initialize from our sample code.
If this code is never modified and the programmer never makes a mistake.
But programmers make mistakes because they are people. Initialization of local pointer variable is necessary to reduce mistakes.
I think this code can produce a bug.
So we must initialize the local pointer variable.
Nevertheless, if you think you do not need to initialize the local variables, I will cancel the commit.

**Pull request closed without merging**
