### PR TITLE
include/debug.h: Modify debug defines of task manager

### PR DESCRIPTION
**Pull request by tyha1115**
Add missing task manager debug defines

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [0f40c8f035058dceeed7890d1e804675bee72b3a] -

**Comment by seinfra** [comment]
Target : [0f40c8f035058dceeed7890d1e804675bee72b3a] -

**Comment by seinfra** [comment]
Target : [8a021eb20ef9378f84eec871833a41fa34d2b11c] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [8a021eb20ef9378f84eec871833a41fa34d2b11c] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [4efcfc04f318b9125c70386bfc2da29672529bdd] -

**Comment by seinfra** [comment]
Target : [4efcfc04f318b9125c70386bfc2da29672529bdd] -

**Comment by seinfra** [comment]
Target : [c0f1d2bb27afe6e7d6f0e1b1ec0df977f8147e51] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [c0f1d2bb27afe6e7d6f0e1b1ec0df977f8147e51] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [7a48f835ca8d9721bd3eecd0d82f50b4a329ba57] -

**Comment by seinfra** [comment]
Target : [7a48f835ca8d9721bd3eecd0d82f50b4a329ba57] -

**Comment by jeongarmy** [comment]
It looks good

**Pull request merged**
