### PR TITLE
build/tools/amebad/bootloader/ : Fix unexpected erase of OTA image after OTN and system reset

### PR DESCRIPTION
**Pull request by fengyunlai**
Fix unexpected erase of OTA image after OTN and system reset.

### CODE REVIEW

**Comment by sunghan-chang** [comment]
@fengyunlai Could you write the reason of the issue and how to resolve in the commit description? (NOT the PR description)

**Comment by fengyunlai** [comment]
> @fengyunlai Could you write the reason of the issue and how to resolve in the commit description? (NOT the PR description)

Sure Mr Chang.

**Comment by sunghan-chang** [comment]
@fengyunlai Could you let me know when you re-raise the PR for this?

**Comment by fengyunlai** [comment]
Mr Chang. Actually I committed with logs and push -f in this PR after you mentioned that to add logs 4 days ago. But it seems that this PR is unmerged?

**Comment by sunghan-chang** [comment]
@fengyunlai Yeah. You closed the PR when you forcely pushed.

**Comment by sunghan-chang** [comment]
```
@fengyunlai fengyunlai closed this 4 days ago
```

**Comment by fengyunlai** [comment]
> ```
> fengyunlai closed this 4 days ago
> ```

Oh, Mr Chang. I am sorry for that mistake, I reopen it.

**Comment by sunghan-chang** [comment]
@fengyunlai oh ok. I thought you needed to modify something with new PR. So I can merge this now. Right?

**Comment by fengyunlai** [comment]
> @fengyunlai oh ok. I thought you needed to modify something with new PR. So I can merge this now. Right?

Yes sure. Sorry for confusion made.

**Review by sunghan-chang — APPROVED** [review]

**Comment by sunghan-chang** [comment]
@fengyunlai Thank you for confirmation.

**Pull request merged**
