### PR TITLE
os/arch/arm/src/amebalite: Add serial flowcontrol warnings

### PR DESCRIPTION
**Pull request by kaikaikaime**
Warns the user to use UART0/3 when flowcontrol is used.

### CODE REVIEW

**Comment by kaikaikaime** [comment]
Current status:
Used #if defined instead
Added uart port identifier in the loguart print
Included comment to uart1,2,4 that autoflow control were not implemented
loguart output is where warning should be placed

**Review by sunghan-chang — COMMENTED** [review]
Do you need to modify something? Could you let me know current status regarding this?

**Comment by kaikaikaime** [comment]
> Current status: Used #if defined instead Added uart port identifier in the loguart print Included comment to uart1,2,4 that autoflow control were not implemented loguart output is where warning should be placed
> 
> The printf is tied to loguart uart4 which will be init first and printf will head towards there , which is in (else condition) from UART0/1/2/3 for flow control !
> 
> [Capture](https://user-images.githubusercontent.com/61275451/186621522-2aa0fa50-6889-4776-840f-b7a3a5b8f860.PNG) l

This the updated version of the commit, and above are the changes that has been made.
It is a completed.

**Comment by sunghan-chang** [comment]
@kaikaikaime You means below is done already in the PR?
> [kaikaikaime](https://github.com/kaikaikaime) commented [4 hours ago](https://github.com/Samsung/TizenRT/pull/5615#issuecomment-1226822009)
@sunghan-chang Ah yes, my ETA will be done with checks by next week

**Comment by kaikaikaime** [comment]
Yes, I was planning to implement additional feature, which is not required at this point in time.

**Review by sunghan-chang — APPROVED** [review]

**Pull request merged**
