### PR TITLE
[Realtek][RTL8721CSM] os/board/rtl8721csm/src/component/common/network/dhcp/dhcps Support AmebaD DHCPs

### PR DESCRIPTION
**Pull request by fengyunlai**
Support AmebaD DHCPS, porting from Realtek default SDK.

### CODE REVIEW

**Comment by fengyunlai** [comment]
> TizenRT provides dhcps, so realtek doesn't need to offer it.

Hi, is it necessary to use TizenRT DHCPS? 
We need to port Realtek DHCPS for softap connection usage for Realtek wlan driver.

**Comment by pillip8282** [comment]
@fengyunlai 
it's necessary to use TizenRT DHCPS? because it is managed by product app.
So you have to use TizenRT DHCPS

**Comment by sunghan-chang** [comment]
@fengyunlai Could you let me know whether this is still necessary or not?

**Comment by fengyunlai** [comment]
> @fengyunlai Could you let me know whether this is still necessary or not?

Thank you for your reminder. I think it is not needed anymore, I will delete in net manager pr.

**Comment by sunghan-chang** [comment]
@fengyunlai If you don't need this anymore, let's close the pr.

**Pull request closed without merging**
