### PR TITLE
os/board/rtl8721csm : print wifi library version

### PR DESCRIPTION
**Pull request by keerthanalex**
Add release note in os/board/rtl8721csm/src/libs/ directory
Print wifi library version when wifi_netmgr_utils_init() is called
Log format:"wlan_version" + "lib_wlan_ver_SHA-1_YYYY/MM/DD-HH:MM:SS"
e.g."wlan_version lib_wlan_ver_1275267f861fdafc92c5c5e89f10c0ee8a87e8ff_2021/12/15-10:27:50"
SHA-1 -> Realtek git version
YYYY/MM/DD -> compile date
HH:MM:SS -> compile time

### CODE REVIEW

**Review by jeongchanKim — APPROVED** [review]
LGTM

**Comment by pillip8282** [comment]
@keerthanalex 
Thanks for explanation of library format. Could you explain what area is wlan_version, realtek git version, compile date and compile time? it'll helpful to understand version. Thanks in advance.

**Comment by keerthanalex** [comment]
> @keerthanalex Thanks for explanation of library format. Could you explain what area is wlan_version, realtek git version, compile date and compile time? it'll helpful to understand version. Thanks in advance.

@pillip8282, I explained the format in the PR description.

**Comment by pillip8282** [comment]
@keerthanalex 
If I make up question, in release note version is written as 
```
version 1275267f861fdafc92c5c5e89f10c0ee8a87e8ff_2021/12/15-10:27:50
```
I could know what is compile date and time. But It's ambiguous to me what is wlan version and Realtek git version.
In PR description, you explained format is wlan_version + Realtek git version(SHA-1)
I want to know what is wlan version and Realtek git version.
I think it's clear if you let me know what is both field in following examples
```
version 1275267f861fdafc92c5c5e89f10c0ee8a87e8ff_2021/12/15-10:27:50
wlan_version lib_wlan_ver_1275267f861fdafc92c5c5e89f10c0ee8a87e8ff_2021/12/15-10:27:50
```

Thanks.

**Comment by keerthanalex** [comment]
> @keerthanalex If I make up question, in release note version is written as
> 
> ```
> version 1275267f861fdafc92c5c5e89f10c0ee8a87e8ff_2021/12/15-10:27:50
> ```
> 
> I could know what is compile date and time. But It's ambiguous to me what is wlan version and Realtek git version. In PR description, you explained format is wlan_version + Realtek git version(SHA-1) I want to know what is wlan version and Realtek git version. I think it's clear if you let me know what is both field in following examples
> 
> ```
> version 1275267f861fdafc92c5c5e89f10c0ee8a87e8ff_2021/12/15-10:27:50
> wlan_version lib_wlan_ver_1275267f861fdafc92c5c5e89f10c0ee8a87e8ff_2021/12/15-10:27:50
> ```
> 
> Thanks.

@pillip8282 , sorry for the confusion. Please find the below explanation,

**1) Output format: "wlan_version" + "lib_wlan_ver_SHA-1_YYYY/MM/DD-HH:MM:SS"**
e.g."wlan_version lib_wlan_ver_1275267f861fdafc92c5c5e89f10c0ee8a87e8ff_2021/12/15-10:27:50"

	"RTW_API_INFO("\n\rwlan_version %s\n", lib_wlan_rev);"
	a) printf statement -> "wlan_version"
	b) %s of lib_wlan_rev -> "lib_wlan_ver_SHA-1_YYYY/MM/DD-HH:MM:SS"
		- SHA-1 -> Realtek git version
		- YYYY/MM/DD -> Compile Date
		- HH:MM:SS -> Compile Time
	
**2) "RELEASE_NOTE" format: "version" + "SHA-1_YYYY/MM/DD-HH:MM:SS"**
e.g."version 1275267f861fdafc92c5c5e89f10c0ee8a87e8ff_2021/12/15-10:27:50"
	- SHA-1 -> Realtek git version
	- YYYY/MM/DD -> Compile Date
	- HH:MM:SS -> Compile Time

**Review by pillip8282 — APPROVED** [review]
LGTM

**Pull request merged**
