### PR TITLE
configs/artik053/nettest: enable FTP Client

### PR DESCRIPTION
**Pull request by JeonginKim**
I set the FTP Client to be enabled when building with the nettest option.
Must activate the temporary directory before the FTPC put command will operate normally.
Modified Temporary directory to be active.

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [7f56b5c62f46f405cf8f3d22d0378622990b28e2] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [7f56b5c62f46f405cf8f3d22d0378622990b28e2] - Code Rule Check OK.

**Comment by sunghan-chang** [comment]
1. This is not a change on external folder. ```configs/artik053/nettest: enable FTP client``` is right.
2. If ftpc is working with enabled tmpfs, let's make a dependancy between ftpc and tmpfs.

**Comment by seinfra** [comment]
Target : [d514fba790b38f5279c27289177cdc1db5b2c382] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [d514fba790b38f5279c27289177cdc1db5b2c382] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [4af29f1c2e8a746bda7db097031e95c15bf44b0a] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [4af29f1c2e8a746bda7db097031e95c15bf44b0a] - Code Rule Check (C++) OK.

**Comment by JeongJunSik** [comment]
Don't you need to apply to other board config such as 053s or 055s?

**Comment by sunghan-chang** [comment]
@JeonginKim Could you check @JeongJunSik 's comment?

**Comment by seinfra** [comment]
Target : [4af29f1c2e8a746bda7db097031e95c15bf44b0a] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [4af29f1c2e8a746bda7db097031e95c15bf44b0a] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [4af29f1c2e8a746bda7db097031e95c15bf44b0a] - Code Rule Check (C++) OK.

**Pull request closed without merging**
