### PR TITLE
Codecoverage tc lwip indentation

### PR DESCRIPTION
**Pull request by vinaykadam1**

### CODE REVIEW

**Comment by vinaykadam1** [comment]
@davidfather  resolved merge conflicts with master. Working on coding rules voilations.

**Comment by vinaykadam1** [comment]
@davidfather : 
1) Did sync with upstream.
2) Resolved merge conflicts.
3) Followed coding rules.
Please review the code.

**Comment by sunghan-chang** [comment]
@vinaykadam1 We talked this before through chat, and I said that leave a commit for indentation only in here. But here are different kinds of changes like adding lwip tc, sync-up with master. Even though I said this several times, always same.

**Comment by vinaykadam1** [comment]
@sunghan-chang: 
1)We added new test cases in codecoverage_tc_lwip_1 branch. To make indentation(like API comments, space correction etc..,) for new source code we took those source code to this branch and made indentation changes. 
2) sync-up:  each time we push the code we were getting merge conflict errors in many files. To avoid merge conflicts errors we did syn-up with master.

Please guide us for further corrections.

**Pull request closed without merging**
