### PR TITLE
seclink: change log

### PR DESCRIPTION
**Pull request by pillip8282**
change log

### CODE REVIEW

**Review by jeongchanKim — DISMISSED** [review]
LGTM

**Review by sunghan-chang — APPROVED** [review]

**Comment by sunghan-chang** [comment]
@pillip8282 When you use printf instead of dbg, you can't distinguish below.
```
#define SL_LOCK(lock)										\
	do {													\
		int sl_res = sem_wait(lock);						\
		if (sl_res < 0) {									\
			SLDRV_LOG(SLDRV_TAG" lock fail(%d)\n", errno);	\   <--- here
		}													\
	} while (0)

#define SL_UNLOCK(lock)										\
	do {													\
		int sl_res = sem_post(lock);						\
		if (sl_res < 0) {									\
			SLDRV_LOG(SLDRV_TAG" lock fail(%d)\n", errno);	\    <---- here
		}													\
	} while (0)
```
How about modifying SL_UNLOCK log like `unlock fail`?

**Comment by pillip8282** [comment]
@sunghan-chang 
Thanks for review. Yes as you said it's undifferentiated. I'll modify it.

**Review by sunghan-chang — APPROVED** [review]

**Review by jeongchanKim — APPROVED** [review]
LGTM

**Pull request merged**
