### PR TITLE
build/tools/amebad/bootloader/: bootloader for PR 4936 boot param feature.

### PR DESCRIPTION
**Pull request by fengyunlai**
add bootloader for PR 4936 boot param feature.

### CODE REVIEW

**Review by jeongchanKim — APPROVED** [review]
LGTM

**Comment by sunghan-chang** [comment]
@jeongarmy Could you verify the operation with this PR?

**Comment by sunghan-chang** [comment]
@fengyunlai When we merge this, we don't need PR #4918 anymore. Could you confirm?

**Comment by fengyunlai** [comment]
> @fengyunlai When we merge this, we don't need PR #4918 anymore. Could you confirm?

Yes Mr Chang, large image case is also passed. We don't need this PR 4918

**Comment by sunghan-chang** [comment]
@fengyunlai And we don't need to build bootloader in TizenRT either. Right? We can cancel that item.

**Comment by sunghan-chang** [comment]
@fengyunlai Thank you for update. Once @jeongarmy verifies, let you know result.

**Comment by fengyunlai** [comment]
> @fengyunlai And we don't need to build bootloader in TizenRT either. Right? We can cancel that item.

Yes Mr Chang, you are right.

**Comment by fengyunlai** [comment]
> @fengyunlai Thank you for update. Once @jeongarmy verifies, let you know result.

Thank you too, Mr Chang, and sure I will discuss with Mr Jeong via emails if there are any unwanted results.

**Comment by sunghan-chang** [comment]
@fengyunlai Except corner case, it works well. Let's merge this for now and let's prepare the corner case with another PR.

**Review by sunghan-chang — APPROVED** [review]

**Pull request merged**
