### PR TITLE
build/configs/rtl8730e/loadable_ext_psram/: Disable LCD support

### PR DESCRIPTION
**Pull request by namanjain7**
Disabling the LCD support for PSRAM defconfig

### CODE REVIEW

**Comment by namanjain7** [comment]
I have disabled the LCD support from menuconfig and then copied the LCD specific changes to defconfig.
LCD is disabled for loadable_ext_psram defconfig now.

**Comment by namanjain7** [comment]
I have disabled the LCD support from menuconfig and then copied the LCD specific changes to defconfig.
LCD is disabled for loadable_ext_psram defconfig now.

**Review by sunghan-chang — APPROVED** [review]

**Comment by sunghan-chang** [comment]
`Disable LCD support for 5th revision and lower board`
Explanation is ok but it looks strange for title. It just disables LCD support in psram defconfig. It does not include `for 5th revision and lower board`. Could you leave `Disable LCD suppport` at the title? Because of the title, someone could think LCD is disabled in rev 05 and lower by this.

**Comment by sunghan-chang** [comment]
@namanjain7 Could you modify the commit? not PR.

**Review by sunghan-chang — APPROVED** [review]

**Comment by namanjain7** [comment]
I have modified the commit message and description.

**Pull request merged**
