### PR TITLE
apps/testcase/systemio: add new gpio scenarios TC

### PR DESCRIPTION
**Pull request by samegautam**
File : apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c
Descriptions : add new scenarios testcase for GPIO

Scenarios testcase name : 
itc_gpio_all_direction_read_write_p
itc_gpio_all_edge_read_write_p
itc_gpio_all_drive_read_write_p
itc_gpio_set_get_direction_edge_drive_mode_p
itc_gpio_open_close_different_pin_p
itc_gpio_reopen_p
itc_gpio_reclose_p
itc_gpio_open_n
itc_gpio_close_n
itc_gpio_get_pin_n
itc_gpio_get_pin_after_close_n
itc_gpio_get_pin_after_invalid_open_n
itc_gpio_read_after_close_n
itc_gpio_write_after_close_n
itc_gpio_set_direction_n
itc_gpio_get_direction_n
itc_gpio_set_direction_after_close_n
itc_gpio_get_direction_after_close_n
itc_gpio_set_edge_mode_n
itc_gpio_get_edge_mode_n
itc_gpio_set_edge_mode_after_close_n
itc_gpio_get_edge_mode_after_close_n
itc_gpio_set_drive_mode_n
itc_gpio_get_drive_mode_n
itc_gpio_set_drive_mode_after_close_n
itc_gpio_get_drive_mode_after_close_n

### CODE REVIEW

**Comment by seinfra** [comment]
Code Rule Check Result:
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:313: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:316: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:319: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:323: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:326: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:326: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:327: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:327: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:333: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:333: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:336: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:336: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:337: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:337: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:340: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:346: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:346: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:349: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:349: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)

**Comment by seinfra** [comment]
Code Rule Check Result:
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:314: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:317: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:320: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:324: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:327: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:327: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:328: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:328: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:334: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:334: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:337: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:337: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:338: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:338: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:341: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:347: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:347: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:350: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:350: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by seinfra** [comment]
Code Rule Check Result:
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:313: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:316: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:319: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:323: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:326: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:326: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:327: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:327: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:333: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:333: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:336: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:336: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:337: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:337: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:340: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:346: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:346: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:349: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:349: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)

**Comment by seinfra** [comment]
Code Rule Check Result:
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:251: ERROR: [IDT_M_TAB] please, no spaces at the start of a line
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:316: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:319: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:322: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:326: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:329: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:329: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:330: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:330: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:336: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:336: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:339: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:339: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:340: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:340: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:343: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:349: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:349: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:352: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:352: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by seinfra** [comment]
Code Rule Check Result:
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:323: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by samegautam** [comment]
Please review @jeongchanKim @sunghan-chang @junmin-kim @Taejun-Kwon

**Comment by sunghan-chang** [comment]
@samegautam Don't leave your private commits in pull reqeust like ```Merge branch 'master' into gpio_scenarios```
Please remove 2 commits from latest.
```
git reset --hard HEAD^
git reset --hard HEAD^
git push -f
```

**Comment by samegautam** [comment]
Leave a comment

**Pull request closed without merging**
