### PR TITLE
framework/araui: Revise typos in the headers of AraUI.

### PR DESCRIPTION
**Pull request by tyha1115**
- Revise typos
- Add SAMSUNG license
- Revise unchaged descriptions for API

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [15c5fbf31e1a27efa5f5e10ed47a599a16544df2] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [15c5fbf31e1a27efa5f5e10ed47a599a16544df2] - Code Rule Check OK.

**Comment by tyha1115** [comment]
Thanks for your comments, they were changed.

**Comment by seinfra** [comment]
Target : [8a77cde6dbe625dd36b1ee9ccf6333ef09b73a04] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [8a77cde6dbe625dd36b1ee9ccf6333ef09b73a04] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [a1282342631e348b1d37b1beea6b91a7e5801dbc] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [a1282342631e348b1d37b1beea6b91a7e5801dbc] - Code Rule Check OK.

**Pull request merged**
