### PR TITLE
os/board/rtl8730e: Modify API for obtaining wpa state

### PR DESCRIPTION
**Pull request by jwei5**
- Modify get_wpa_supplicant_state API to cater to usage after disconnection event
- Modify API to obtain key_mgmt value from recently disconnected connection
- Add API to obtain previous wifi join status

### CODE REVIEW

**Comment by jwei5** [comment]
Hi @hk-gwak  , I have made some changes to get_wpa_supplicant_state() for usage during disconnection event

**Comment by hk-gwak** [comment]
Looks like PR was updated recently. is there anything to be modified additionally?

**Comment by jwei5** [comment]
Hi @hk-gwak , I updated the PR yesterday to resolve a conflict with km0_km4_app.bin from commit 6552908c96184edd73f6c2031aafacbb89d7e640

**Comment by hk-gwak** [comment]
> Hi @hk-gwak , I updated the PR yesterday to resolve a conflict with km0_km4_app.bin from commit [6552908](https://github.com/Samsung/TizenRT/commit/6552908c96184edd73f6c2031aafacbb89d7e640)

Got it, Thank you.

**Review by hk-gwak — APPROVED** [review]
LGTM

**Pull request merged**
