### PR TITLE
mtd/jedec : Add new flash interface of XMC

### PR DESCRIPTION
**Pull request by Taejun-Kwon**
Add new jedec Common Flash Interface to support XMC

### CODE REVIEW

**Review by jeongchanKim — APPROVED** [review]
LGTM

**Review by amogh-samsung — APPROVED** [review]
Looks all good

**Review by jeongchanKim — APPROVED** [review]
LGTM

**Review by sangam-swami — APPROVED** [review]
looks fine

**Review by sunghan-chang — APPROVED** [review]

**Pull request merged**
