### PR TITLE
media: Modify get closest samprate logic

### PR DESCRIPTION
**Pull request by jarvisjang**
Some logic that placed in the loop can be out of the loop.

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [04763b9b741772eb883f4b24a525d6a968f9dc69] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [04763b9b741772eb883f4b24a525d6a968f9dc69] - Code Rule Check Result:
framework/src/media/audio/audio_manager.c:950: ERROR: [BRC_M_SMT] else should follow close brace '}'
framework/src/media/audio/audio_manager.c:972: ERROR: [BRC_M_SMT] else should follow close brace '}'
framework/src/media/audio/audio_manager.c:993: ERROR: [BRC_M_SMT] else should follow close brace '}'

**Comment by seinfra** [comment]
Target : [5fb218d696dc00c5e7e0944f3deaf66d9c8c6826] - Code Rule Check Result:
framework/src/media/audio/audio_manager.c:991: ERROR: [BRC_M_SMT] else should follow close brace '}'

**Comment by seinfra** [comment]
Target : [5fb218d696dc00c5e7e0944f3deaf66d9c8c6826] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [24a182b8b09fda710028290a3fcb45255d1a0d68] -

**Comment by seinfra** [comment]
Target : [4b14f22ca368246f4a5a04a7ce90b906ae7609b2] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [4b14f22ca368246f4a5a04a7ce90b906ae7609b2] - Code Rule Check (C++) OK.

**Comment by jarvisjang** [comment]
@Taejun-Kwon @jsdosa @junmin-kim  Please review this PR.

**Pull request merged**
