### PR TITLE
framework/st_things : Turn on the ERROR log by default

### PR DESCRIPTION
**Pull request by JeongJunSik**
- ERROR is not visible.
so, turn on the ERROR log default.

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [69d1407e4daed5a0b1652049ed3902d9323b1f33] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [69d1407e4daed5a0b1652049ed3902d9323b1f33] - Code Rule Check (C++) OK.

**Comment by juitem** [comment]
contents is okay, it would be better to change Title
"Turn on the ERROR log by default

**Comment by seinfra** [comment]
Target : [fcd49697d83ea2fab9b6b414c25121e34991f8cc] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [fcd49697d83ea2fab9b6b414c25121e34991f8cc] - Code Rule Check (C++) OK.

**Pull request merged**
