### PR TITLE
kernel/spawn: Remove task_spawn and posix_spawn

### PR DESCRIPTION
**Pull request by jeongchanKim**
task_spawn and posix_spawn are deprecated.
TizenRT does not support spawn functionality. Because current TizenRT, all tasks are in the memory.

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [c4dc27ffd90bd94ba7fd20ac739381aa326dfca2] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [c4dc27ffd90bd94ba7fd20ac739381aa326dfca2] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [8f44ff19ea00cb3a686c30085136c1b0c6af3e07] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [8f44ff19ea00cb3a686c30085136c1b0c6af3e07] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [4ce1be699149de5de133c5045ee040a08246a871] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [4ce1be699149de5de133c5045ee040a08246a871] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [48347d30bbbe35debf8e71a72cc611b232871a8e] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [48347d30bbbe35debf8e71a72cc611b232871a8e] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [9ea8e1243cf7f7ceaa8e3b1241ae477091da8c77] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [9ea8e1243cf7f7ceaa8e3b1241ae477091da8c77] - Code Rule Check OK.

**Comment by jeongchanKim** [comment]
@pradeepns85, If PROTECTED BUILD is enabled and memory protection per task is supported, spawn functionality is needed. 
But as I know, we only have a plan for supporting stack and heap protection per task. With this condition, only posix_spawn is needed, task_spawn is not needed. Because task_spawn is as same as task_spawn.(entry point is not protected.)

posix_spawn is not working in current TizenRT. So I think we can remove this and we will add again when we can support.

I also want to know your opinion. Thanks.

**Comment by pradeepns85** [comment]
@jeongchanKim , Removing and adding it later is one option as you suggested. 
Another option is to bind this feature with CONFIG_BUILD_PROTECTED.  
I request you to discuss  with @sunghan-chang  and take it further. I agree to his final opinion.

Cheers,
Pradeep

**Pull request merged**
