### PR TITLE
apps: kill apps depend on signals

### PR DESCRIPTION
**Pull request by rzr**
Change-Id: I31c51dab2338cf3d6235c058d9033f79f196328a
Signed-off-by: Philippe Coval <philippe.coval@osg.samsung.com>

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [fa8ea3949a1ac83b1c1fabeefacbd9490d1ba02d] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [fa8ea3949a1ac83b1c1fabeefacbd9490d1ba02d] - Code Rule Check (C++) OK.

**Comment by sunghan-chang** [comment]
@rzr Could you let me know the reason why you make a dependancy with SIGNAL?

**Comment by rzr** [comment]
Actually dependency was introduced in declaration and not implementation.

```
cat ./apps/system/utils/kdbg_commands.h

#ifndef CONFIG_DISABLE_SIGNALS
#if defined(CONFIG_ENABLE_KILL)
int kdbg_kill(int argc, char **args);
#endif

#if defined(CONFIG_ENABLE_KILLALL)
int kdbg_killall(int argc, char **args);
#endif
#endif  
```

I have tested the other patch, but it does much that my straightforward one, so I would recommend to merge this and rebase the other.

**Comment by sunghan-chang** [comment]
@rzr You're right. We missed that point. I will modify kdbg_command.h. But I don't agree why we merge yours. "kill" command has two types execution. One is sending signal, another is terminating thread. Terminating thread does not treat CONFIG_DISABLE_SIGNAL. What is your straightforward point?

**Comment by rzr** [comment]
I just built master without this patch, 

92760eeee331f18dd6cd0fe6bec386b56020453a seems to remove the dependencies in
./apps/system/utils/kdbg_commands.h

So I can align to it, by closing this unmerged PR. Is it ok ?

**Comment by sunghan-chang** [comment]
@rzr Thank you for confirmation. If you don't have different opinion, it is ok to close this to me.

**Pull request closed without merging**
