### PR TITLE
build/tools/amebasmart/gnu_utility: optimize PM sleep/wakeup time

### PR DESCRIPTION
**Pull request by zhongnuo-tang**
1. reduce sleep/wakeup log
2. optimize sleep/wakeup time by adjusting the delay time required for last data to be completely out of loguart tx fifo. 115200bps requires 104us, 1.5Mbps requires 8us

### CODE REVIEW

**Comment by sunghan-chang** [comment]
@zhongnuo-tang In the description, maybe 8us, not 8ms.

**Comment by sunghan-chang** [comment]
Could you add how to reduce the logs?

**Comment by zhongnuo-tang** [comment]
> Could you add how to reduce the logs?
Dear Mr Chang,
change from
"[LPCAP-I] CA32PG",
"[LPCNP-I] KM4PG"
"[PMC-I] Wakeup source: UART LOG"
to
"CA32PG-KM4PG-Wakeup : UART LOG"
updated in commit message.

**Comment by zhongnuo-tang** [comment]
> Could you add how to reduce the logs?

Dear @sunghan-chang the logs are reduced as follow 
change from
"[LPCAP-I] CA32PG",
"[LPCNP-I] KM4PG"
"[PMC-I] Wakeup source: UART LOG"
to
"CA32PG-KM4PG-Wakeup : UART LOG"

**Review by sunghan-chang — APPROVED** [review]

**Comment by sunghan-chang** [comment]
@ewoodev @gSahitya-samsung Could you confirm this?

**Review by gSahitya-samsung — APPROVED** [review]

**Pull request merged**
