### PR TITLE
build/tools/amebad/bootloader/ : Check BP before check CRC32

### PR DESCRIPTION
**Pull request by fengyunlai**
build/tools/amebad/bootloader/ : Check BP before check CRC32
    
Check BP data before caculate CRC32 to skip invalid bp region CRC32 calculation and thus save time.
Do not erase BP if invalid.
Add valid bp version and kernel version print.
    
Bootloader version:
    km0_bootloader_ver_07729b9_2022/01/18-14:40:05

### CODE REVIEW

**Comment by sunghan-chang** [comment]
Could you write new bootloader version in commit description?

**Comment by fengyunlai** [comment]
> Could you write new bootloader version in commit description?

Sure Mr Chang, I have amended the commit log and re-pushed with bootloader version.

**Comment by sunghan-chang** [comment]
@jeongarmy is checking on this. Once she verifies, I will merge.

**Comment by jeongarmy** [comment]
Hi, I verified it works well in normal case.

But it doesn't work when boot parameter recovery.
0. Download valid kernel binary to first kernel partition and initial bootparam.bin (valid BP1, active idx = 0) => It boots well
1. Download same valid kernel binary to second kernel partition
2. Erase some bytes in the first kernel partition to break binary
3. An error happens like below
```
#[MODULE_BOOT-LEVEL_INFO]:IMG1 ENTER ROMSUB:2
bootloader_version km0_bootloader_ver_07729b9_2022/01/10-15:37:41
#utoboot in 50 milliseconds
Normal boot
BP1 data valid
BP2 version invalid
BP1 CRC32 match, attached CRC: 0xbb0f968a, calculated CRC: 0xbb0f968a
BP1 selected
Active Index: 0
OTA1 invalid
Active index OTA invalid, rewrite active index to 1
```
=> It should boots well and bootparam should be recovered with `active idx = 1`

**Comment by fengyunlai** [comment]
> Hi, I verified it works well in normal case.
> 
> But it doesn't work when boot parameter recovery. 0. Download valid kernel binary to first kernel partition and initial bootparam.bin (valid BP1, active idx = 0) => It boots well
> 
> 1. Download same valid kernel binary to second kernel partition
> 2. Erase some bytes in the first kernel partition to break binary
> 3. An error happens like below
> 
> ```
> #[MODULE_BOOT-LEVEL_INFO]:IMG1 ENTER ROMSUB:2
> bootloader_version km0_bootloader_ver_07729b9_2022/01/10-15:37:41
> #utoboot in 50 milliseconds
> Normal boot
> BP1 data valid
> BP2 version invalid
> BP1 CRC32 match, attached CRC: 0xbb0f968a, calculated CRC: 0xbb0f968a
> BP1 selected
> Active Index: 0
> OTA1 invalid
> Active index OTA invalid, rewrite active index to 1
> ```
> 
> => It should boots well and bootparam should be recovered with `active idx = 1`

Hi, sorry for any trouble made. Let me check recovery case more and see which modification cause this error. I will fix that and recommit asap. Thank you~

**Comment by jeongarmy** [comment]
@fengyunlai Thank you!
And could you add version of valid BP to know how which BP is selected when both BPs are valid?
```
#[MODULE_BOOT-LEVEL_INFO]:IMG1 ENTER ROMSUB:2
bootloader_version km0_bootloader_ver_07729b9_2022/01/10-15:37:41
#utoboot in 50 milliseconds
Normal boot
BP1 data valid // Add version here
BP2 data valid // Add version here
BP1 CRC32 match, attached CRC: 0xbb0f968a, calculated CRC: 0xbb0f968a
BP2 CRC32 match, attached CRC: 0xa115fe6, calculated CRC: 0xa115fe6
Both BP CRC valid
BP2 selected
Active Index: 1
OTA2 CRC32 match, attached CRC: 0x196e3ef2, calculated CRC: 0x196e3ef2
[MODULE_BOOT-LEVEL_INFO]:OTA2 USE, version: 200204

```

**Comment by fengyunlai** [comment]
> @fengyunlai Thank you! And could you add version of valid BP to know how which BP is selected when both BPs are valid?
> 
> ```
> #[MODULE_BOOT-LEVEL_INFO]:IMG1 ENTER ROMSUB:2
> bootloader_version km0_bootloader_ver_07729b9_2022/01/10-15:37:41
> #utoboot in 50 milliseconds
> Normal boot
> BP1 data valid // Add version here
> BP2 data valid // Add version here
> BP1 CRC32 match, attached CRC: 0xbb0f968a, calculated CRC: 0xbb0f968a
> BP2 CRC32 match, attached CRC: 0xa115fe6, calculated CRC: 0xa115fe6
> Both BP CRC valid
> BP2 selected
> Active Index: 1
> OTA2 CRC32 match, attached CRC: 0x196e3ef2, calculated CRC: 0x196e3ef2
> [MODULE_BOOT-LEVEL_INFO]:OTA2 USE, version: 200204
> ```

I have fixed that issue on my side, added valid BP version print and re-committed. Thanks~

**Comment by jeongarmy** [comment]
Hi, Did you test same scenario on loadable?
Binary loading is failed after bootloader recovers BP.
I think user data in bootparam are broken when BP recovery.
```
Normal boot
BP1 data valid, version:1
BP2 version invalid
BP1 CRC32 match, attached CRC: 0x8c9e0187, calculated CRC: 0x8c9e0187
BP1 selected
Active Index: 1
OTA2 CRC32 match, attached CRC: 0x7c1aa7dc, calculated CRC: 0x7c1aa7dc
[MODULE_BOOT-LEVEL_INFO]:OTA2 USE, version: 200204
...
// Get app loading info from bootparam => But failed.
binary_manager_scan_ubin_all: Failed to find matched binary ap▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒                                                                   ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒                                                                   ▒▒ in binary table
binary_manager_scan_ubin_all: Failed to find matched binary ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒                                                                   ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ in binary tabl                                                                   e
loadingall_thread: Failed to find valid binaries to load
```
There are user binary information also in boot parameter on loadable.
Could you please check and keep all boot parameters except for data needed for recovery.
You can see the all data of boot parameter in os/tools/mkbootparam.py.

**Comment by fengyunlai** [comment]
> Hi, Did you test same scenario on loadable? Binary loading is failed after bootloader recovers BP. I think user data in bootparam are broken when BP recovery.
> 
> ```
> Normal boot
> BP1 data valid, version:1
> BP2 version invalid
> BP1 CRC32 match, attached CRC: 0x8c9e0187, calculated CRC: 0x8c9e0187
> BP1 selected
> Active Index: 1
> OTA2 CRC32 match, attached CRC: 0x7c1aa7dc, calculated CRC: 0x7c1aa7dc
> [MODULE_BOOT-LEVEL_INFO]:OTA2 USE, version: 200204
> ...
> // Get app loading info from bootparam => But failed.
> binary_manager_scan_ubin_all: Failed to find matched binary ap▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒                                                                   ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒                                                                   ▒▒ in binary table
> binary_manager_scan_ubin_all: Failed to find matched binary ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒                                                                   ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ in binary tabl                                                                   e
> loadingall_thread: Failed to find valid binaries to load
> ```
> 
> There are user binary information also in boot parameter on loadable. Could you please check and keep all boot parameters except for data needed for recovery. You can see the all data of boot parameter in os/tools/mkbootparam.py.

You are right. Before I didn't know that loadable apps BP will include more bp data. Now I have fixed the loadable app invalid kernel bin and bp recovery cases. I have also tested and verified these 2 cases. Thank you~

**Comment by jeongarmy** [comment]
I verified BP recovery and boot works well.
But I couldn't see the version of used kernel binary when BP recovery.
```
#[MODULE_BOOT-LEVEL_INFO]:IMG1 ENTER ROMSUB:2
bootloader_version km0_bootloader_ver_07729b9_2022/01/13-15:04:16
#utoboot in 50 milliseconds
Normal boot
BP1 data valid, version:1
BP2 version invalid
BP1 CRC32 match, attached CRC: 0xbb0f968a, calculated CRC: 0xbb0f968a
BP1 selected
Active Index: 0
OTA1 invalid
Active index OTA invalid, rewrite active index to 1
OTA2 CRC32 match, attached CRC: 0xee37fe40, calculated CRC: 0xee37fe40
[MODULE_BOOT-LEVEL_INFO]:OTA2 USE // Version is missing
[MODULE_BOOT-LEVEL_INFO]:IMG2 DATA[0xc010cb4:5840:0x85000]
[MODULE_BOOT-LEVEL_INFO]:IMG2 SIGN[RTKWin(8500c)]
[MODULE_BOOT-LEVEL_INFO]:IMG2 ENTRY[0x85000:0xc00d639]
[MODULE_BOOT-LEVEL_INFO]:KM0 BOOT_IMG2 BOOT REASON: 0

After rebooting,

#utoboot in 50 milliseconds
Normal boot
BP1 data valid, version:1
BP2 version invalid
BP1 CRC32 match, attached CRC: 0x3e14a4c4, calculated CRC: 0x3e14a4c4
BP1 selected
Active Index: 1
OTA2 CRC32 match, attached CRC: 0xee37fe40, calculated CRC: 0xee37fe40
[MODULE_BOOT-LEVEL_INFO]:OTA2 USE, version: 200204 // It is ok
```

**Comment by fengyunlai** [comment]
> I verified BP recovery and boot works well. But I couldn't see the version of used kernel binary when BP recovery.
> 
> ```
> #[MODULE_BOOT-LEVEL_INFO]:IMG1 ENTER ROMSUB:2
> bootloader_version km0_bootloader_ver_07729b9_2022/01/13-15:04:16
> #utoboot in 50 milliseconds
> Normal boot
> BP1 data valid, version:1
> BP2 version invalid
> BP1 CRC32 match, attached CRC: 0xbb0f968a, calculated CRC: 0xbb0f968a
> BP1 selected
> Active Index: 0
> OTA1 invalid
> Active index OTA invalid, rewrite active index to 1
> OTA2 CRC32 match, attached CRC: 0xee37fe40, calculated CRC: 0xee37fe40
> [MODULE_BOOT-LEVEL_INFO]:OTA2 USE // Version is missing
> [MODULE_BOOT-LEVEL_INFO]:IMG2 DATA[0xc010cb4:5840:0x85000]
> [MODULE_BOOT-LEVEL_INFO]:IMG2 SIGN[RTKWin(8500c)]
> [MODULE_BOOT-LEVEL_INFO]:IMG2 ENTRY[0x85000:0xc00d639]
> [MODULE_BOOT-LEVEL_INFO]:KM0 BOOT_IMG2 BOOT REASON: 0
> 
> After rebooting,
> 
> #utoboot in 50 milliseconds
> Normal boot
> BP1 data valid, version:1
> BP2 version invalid
> BP1 CRC32 match, attached CRC: 0x3e14a4c4, calculated CRC: 0x3e14a4c4
> BP1 selected
> Active Index: 1
> OTA2 CRC32 match, attached CRC: 0xee37fe40, calculated CRC: 0xee37fe40
> [MODULE_BOOT-LEVEL_INFO]:OTA2 USE, version: 200204 // It is ok
> ```

Hi, yes, because when BP recovery or rewrite active index, the printing is not the same place as normal boot. So when reboot, version is printed.  I thought only normal case need that. 

Do you think we need to add this version print in this PR? Or may I ask whether I can add this minor modification in next PR, together with hotfix hash stored in efuse feature? That feature will be done within next week I think, I can add this minor fix there.

Thank you!

**Comment by jeongarmy** [comment]
@fengyunlai As I know, we didn't decide hotfix hash stored in efuse feature yet.
I think we'd better to merge this PR with minor modification that version prints when BP recovery first.
Could you please add version print in this PR?

**Comment by fengyunlai** [comment]
> @fengyunlai As I know, we didn't decide hotfix hash stored in efuse feature yet. I think we'd better to merge this PR with minor modification that version prints when BP recovery first. Could you please add version print in this PR?

You are right, I have modified in this PR.

**Review by jeongarmy — APPROVED** [review]
I verified all works well. Looks good to me. Thank you!

**Review by sunghan-chang — APPROVED** [review]

**Pull request merged**
