### PR TITLE
framework/araui: Replace tweening widget with animation

### PR DESCRIPTION
**Pull request by dev-hue**
- Replace tweening with animation
- Remove tweening code
- Remove unused variables
- Correct typos

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [2a932fbc1466952e4d066580c45ae845cf745d84] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [2a932fbc1466952e4d066580c45ae845cf745d84] - Code Rule Check Result:
framework/src/araui/animation/ui_animation.c:341: ERROR: [BRC_M_SMT] that open brace { should be on the previous line

**Comment by seinfra** [comment]
Target : [cdb20aec8d908c8e4404169f18b01ee4406b5a1e] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [cdb20aec8d908c8e4404169f18b01ee4406b5a1e] - Code Rule Check Result:
framework/src/araui/core/ui_core.c:213: ERROR: [IDT_M_TAB] please, no spaces at the start of a line

**Comment by dev-hue** [comment]
New PR will be requested.
Close this PR.

**Pull request closed without merging**
