### PR TITLE
build/tools/amebasmart: Fix UART Download for External Flash

### PR DESCRIPTION
**Pull request by jiangxiaoyunjoy**
offset for external flash was not handled properly when performing flash erase, causing image download wrongly

### CODE REVIEW

**Comment by sunghan-chang** [comment]
@jiangxiaoyunjoy Could you add more explanation of this commit in the COMMIT description? What was the issue? Without this PR, the downloader does not work well?

**Comment by jiangxiaoyunjoy** [comment]
> @jiangxiaoyunjoy Could you add more explanation of this commit in the COMMIT description? What was the issue? Without this PR, the downloader does not work well?

Hi @sunghan-chang ，
the external flash is erased with the wrong partition in the previous version, as the offset conversion for the external flash was not handled properly, this will cause image download wrongly for DDR package.
the bug is fixed in this flashloader, and the download tool won't be affected.

**Comment by sunghan-chang** [comment]
@jiangxiaoyunjoy Could you write what you said in the commit description?
@Tirtha-Samsung Could you check this PR?

**Comment by jiangxiaoyunjoy** [comment]
> @jiangxiaoyunjoy Could you write what you said in the commit description? @Tirtha-Samsung Could you check this PR?

Hi @sunghan-chang ,
commit description changed.
Thank you~

**Comment by sunghan-chang** [comment]
@jiangxiaoyunjoy `the bug is fixed in this flashloader, and the download tool won't be affected.`

As far as I know, the flashloader is a part of the download tool. What do you mean `the download tool won't be affected.`?
Do you mean that
flashloader = tool for Linux
download tool = tool for Windows
?

**Comment by jiangxiaoyunjoy** [comment]
> @jiangxiaoyunjoy `the bug is fixed in this flashloader, and the download tool won't be affected.`
> 
> As far as I know, the flashloader is a part of the download tool. What do you mean `the download tool won't be affected.`? Do you mean that flashloader = tool for Linux download tool = tool for Windows ?

Hi @sunghan-chang ,
flashloader and download tool are compulsory for both Windows version and Linux version.  download tool invoked flashloader to get information and transfer data.
To solve this issue, only flashloader needs to be modified, the download tool can be kept unchanged.
Thank you~

**Comment by Tirtha-Samsung** [comment]
@jiangxiaoyunjoy , what problem are you facing with this PR https://github.com/Samsung/TizenRT/pull/6350

**Comment by sunghan-chang** [comment]
@jiangxiaoyunjoy When we check downloading with PR #6350 , it looks no issue there. But you said there is a some issue you mentioned in the description. I don't know this is necessary or not. Do you think this should be merged regardless of PR #6350 ? Or if we use 6350, no need to merge this?

**Comment by sunghan-chang** [comment]
@jiangxiaoyunjoy How can we meet the issue? I mean, how to reproduce the issue?

**Comment by jiangxiaoyunjoy** [comment]
> @jiangxiaoyunjoy Could you check my comments?

Hi @sunghan-chang ,
Please proceed to Eric to know more details about this issue. The current TizenRT cannot 
 reproduce the issue, so I'm not able to provide the reproduce flow.
Thank you~

**Comment by jiangxiaoyunjoy** [comment]
Hi @sunghan-chang
Please review the latest commit log. If this description is okay, please merge this PR to TizenRT.
Thank you~

**Review by jylee9613 — APPROVED** [review]

**Review by jeongarmy — APPROVED** [review]
LGTM

**Pull request merged**
