### PR TITLE
mm/check_heap_corruption,manage_allocfail : Change dbg to lldbg

### PR DESCRIPTION
**Pull request by jeongchanKim**
In mm_check_heap_corruption,mm_manage_allocfail, information is printed through dbg. So if called from up_assert, logs can be mixed.

Signed-off-by: jeongchanKim <jc_.kim@samsung.com>

### CODE REVIEW

**Review by 29TB — COMMENTED** [review]
LGTM. >.>

**Review by 29TB — DISMISSED** [review]
Seems to be properly redefined, as long as no other files use that variable (or whatever), I believe it should be fine. LGTM.

**Comment by kishore-sn** [comment]
Looks good

**Review by sangam-swami — DISMISSED** [review]
Looks fine

**Comment by sunghan-chang** [comment]
@jeongchanKim As we discussed offline, this could not be a solution to prevent log mixing. Let's check flushing and sched lock.

**Pull request closed without merging**
