### PR TITLE
kdbg: change config name of kdbg commands to ENABLE_XXXX_CMD

### PR DESCRIPTION
**Pull request by jeongarmy**
change config name of kdbg commands to ENABLE_XXXX_CMD to clear to user.

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [c79e23af8db6b456863640e2bba51d97dbebb252] -

**Comment by seinfra** [comment]
Target : [c79e23af8db6b456863640e2bba51d97dbebb252] -

**Comment by seinfra** [comment]
Target : [f4aa6e74c7578c0bee52e1b01a4b55d60289e97e] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [f4aa6e74c7578c0bee52e1b01a4b55d60289e97e] - Code Rule Check OK.

**Comment by sunghan-chang** [comment]
@jeongarmy Because you don't change defconfigs, kernel commands will not work on defconfig. Please change them together.

**Comment by seinfra** [comment]
Target : [e25264a82941f2f2b7da30339261bd9a84ae6317] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [e25264a82941f2f2b7da30339261bd9a84ae6317] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [e326041e6eb11f3d0d64032ab782b134a769237d] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [e326041e6eb11f3d0d64032ab782b134a769237d] - Code Rule Check (C++) OK.

**Pull request merged**
