### PR TITLE
apps/testcase/systemio: add new gpio scenarios TC

### PR DESCRIPTION
**Pull request by samegautam**
File : apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c
Descriptions : add new scenarios testcase for GPIO
Scenarios testcase name :
 itc_gpio_all_direction_read_write_p
 itc_gpio_all_edge_read_write_p
 itc_gpio_all_drive_read_write_p
 itc_gpio_set_get_direction_edge_drive_mode_p
 itc_gpio_open_close_different_pin_p
 itc_gpio_reopen_p
 itc_gpio_reclose_p
 itc_gpio_open_n
 itc_gpio_close_n
 itc_gpio_get_pin_n
 itc_gpio_get_pin_after_close_n
 itc_gpio_get_pin_after_invalid_open_n
 itc_gpio_read_after_close_n
 itc_gpio_write_after_close_n
 itc_gpio_set_direction_n
 itc_gpio_get_direction_n
 itc_gpio_set_direction_after_close_n
 itc_gpio_get_direction_after_close_n
 itc_gpio_set_edge_mode_n
 itc_gpio_get_edge_mode_n
 itc_gpio_set_edge_mode_after_close_n
 itc_gpio_get_edge_mode_after_close_n
 itc_gpio_set_drive_mode_n
 itc_gpio_get_drive_mode_n
 itc_gpio_set_drive_mode_after_close_n
 itc_gpio_get_drive_mode_after_close_n

Signed-off-by: Sameer Gautam <sameer.g1@samsung.com>

### CODE REVIEW

**Comment by seinfra** [comment]
Code Rule Check Result:
apps/examples/testcase/ta_tc/systemio/itc/itc_gpio.c:323: ERROR: [SPC_M_OPR] space required after that ';' (ctx:VxV)

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by samegautam** [comment]
please review @jeongchanKim @sunghan-chang @junmin-kim @Taejun-Kwon

**Comment by seinfra** [comment]
Code Rule Check OK.

**Comment by samegautam** [comment]
@sunghan-chang : Please review.
 we have changed testcase name as per updated coding conventions.

**Comment by samegautam** [comment]
Changes would be commit in split commit.

**Pull request closed without merging**
