### PR TITLE
build/tools/amebasmart: Tune DDR package Tx power

### PR DESCRIPTION
**Pull request by ZhenBei-Sin**

### CODE REVIEW

**Comment by sunghan-chang** [comment]
@ZhenBei-Sin We will use both packages. Is this PR ok for both? Could you confirm that?

**Comment by ZhenBei-Sin** [comment]
> @ZhenBei-Sin We will use both packages. Is this PR ok for both? Could you confirm that?

Verification Bootup:
image

Verification Log:
ble_rmc init, ble_rmc start, wm_test start, wm_test scan, wm_test join, wm_test info
[PR#6368_DDR_flat_dev.log](https://github.com/user-attachments/files/16791176/PR.6368_DDR_flat_dev.log)
[PR#6368_PSRAM_flat_apps.log](https://github.com/user-attachments/files/16791177/PR.6368_PSRAM_flat_apps.log)

**Comment by sunghan-chang** [comment]
@ZhenBei-Sin Title is `tune tx power`. It looks and it should not affect booting. How about rf performance with this PR for both packages?

**Comment by ZhenBei-Sin** [comment]
> @ZhenBei-Sin Title is `tune tx power`. It looks and it should not affect booting. How about rf performance with this PR for both packages?

Hi @sunghan-chang 
Just received the test result, everything work fine.
You may double confirm with module maker about the RF performance.

Thank you.

**Comment by sunghan-chang** [comment]
@ZhenBei-Sin Because PR #6370 was merged, there are some conflicts. (sorry but it's necessary first)
Could you resolve the conflicts?

**Comment by Dane-Kang** [comment]
> @ZhenBei-Sin Could you let us know why the title is `tune tx power`?

Found there were difference RF power operations between PSRAM and DDR packages.
This adjustment are not changed DDR Power table but just modified RF power operations for compatible across both PSRAM and DDR packages

**Comment by sunghan-chang** [comment]
@ZhenBei-Sin @Dane-Kang Then, can we say `tune tx power`? Let's rewrite the title and merge this PR after resolving a conflict.

**Comment by sunghan-chang** [comment]
@ZhenBei-Sin @Dane-Kang We need this ASAP. Could you resolve the conflict ASAP?

**Review by sunghan-chang — APPROVED** [review]

**Comment by sunghan-chang** [comment]
@ZhenBei-Sin Quick question, Is this made with latest km0_km4_app.bin base?

**Comment by ZhenBei-Sin** [comment]
> @ZhenBei-Sin Quick question, Is this made with latest km0_km4_app.bin base?

YES.

**Pull request merged**
