### PR TITLE
libc/zoneinfo : Change mk_latest_tzrule.py to mk_opt_tzrule.py and fi…

### PR DESCRIPTION
**Pull request by jeongchanKim**
…le permissions

mk_opt_tzrule does not make the rule, but it just extracts the latest tzrule from the raw tz data.
File permission of utils_tzselect.c and gitignore is changed to 644.

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [2108fa4834e4e248cd5f0615496433f72d091a2b] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [2108fa4834e4e248cd5f0615496433f72d091a2b] - Code Rule Check OK.

**Comment by sunghan-chang** [comment]
@jeongchanKim As I said in offline, please check another file for permission and please modify the code together which calls python script.

**Comment by seinfra** [comment]
Target : [13d6b36f3aca00e9bc488e2d60beb26f10ab4a24] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [13d6b36f3aca00e9bc488e2d60beb26f10ab4a24] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [aa1dd77707ab2fc01215fdb0dad5c602357eb775] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [aa1dd77707ab2fc01215fdb0dad5c602357eb775] - Code Rule Check (C++) OK.

**Pull request merged**
