### PR TITLE
apps/examples: Fix define mtd mount path

### PR DESCRIPTION
**Pull request by KimDongEon**
fix mtd paths that depend on the board.

### CODE REVIEW

**Comment by seinfra** [comment]
Target : [8721d792502bcba01d70f304a8dd9dad35602986] - Code Rule Check (C++) OK.

**Comment by seinfra** [comment]
Target : [8721d792502bcba01d70f304a8dd9dad35602986] - Code Rule Check OK.

**Comment by sunghan-chang** [comment]
@KimDongEon Please don't modify this again with different commit. Please cherry pick Cypress commit from Cypress repo.

**Comment by sunghan-chang** [comment]
@KimDongEon Sorry for mis-understanding. There is no this change on Cypress repo. Anyway this change is wrong. Please re-check.

**Comment by KimDongEon** [comment]
close

**Pull request closed without merging**
