### PR TITLE
IMXRT1020_EVK: Download script changes to fix long boot time

### PR DESCRIPTION
**Pull request by btheosam**
imxrt1020-evk_download.sh:
	Perform the corresponding action ONLY on the those parititon
fed to download script. By default erasing userfs increases the boot time
as it has to be reinitialized while booting.

### CODE REVIEW

**Comment by btheosam** [comment]
**DONT MERGE:** This PR has a dependency on another PR
https://github.com/Samsung/TizenRT/pull/3552/files
. Untill that is reviewed and merged, this cant be. But can be reviewed in parallel.

**Comment by seinfra** [comment]
Target : [3f722670b31952538f6571575b99a4bdabc40c7e] - Code Rule Check OK.

**Comment by seinfra** [comment]
Target : [3f722670b31952538f6571575b99a4bdabc40c7e] - Code Rule Check (C++) OK.

**Comment by btheosam** [comment]
closing this due to a dependency another another PR.

**Pull request closed without merging**
