### PR TITLE
os/board/rtl8720e: Add the API for power rate table

### PR DESCRIPTION
**Pull request by lu04-wang**
…e and print power rate table

### CODE REVIEW

**Comment by sunghan-chang** [comment]
@lu04-wang If this library includes any unmerged PR change, please leave the number.

**Comment by lu04-wang** [comment]
> @lu04-wang If this library includes any unmerged PR change, please leave the number.

Hi,  Mr.Chang, There is no unmerged PR

**Review by ewoodev — COMMENTED** [review]
`…e and print power rate table`

This commit title is long. Also there is no commit detail. 
Please Could you check commit rule?

**Comment by lu04-wang** [comment]
> `…e and print power rate table`
> 
> This commit title is long. Also there is no commit detail. Please Could you check commit rule?

Hi @ewoodev  I have update the commit message, please help to check

**Comment by sunghan-chang** [comment]
@lu04-wang It looks good. Thank you for update.

**Comment by lu04-wang** [comment]
> @lu04-wang It looks good. Thank you for update. Let's reopen the PR.

Hi @sunghan-chang the issue is reopened

**Review by sunghan-chang — APPROVED** [review]

**Pull request merged**
