### PR TITLE
build/tools/amebasmart/imagetool: Add configuration for package type2…

### PR DESCRIPTION
**Pull request by jiangxiaoyunjoy**
… - DDR

    1. print package type before download/erase operation
   
    2. skip flash checking when addr >0x0A000000, as flash checking on external flash is not applicable
   
    3. If the image size exceed module flash size, report error and stop download. Therefore, error will be pop up if end addr > 0x0C000000 for package 1 and 0x0E000000 for package 2 DDR

    4. package 1 not able to download image to address between 0x09000000 to 0x0A000000 due to invalid flash mapping
   
Test ok on package 1/package 2/EVB

### CODE REVIEW

**Comment by sunghan-chang** [comment]
```
    1. print package type before download/erase operation
   
    2. skip flash checking when addr >0x0A000000
   
    3. error will be pop up if end addr > 0x0C000000 for package 1 and 0x0E000000 for package 2 DDR

    4. package 1 not able to download image to address between 0x09000000 to 0x0A000000
   
Test ok on package 1/package 2/EVB
```
Could you add more explanation for them?
1. Is there any example to know how to print the package type? Is that readable sentence or just number?
2. What is the flash checking? Do you mean that the tool will not check something for external flash? Why?
3. What is the `package 1`, `package 2`, `0x0C00_0000` and `0x0E00_0000`?
4. `package 2` can download something between `0x09000000 to 0x0A000000`? Because the `package 2` has 16MB internal flash?

**Comment by jiangxiaoyunjoy** [comment]
> 1. sentence

hi @sunghan-chang ,
1. package type will be printed in the download log
`==========================
Downloading bootparam binary
==========================

ImageTool 8730e for SDA V1.3

Number of Images: 1

Download bootparam.bin to: 0x08FFE000

Open serial port         ......    OK

UART download...
Check download mode      ......    OK
Download flashloader     ......    OK
Internal flash size: 32 MB + External flash size: 64 MB
--> Package 2:DDR.
Check flash size         ......    OK
Flash protection         ......    OK
Erase flash              ......    OK
Download image           ......    OK
Check checksum           ......    OK
Close serial port        ......    OK
`
Internal flash size: 16 MB + External flash size: 32 MB
--> Package 1.
Internal flash size: 32 MB + External flash size: 64 MB
--> Package 2:DDR.

2. flash checking is ignored if only download images to external flash. This is the request from SDA when implementing external flash feature. If you'd like to check the flash status of external flash in each download, please let me know.
3. package 1 has a flash size of 16+32MB, therefore the max addr can be assigned is (0x0A000000+32*1024*1024) = 0x0C000000. package 2 has a flash size of 32+64MB, therefore the max addr can be assigned is (0x0A000000+64*1024*1024) = 0x0E000000.If the image size exceed module flash size, report error and stop download.
4. package 2 can download between 0x09000000 to 0x0A000000, because the package 2 has 32MB internal flash: 0x08000000+32*1024*1024 = 0x0A000000, while package 1 only has 16MB: 0x08000000+16*1024*1024 = 0x09000000.
Thank you~

**Comment by sunghan-chang** [comment]
@jiangxiaoyunjoy Could you write your explanation above in the commit description?

**Comment by jiangxiaoyunjoy** [comment]
> @jiangxiaoyunjoy Could you write your explanation above in the commit description?

Hi @sunghan-chang , commit updated. 
Thank you~

**Review by sunghan-chang — APPROVED** [review]

**Comment by sunghan-chang** [comment]
@jiangxiaoyunjoy Thank you for update. Can I merge this now? Is there any PR to be merged first?

**Comment by jiangxiaoyunjoy** [comment]
> @jiangxiaoyunjoy Thank you for update. Can I merge this now? Is there any PR to be merged first?

Hi @sunghan-chang , you can merge this now~ No other PRs to be merged first.
Thank you~

**Pull request merged**
