### PR TITLE
Execute mem leak before during malloc failure, change mem leak allocation from dynamic to static

### PR DESCRIPTION
**Pull request by abhishek-samsung**

### CODE REVIEW

**Comment by abhishek-samsung** [comment]
failure in kernel heap,

```
run_all_mem_leak_checker: 
Kernel :
print_info: Type   |    Addr    | Size(byte) |    Owner   | PID 
print_info: ---------------------------------------------------
print_info: LEAK   | 0x6014c670 |        80  |  0xe04b2a7 | 4
print_info: *** 1 LEAKS, 0 BROKENS.
run_all_mem_leak_checker: 
Below are text addresses of loadable apps (and common binary if enabled) :
run_all_mem_leak_checker: The pc value of the allocation can be obtained by subtracting the text start address of the appropriate binary

run_all_mem_leak_checker: [common] Text Addr : 0xe161010, Text Size : 5533696
run_all_mem_leak_checker: [app1] Text Addr : 0xe6a8030, Text Size : 700416
run_all_mem_leak_checker: 
run_all_mem_leak_checker: app1 :
print_info: --------------------------------------------------- 
print_info: LEAK   | 0x60286c50 |        16  |  0xe16d4d5 | 23
print_info: LEAK   | 0x60286c70 |        32  |  0xe16d4d5 | 24
print_info: *** 2 LEAKS, 0 BROKENS.
mm_manage_alloc_fail: Allocation failed from kernel heap.
mm_manage_alloc_fail:  - requested size 40000000
mm_manage_alloc_fail:  - caller address = 0x0e047ff7
mm_manage_alloc_fail:  - largest free size : 1175040
mm_manage_alloc_fail:  - total free size   : 1176784
mm_check_heap_corruption: No heap corruption detected = 0x6027fff0
****************************************************************
REGION #0 Start=0x0x60120800, End=0x0x6027fff0, Size=1439744
****************************************************************
  MemAddr |   Size   | Status |    Owner   |  Pid  |
----------|----------|--------|------------|-------|
0x60120800 |       16 |   A    | 0x    dead |   0   |
0x60120810 |     1728 |   A    | 0x e01a209 |   0   |
0x60120ed0 |      416 |   A    | 0x e01a371 |   0   |
0x60121070 |     1728 |   A    | 0x e01a209 |   0   |
0x60121730 |      416 |   A    | 0x e01a371 |   0   |
0x601218d0 |     3360 |   A    | 0x e024ac5 |   0   |
```

failure in user heap,
```
run_all_mem_leak_checker: 
Kernel :
print_info: Type   |    Addr    | Size(byte) |    Owner   | PID 
print_info: ---------------------------------------------------
print_info: LEAK   | 0x6014c670 |        80  |  0xe04b2a7 | 4
print_info: *** 1 LEAKS, 0 BROKENS.
run_all_mem_leak_checker: 
Below are text addresses of loadable apps (and common binary if enabled) :
run_all_mem_leak_checker: The pc value of the allocation can be obtained by subtracting the text start address of the appropriate binary

run_all_mem_leak_checker: [common] Text Addr : 0xe161010, Text Size : 5533696
run_all_mem_leak_checker: [app1] Text Addr : 0xe6a8030, Text Size : 700416
run_all_mem_leak_checker: 
run_all_mem_leak_checker: app1 :
print_info: Type   |    Addr    | Size(byte) |    Owner   | PID 
print_info: ---------------------------------------------------
print_info: LEAK   | 0x60286c50 |        16  |  0xe16d4d5 | 21
print_info: *** 1 LEAKS, 0 BROKENS.
mm_manage_alloc_fail: Allocation failed from user heap.
mm_manage_alloc_fail:  - requested size 40000000
mm_manage_alloc_fail:  - largest free size : 5194944
mm_manage_alloc_fail:  - total free size   : 5194992
mm_check_heap_corruption: Heap start = 0x60280a30 end = 0x6077fff0
mm_check_heap_corruption: No heap corruption detected
****************************************************************
REGION #0 Start=0x0x60280a30, End=0x0x6077fff0, Size=5240272
****************************************************************
  MemAddr |   Size   | Status |    Owner   |  Pid  |
----------|----------|--------|------------|-------|
0x60280a30 |       16 |   A    | 0x    dead |  15   |
0x60280a40 |     8208 |   A    | 0x e028fdd |  16(S)|
0x60282a50 |      416 |   A    | 0x e01a371 |  15   |
0x60282bf0 |      272 |   A    | 0x e0409bd |  15   |
0x60282d00 |      272 |   A    | 0x e0409bd |  15   |

```

**Comment by sunghan-chang** [comment]
@abhishek-samsung What about mem leak checker in TASH?

**Comment by abhishek-samsung** [comment]
> @abhishek-samsung What about mem leak checker in TASH?

I changed printf to mfdbg, so func names are also getting printed.

```
TASH>>
TASH>>
TASH>>mem_leak
TASH>>run_all_mem_leak_checker: 
Kernel :
print_info: Type   |    Addr    | Size(byte) |    Owner   | PID 
print_info: ---------------------------------------------------
print_info: LEAK   | 0x6014c670 |        80  |  0xe04b2a7 | 4
print_info: *** 1 LEAKS, 0 BROKENS.
run_all_mem_leak_checker: 
Below are text addresses of loadable apps (and common binary if enabled) :
run_all_mem_leak_checker: The pc value of the allocation can be obtained by subtracting the text start address of the appropriate binary

run_all_mem_leak_checker: [common] Text Addr : 0xe161010, Text Size : 5533696
run_all_mem_leak_checker: [app1] Text Addr : 0xe6a8030, Text Size : 700416
run_all_mem_leak_checker: 
run_all_mem_leak_checker: app1 :
print_info: Type   |    Addr    | Size(byte) |    Owner   | PID 
print_info: ---------------------------------------------------
print_info: LEAK   | 0x60286c50 |        16  |  0xe16d4d5 | 21
print_info: LEAK   | 0x60286c70 |        32  |  0xe16d4d5 | 22
print_info: *** 2 LEAKS, 0 BROKENS.

```

**Comment by sunghan-chang** [comment]
How about removing function names? 
It looks strange in TASH response. And no need to print it in assert or alloc fail either.

**Comment by abhishek-samsung** [comment]
> How about removing function names? It looks strange in TASH response. And no need to print it in assert or alloc fail either.

I have removed func name print and updated the PR,

mem leak in tash :
```
TASH>>mem_leak
TASH>>
Kernel :
Type   |    Addr    | Size(byte) |    Owner   | PID 
---------------------------------------------------
LEAK   | 0x6014c670 |        80  |  0xe04b10f | 4
*** 1 LEAKS, 0 BROKENS.

Below are text addresses of loadable apps (and common binary if enabled) :
The pc value of the allocation can be obtained by subtracting the text start address of the appropriate binary

[common] Text Addr : 0xe161010, Text Size : 5533696
[app1] Text Addr : 0xe6a8030, Text Size : 700416

app1 :
Type   |    Addr    | Size(byte) |    Owner   | PID 
---------------------------------------------------
LEAK   | 0x60286c50 |        16  |  0xe16d4d5 | 21
LEAK   | 0x60286c70 |        32  |  0xe16d4d5 | 22
*** 2 LEAKS, 0 BROKENS.
```

mem_leak during malloc fail :
```
Kernel :
Type   |    Addr    | Size(byte) |    Owner   | PID 
---------------------------------------------------
LEAK   | 0x6014c670 |        80  |  0xe04b10f | 4
*** 1 LEAKS, 0 BROKENS.

Below are text addresses of loadable apps (and common binary if enabled) :
The pc value of the allocation can be obtained by subtracting the text start address of the appropriate binary

[common] Text Addr : 0xe161010, Text Size : 5533696
[app1] Text Addr : 0xe6a8030, Text Size : 700416

app1 :
Type   |    Addr    | Size(byte) |    Owner   | PID 
---------------------------------------------------
LEAK   | 0x60286c50 |        16  |  0xe16d4d5 | 21
LEAK   | 0x60286c70 |        32  |  0xe16d4d5 | 22
LEAK   | 0x6028bb40 |        16  |  0xe16d4d5 | 24
*** 3 LEAKS, 0 BROKENS.
mm_manage_alloc_fail: Allocation failed from user heap.
mm_manage_alloc_fail:  - requested size 40000000
mm_manage_alloc_fail:  - caller address = 0x0e16d117
mm_manage_alloc_fail:  - largest free size : 5194912
mm_manage_alloc_fail:  - total free size   : 5194912
mm_check_heap_corruption: Heap start = 0x60280a30 end = 0x6077fff0
mm_check_heap_corruption: No heap corruption detected
****************************************************************
REGION #0 Start=0x0x60280a30, End=0x0x6077fff0, Size=5240272
****************************************************************
  MemAddr |   Size   | Status |    Owner   |  Pid  |
----------|----------|--------|------------|-------|
0x60280a30 |       16 |   A    | 0x    dead |  15   |
0x60280a40 |     8208 |   A    | 0x e028e45 |  16(S)|
0x60282a50 |      416 |   A    | 0x e01a371 |  15   |
0x60282bf0 |      272 |   A    | 0x e040825 |  15   |
0x60282d00 |      272 |   A    | 0x e040825 |  15   |

```

**Review by sunghan-chang — APPROVED** [review]

**Pull request merged**
