### PR TITLE
[DO NOT MERGE] build/configs/rtl8730e: Change PSRAM size for KM4 image

### PR DESCRIPTION
**Pull request by jwei5**
- Revert KM4 PSRAM size to 242k to test for fault issue on PR6016

### CODE REVIEW

**Comment by jwei5** [comment]
[PR6017.zip](https://github.com/Samsung/TizenRT/files/13817281/PR6017.zip)
Diff file and file changes for PR6017

**Comment by Dane-Kang** [comment]
ERROR: CFLAG string is too long [4331/4096]: -fno-common -Wall -Wstrict-prototypes -Wshadow -Wundef -fno-builtin -fno-common -Wall -Wstrict-prototypes -Wshadow -Wundef -Wno-implicit-function-declaration -Wno-unused-function -Wno-unused-but-set-variable -g -Os -fno-strict-aliasing -fno-strength-reduce -fomit-frame-pointer -mthumb -mcpu=cortex-a32 -mfloat-abi=hard -mfpu=neon-vfpv4 -I. -isystem /root/product/.tizenrt/os/include -isystem /root/product/.tizenrt/os/../framework/include -isystem /root/product/.tizenrt/os/../external/include -isystem /root/product/.tizenrt/os/net/lwip/src/include -D__KERNEL__ -pipe -ffunction-sections -fdata-sections -DCONFIG_PLATFORM_AMEBAD2 -DCONFIG_USE_MBEDTLS_ROM_ALG -DDM_ODM_SUPPORT_TYPE=32 -DARM_ARCH_MAJOR=7 -DLOG_LEVEL=40 -DARMV7_SUPPORTS_LARGE_PAGE_ADDRESSING=1 -DPLAT_RO_XLAT_TABLES=0 -DPLAT_XLAT_TABLES_DYNAMIC=0 -DENABLE_BTI=0 -DHW_ASSISTED_COHERENCY=0 -DENABLE_ASSERTIONS=1 -DWARMBOOT_ENABLE_DCACHE_EARLY=0 -DSTD_PRINTF -DCONFIG_PLATFORM_TIZENRT_OS=1 -I/root/product/.tizenrt/os/board/rtl8730e/include -I/root/product/.tizenrt/os/arch/arm/src/armv7-a -I/root/product/.tizenrt/os/board/rtl8730e/src/project/realtek_amebaD2_va0_example/inc/inc_ap -I/root/product/.tizenrt/os/board/rtl8730e/src/component/soc/amebad2/bootloader -I/root/product/.tizenrt/os/board/rtl8730e/src/component/soc/amebad2/cmsis -I/root/product/.tizenrt/os/board/rtl8730e/src/component/soc/amebad2/cmsis-dsp/Include -I/root/product/.tizenrt/os/board/rtl8730e/src/component/soc/amebad2/cmsis-dsp/PrivateInclude -I/root/product/.tizenrt/os/board/rtl8730e/src/component/soc/amebad2/fwlib/include -I/root/product/.tizenrt/os/board/rtl8730e/src/component/soc/amebad2/fwlib/ap_core -I/root/product/.tizenrt/os/board/rtl8730e/src/component/soc/amebad2/app/monitor/include -I/root/product/.tizenrt/os/board/rtl8730e/src/component/soc/amebad2/swlib -I/root/product/.tizenrt/os/board/rtl8730e/src/component/soc/amebad2/misc -I/root/product/.tizenrt/os/board/rtl8730e/src/component/stdlib -I/root/product/.tizenrt/os/board/rtl8730e/src/component/usrcfg/rtl8730e/include -I/root/product/.tizenrt/os/board/rtl8730e/src/component/wifi/api -I/root/product/.tizenrt/os/board/rtl8730e/src/component/wifi/driver/include -I/root/product/.tizenrt/os/board/rtl8730e/src/component/wifi/inic -I/root/product/.tizenrt/os/board/rtl8730e/src/component/wifi/wpa_supplicant/src/crypto -I/root/product/.tizenrt/os/board/rtl8730e/src/component/lwip/api -I/root/product/.tizenrt/os/board/rtl8730e/src/component/os/tizenrt -I/root/product/.tizenrt/os/board/rtl8730e/src/component/mbed/targets/hal/rtl8730e -I/root/product/.tizenrt/os/board/rtl8730e/src/component/os_dep/include -I/root/product/.tizenrt/os/board/rtl8730e/src/component/wifi/wpa_supplicant/wpa_lite -I/root/product/.tizenrt/os/board/rtl8730e/src/component/mbed/api -I/root/product/.tizenrt/os/board/rtl8730e/src/component/mbed/hal -I/root/product/.tizenrt/os/board/rtl8730e/src/component/mbed/hal_ext -I/root/product/.tizenrt/os/board/rtl8730e/src/component/mbed/targets/hal/rtl8730e -I/root/product/.tizenrt/os/board/rtl8730e/src/component/os_dep -I/root/product/.tizenrt/os/net/netmgr -I/root/product/.tizenrt/os/board/rtl8730e/src/component/file_system/vfs2.0 -I/root/product/.tizenrt/os/board/rtl8730e/src/component/file_system/ftl -I/root/product/.tizenrt/os/board/rtl8730e/src/component/file_system/kv -I/root/product/.tizenrt/os/board/rtl8730e/src/component/bluetooth/inc -I/root/product/.tizenrt/os/board/rtl8730e/src/component/bluetooth/profile/client -I/root/product/.tizenrt/os/board/rtl8730e/src/component/bluetooth/driver/inc -I/root/product/.tizenrt/os/board/rtl8730e/src/component/bluetooth/driver/inc/hci -I/root/product/.tizenrt/os/board/rtl8730e/src/component/bluetooth/api/rtk_stack -I/root/product/.tizenrt/os/board/rtl8730e/src/component/bluetooth/rtk_stack/inc -I/root/product/.tizenrt/os/board/rtl8730e/src/component/bluetooth/rtk_stack/platform/amebad2/inc -I/root/product/.tizenrt/os/arch/arm/src/chip -I/root/product/.tizenrt/os/arch/arm/src/common -I/root/product/.tizenrt/os/board/rtl8730e/src/component/soc/amebad2/cmsis -I/root/product/.tizenrt/os/board/common -I/root/product/.tizenrt/os/board/rtl8730e/src -I/root/product/.tizenrt/os/arch/arm/src/armv7-a -I/root/product/.tizenrt/os/board/rtl8730e/src/component/soc/amebad2/bootloader -I/root/product/.tizenrt/os/se/ameba
make[2]: *** [.depend] Error 1
Makefile:222: recipe for target '.depend' failed
make[2]: Leaving directory '/root/product/.tizenrt/os/board/rtl8730e/src'

**Comment by jwei5** [comment]
[PR6017_trace_heap.zip](https://github.com/Samsung/TizenRT/files/13827161/PR6017_trace_heap.zip)
For commit da70a6

**Comment by jwei5** [comment]
[disable_km4_main.zip](https://github.com/Samsung/TizenRT/files/13857787/disable_km4_main.zip)
Disable KM4 main for testing

**Comment by Dane-Kang** [comment]
[latest_patch.diff.txt](https://github.com/Samsung/TizenRT/files/13896858/latest_patch.diff.txt)

**Comment by sunghan-chang** [comment]
@jwei5 @Dane-Kang Is this necessary? If not, let's close.

**Comment by jwei5** [comment]
Hi @sunghan-chang , we can close this PR.

**Pull request closed without merging**
